include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    # Treat missing returns as errors
    missing_required_param: error
    missing_return: error
    # Warnings for code quality
    todo: warning
    deprecated_member_use: warning

linter:
  rules:
    # Error rules - require declarations
    - always_declare_return_types
    - always_require_non_null_named_parameters
    
    # Style rules
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - unnecessary_const
    - unnecessary_new
    - unnecessary_this
    
    # Documentation
    - package_api_docs
    - public_member_api_docs
    
    # Code quality
    - avoid_print
    - avoid_returning_null_for_void
    - avoid_unnecessary_containers
    - no_duplicate_case_values
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_iterable_whereType
    - prefer_null_aware_operators
    - prefer_typing_uninitialized_variables
    - unawaited_futures
    - unnecessary_null_checks
    - unnecessary_null_in_if_null_operators
    - use_build_context_synchronously
    
    # Effective Dart
    - camel_case_types
    - constant_identifier_names
    - file_names
    - non_constant_identifier_names
    - library_names
    - library_prefixes
    
    # Best practices
    - avoid_bool_literals_in_conditional_expressions
    - avoid_catches_without_on_clauses
    - avoid_catching_errors
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_null_checks_in_equality_operators
    - avoid_renaming_method_parameters
    - avoid_return_types_on_setters
    - avoid_shadowing_type_parameters
    - avoid_single_cascade_in_expression_statements
    - avoid_types_as_parameter_names
    - avoid_void_async
    - cancel_subscriptions
    - close_sinks
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - hash_and_equals
    - implementation_imports
    - library_private_types_in_public_api
    - null_closures
    - overridden_fields
    - package_names
    - prefer_adjacent_string_concatenation
    - prefer_collection_literals
    - prefer_conditional_assignment
    - prefer_contains
    - prefer_equal_for_default_values
    - prefer_final_fields
    - prefer_for_elements_to_map_fromIterable
    - prefer_function_declarations_over_variables
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_spread_collections
    - recursive_getters
    - slash_for_doc_comments
    - sort_child_properties_last
    - type_init_formals
    - unnecessary_brace_in_string_interps
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_parenthesis
    - unnecessary_statements
    - unnecessary_string_interpolations
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
    - void_checks
