// ignore_for_file: type=lint, unused_import

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset('package:bacnet_plugin/src/native/bindings.g.dart')
library;

import 'dart:ffi' as ffi;

/// Adds or replaces a static device address binding.
/// @param host IPv4 address or host name of the device (or of the router).
/// @param net remote network number (0 for local devices).
/// @param adr remote MAC address behind the router (NULL for local).
@ffi.Native<
  ffi.Int32 Function(
    ffi.Uint32,
    ffi.Pointer<ffi.Char>,
    ffi.Uint16,
    ffi.Uint16,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint8,
    ffi.Uint16,
  )
>()
external int bacnet_plugin_bind_device(
  int device_id,
  ffi.Pointer<ffi.Char> host,
  int port,
  int net,
  ffi.Pointer<ffi.Uint8> adr,
  int adr_len,
  int max_apdu,
);

/// Returns 1 and fills the optional outputs when the device is bound,
/// 0 otherwise. `mac` must hold at least 7 bytes.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Uint32,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint8>,
    ffi.Pointer<ffi.Uint16>,
    ffi.Pointer<ffi.Uint16>,
  )
>(isLeaf: true)
external int bacnet_plugin_device_binding(
  int device_id,
  ffi.Pointer<ffi.Uint8> mac,
  ffi.Pointer<ffi.Uint8> mac_len,
  ffi.Pointer<ffi.Uint16> net,
  ffi.Pointer<ffi.Uint16> max_apdu,
);

/// Sets the password DeviceCommunicationControl and ReinitializeDevice
/// requests must carry (up to 20 characters). NULL or "" accepts requests
/// without a password.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Char>)>()
external int bacnet_plugin_device_set_password(ffi.Pointer<ffi.Char> password);

/// Sets a string property of the local Device object
/// (vendor name, model name, description, location, firmware, version).
@ffi.Native<ffi.Int32 Function(ffi.Uint32, ffi.Pointer<ffi.Char>)>()
external int bacnet_plugin_device_set_string(
  int property,
  ffi.Pointer<ffi.Char> value,
);

/// Sets the vendor identifier of the local Device object.
@ffi.Native<ffi.Int32 Function(ffi.Uint16)>()
external int bacnet_plugin_device_set_vendor_id(int vendor_id);

/// Empties the event buffer.
@ffi.Native<ffi.Void Function()>(isLeaf: true)
external void bacnet_plugin_events_clear();

/// Pointer to the event buffer. Valid until the next engine call.
@ffi.Native<ffi.Pointer<ffi.Uint8> Function()>(isLeaf: true)
external ffi.Pointer<ffi.Uint8> bacnet_plugin_events_data();

/// Number of bytes in the event buffer.
@ffi.Native<ffi.Uint32 Function()>(isLeaf: true)
external int bacnet_plugin_events_length();

/// Initializes the BACnet/IP datalink and the stack.
///
/// @param iface interface name ("eth0"), IPv4 address ("192.168.1.10") or NULL
/// for the default interface.
/// @param port UDP port (47808 by default).
/// @param device_instance own Device object instance.
/// @param socket_buffer_bytes SO_RCVBUF / SO_SNDBUF size, 0 keeps OS default.
/// @return BP_OK or a negative BP_ERR_* code.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Uint16, ffi.Uint32, ffi.Int32)
>()
external int bacnet_plugin_init(
  ffi.Pointer<ffi.Char> iface,
  int port,
  int device_instance,
  int socket_buffer_bytes,
);

/// Copies the own BACnet/IP address (IPv4 address and UDP port, 6 bytes) to
/// `mac`, which must hold at least 6 bytes: where devices send
/// notifications to this engine.
/// @return the number of bytes copied or a negative BP_ERR_* code.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Uint8>)>(isLeaf: true)
external int bacnet_plugin_local_address(ffi.Pointer<ffi.Uint8> mac);

/// Creates a server object. Returns the instance or a negative error.
@ffi.Native<
  ffi.Int64 Function(
    ffi.Uint16,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
  )
>(isLeaf: true)
external int bacnet_plugin_object_create(
  int object_type,
  int instance,
  ffi.Pointer<ffi.Uint32> error_class,
  ffi.Pointer<ffi.Uint32> error_code,
);

/// Deletes a server object.
@ffi.Native<ffi.Int32 Function(ffi.Uint16, ffi.Uint32)>(isLeaf: true)
external int bacnet_plugin_object_delete(int object_type, int instance);

/// Reads a property of a server object as application encoded data.
/// @return encoded length or a negative error code.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Uint16,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint16,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
  )
>(isLeaf: true)
external int bacnet_plugin_object_read(
  int object_type,
  int instance,
  int property,
  int array_index,
  ffi.Pointer<ffi.Uint8> buffer,
  int buffer_len,
  ffi.Pointer<ffi.Uint32> error_class,
  ffi.Pointer<ffi.Uint32> error_code,
);

/// Sets the object description (UTF-8, copied).
@ffi.Native<ffi.Int32 Function(ffi.Uint16, ffi.Uint32, ffi.Pointer<ffi.Char>)>(
  isLeaf: true,
)
external int bacnet_plugin_object_set_description(
  int object_type,
  int instance,
  ffi.Pointer<ffi.Char> description,
);

/// Sets the object name (UTF-8, copied).
@ffi.Native<ffi.Int32 Function(ffi.Uint16, ffi.Uint32, ffi.Pointer<ffi.Char>)>(
  isLeaf: true,
)
external int bacnet_plugin_object_set_name(
  int object_type,
  int instance,
  ffi.Pointer<ffi.Char> name,
);

/// Sets a numeric property locally (no network write semantics):
/// present-value (85), out-of-service (81), units (117), cov-increment (22).
/// A NaN present value relinquishes the given priority of commandable objects.
@ffi.Native<
  ffi.Int32 Function(ffi.Uint16, ffi.Uint32, ffi.Uint32, ffi.Double, ffi.Uint8)
>(isLeaf: true)
external int bacnet_plugin_object_set_number(
  int object_type,
  int instance,
  int property,
  double value,
  int priority,
);

/// Applies many present value updates at once.
/// @return number of successfully applied updates.
@ffi.Native<
  ffi.Int32 Function(ffi.Pointer<bp_present_value_update_t>, ffi.Uint32)
>(isLeaf: true)
external int bacnet_plugin_object_set_present_values(
  ffi.Pointer<bp_present_value_update_t> updates,
  int count,
);

/// Sets the state texts of a multi-state object: NUL separated strings
/// (e.g. "Off\0On\0Auto\0"); defines the number of states.
@ffi.Native<
  ffi.Int32 Function(ffi.Uint16, ffi.Uint32, ffi.Pointer<ffi.Char>, ffi.Uint32)
>(isLeaf: true)
external int bacnet_plugin_object_set_state_texts(
  int object_type,
  int instance,
  ffi.Pointer<ffi.Char> state_texts,
  int length,
);

/// Sets the present value of a CharacterString Value object.
@ffi.Native<ffi.Int32 Function(ffi.Uint16, ffi.Uint32, ffi.Pointer<ffi.Char>)>(
  isLeaf: true,
)
external int bacnet_plugin_object_set_string(
  int object_type,
  int instance,
  ffi.Pointer<ffi.Char> value,
);

/// Writes an application encoded value using WriteProperty semantics.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Uint16,
    ffi.Uint32,
    ffi.Uint32,
    ffi.Int32,
    ffi.Uint8,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint16,
    ffi.Pointer<ffi.Uint32>,
    ffi.Pointer<ffi.Uint32>,
  )
>(isLeaf: true)
external int bacnet_plugin_object_write(
  int object_type,
  int instance,
  int property,
  int array_index,
  int priority,
  ffi.Pointer<ffi.Uint8> data,
  int data_len,
  ffi.Pointer<ffi.Uint32> error_class,
  ffi.Pointer<ffi.Uint32> error_code,
);

/// Waits up to timeout_ms for network traffic (or a wakeup), processes up to
/// max_packets packets and runs all stack timers.
/// @return number of processed packets or a negative error code.
@ffi.Native<ffi.Int32 Function(ffi.Uint32, ffi.Uint32)>()
external int bacnet_plugin_poll(int timeout_ms, int max_packets);

/// Registers as foreign device with a BBMD and keeps the registration.
@ffi.Native<ffi.Int32 Function(ffi.Pointer<ffi.Char>, ffi.Uint16, ffi.Uint16)>()
external int bacnet_plugin_register_foreign_device(
  ffi.Pointer<ffi.Char> host,
  int port,
  int ttl_seconds,
);

/// Sends a confirmed request to a bound device.
/// @param service confirmed service choice.
/// @param data encoded service request (without APDU header).
/// @return invoke id (1..255) or a negative BP_ERR_* code.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Uint32,
    ffi.Uint8,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint16,
    ffi.Uint8,
  )
>(isLeaf: true)
external int bacnet_plugin_send_confirmed(
  int device_id,
  int service,
  ffi.Pointer<ffi.Uint8> data,
  int data_len,
  int priority,
);

/// Broadcasts an I-Am for the local device.
@ffi.Native<ffi.Int32 Function()>()
external int bacnet_plugin_send_i_am();

/// Sends an unconfirmed request.
/// @param device_id target device or BP_DEVICE_UNKNOWN for a broadcast.
/// @param network broadcast network: 0 = local, 0xFFFF = global, else remote.
@ffi.Native<
  ffi.Int32 Function(
    ffi.Uint32,
    ffi.Uint16,
    ffi.Uint8,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint16,
  )
>(isLeaf: true)
external int bacnet_plugin_send_unconfirmed(
  int device_id,
  int network,
  int service,
  ffi.Pointer<ffi.Uint8> data,
  int data_len,
);

/// Turns the local Device object into a BACnet server: registers the server
/// service handlers (Who-Is, Read/WriteProperty(Multiple), SubscribeCOV,
/// ReadRange, DCC, ...) and sends an I-Am.
@ffi.Native<ffi.Int32 Function(ffi.Uint32, ffi.Pointer<ffi.Char>)>()
external int bacnet_plugin_server_enable(
  int device_instance,
  ffi.Pointer<ffi.Char> device_name,
);

/// Sets a tunable (BP_OPTION_*). Returns BP_OK or BP_ERR_INVALID_ARGUMENT.
@ffi.Native<ffi.Int32 Function(ffi.Int32, ffi.Int64)>(isLeaf: true)
external int bacnet_plugin_set_option(int option, int value);

/// Closes sockets and resets the engine state.
@ffi.Native<ffi.Void Function()>()
external void bacnet_plugin_shutdown();

/// Fills `out` with engine statistics.
@ffi.Native<ffi.Void Function(ffi.Pointer<bp_stats_t>)>(isLeaf: true)
external void bacnet_plugin_stats(ffi.Pointer<bp_stats_t> out);

/// Removes the address binding of a device.
@ffi.Native<ffi.Void Function(ffi.Uint32)>(isLeaf: true)
external void bacnet_plugin_unbind_device(int device_id);

/// Version string of the engine and the bundled bacnet-stack.
@ffi.Native<ffi.Pointer<ffi.Char> Function()>(isLeaf: true)
external ffi.Pointer<ffi.Char> bacnet_plugin_version();

/// Interrupts a blocking bacnet_plugin_poll(). Safe from any thread.
@ffi.Native<ffi.Void Function()>(isLeaf: true)
external void bacnet_plugin_wakeup();

const int BP_DEVICE_UNKNOWN = 4294967295;

const int BP_ERR_ALREADY_INITIALIZED = -2;

const int BP_ERR_APDU_TOO_LARGE = -7;

const int BP_ERR_COMMUNICATION_DISABLED = -9;

const int BP_ERR_DATALINK = -4;

const int BP_ERR_INVALID_ARGUMENT = -3;

const int BP_ERR_NOT_BOUND = -5;

const int BP_ERR_NOT_INITIALIZED = -1;

const int BP_ERR_NO_MEMORY = -11;

const int BP_ERR_NO_TRANSACTION = -6;

const int BP_ERR_OBJECT = -10;

const int BP_ERR_SEND_FAILED = -8;

const int BP_ERR_SERVER_DISABLED = -13;

const int BP_ERR_UNSUPPORTED = -12;

const int BP_EVENT_ABORT = 5;

const int BP_EVENT_COMPLEX_ACK = 1;

const int BP_EVENT_CONFIRMED_NOTIFICATION = 8;

const int BP_EVENT_ERROR = 3;

const int BP_EVENT_LOG = 10;

const int BP_EVENT_REJECT = 4;

const int BP_EVENT_SERVICE = 11;

const int BP_EVENT_SIMPLE_ACK = 2;

const int BP_EVENT_TIMEOUT = 6;

const int BP_EVENT_UNCONFIRMED = 7;

const int BP_EVENT_WRITE = 9;

const int BP_FLAG_ABORT_FROM_SERVER = 1;

const int BP_FLAG_COMPLEX = 2;

const int BP_FLAG_LOCAL = 4;

const int BP_FLAG_SEGMENTED = 8;

const int BP_OK = 0;

const int BP_OPTION_APDU_RETRIES = 5;

const int BP_OPTION_APDU_TIMEOUT_MS = 4;

const int BP_OPTION_COV_SCAN_BUDGET = 6;

const int BP_OPTION_COV_SCAN_INTERVAL_MS = 2;

const int BP_OPTION_MAX_EVENT_BUFFER = 3;

const int BP_OPTION_MAX_SEGMENTS = 7;

const int BP_OPTION_STRICT_SOURCE = 1;

/// Header that precedes every event in the event buffer (host byte order,
/// 48 bytes, no padding). `data_len` bytes of payload follow the header.
final class bp_event_header_t extends ffi.Struct {
  @ffi.Uint8()
  external int kind;

  @ffi.Uint8()
  external int service;

  @ffi.Uint8()
  external int invoke_id;

  @ffi.Uint8()
  external int flags;

  @ffi.Uint32()
  external int device_id;

  @ffi.Uint32()
  external int a;

  @ffi.Uint32()
  external int b;

  @ffi.Uint32()
  external int c;

  @ffi.Int32()
  external int d;

  @ffi.Uint8()
  external int priority;

  @ffi.Uint8()
  external int src_mac_len;

  @ffi.Uint16()
  external int src_net;

  @ffi.Array.multi([7])
  external ffi.Array<ffi.Uint8> src_mac;

  @ffi.Uint8()
  external int src_len;

  @ffi.Array.multi([7])
  external ffi.Array<ffi.Uint8> src_adr;

  @ffi.Uint8()
  external int reserved0;

  @ffi.Uint16()
  external int data_len;

  @ffi.Uint16()
  external int reserved1;
}

/// Batched present value update for server objects.
final class bp_present_value_update_t extends ffi.Struct {
  @ffi.Uint32()
  external int instance;

  @ffi.Uint16()
  external int object_type;

  @ffi.Uint8()
  external int priority;

  @ffi.Uint8()
  external int reserved;

  @ffi.Double()
  external double value;

  static ffi.Pointer<bp_present_value_update_t> $allocate(
    ffi.Allocator $allocator, {
    required int instance,
    required int object_type,
    required int priority,
    required int reserved,
    required double value,
  }) => $allocator<bp_present_value_update_t>()
    ..ref.instance = instance
    ..ref.object_type = object_type
    ..ref.priority = priority
    ..ref.reserved = reserved
    ..ref.value = value;
}

/// Engine statistics.
final class bp_stats_t extends ffi.Struct {
  @ffi.Uint64()
  external int packets_received;

  @ffi.Uint64()
  external int requests_sent;

  @ffi.Uint64()
  external int replies_dropped;

  @ffi.Uint64()
  external int events_dropped;

  @ffi.Uint64()
  external int timeouts;

  @ffi.Uint64()
  external int poll_calls;

  @ffi.Uint32()
  external int tsm_idle;

  @ffi.Uint32()
  external int bound_devices;

  @ffi.Uint32()
  external int event_buffer_capacity;

  /// Complex ACKs received in segments and reassembled.
  @ffi.Uint32()
  external int segmented_replies;

  static ffi.Pointer<bp_stats_t> $allocate(
    ffi.Allocator $allocator, {
    required int packets_received,
    required int requests_sent,
    required int replies_dropped,
    required int events_dropped,
    required int timeouts,
    required int poll_calls,
    required int tsm_idle,
    required int bound_devices,
    required int event_buffer_capacity,
    required int segmented_replies,
  }) => $allocator<bp_stats_t>()
    ..ref.packets_received = packets_received
    ..ref.requests_sent = requests_sent
    ..ref.replies_dropped = replies_dropped
    ..ref.events_dropped = events_dropped
    ..ref.timeouts = timeouts
    ..ref.poll_calls = poll_calls
    ..ref.tsm_idle = tsm_idle
    ..ref.bound_devices = bound_devices
    ..ref.event_buffer_capacity = event_buffer_capacity
    ..ref.segmented_replies = segmented_replies;
}
