// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet engineering units (BACnetEngineeringUnits).
abstract final class BacnetEngineeringUnits {
  /// Square Meters.
  static const int squareMeters = 0;

  /// Square Feet.
  static const int squareFeet = 1;

  /// Milliamperes.
  static const int milliamperes = 2;

  /// Amperes.
  static const int amperes = 3;

  /// Ohms.
  static const int ohms = 4;

  /// Volts.
  static const int volts = 5;

  /// Kilovolts.
  static const int kilovolts = 6;

  /// Megavolts.
  static const int megavolts = 7;

  /// Volt Amperes.
  static const int voltAmperes = 8;

  /// Kilovolt Amperes.
  static const int kilovoltAmperes = 9;

  /// Megavolt Amperes.
  static const int megavoltAmperes = 10;

  /// Volt Amperes Reactive.
  static const int voltAmperesReactive = 11;

  /// Kilovolt Amperes Reactive.
  static const int kilovoltAmperesReactive = 12;

  /// Megavolt Amperes Reactive.
  static const int megavoltAmperesReactive = 13;

  /// Degrees Phase.
  static const int degreesPhase = 14;

  /// Power Factor.
  static const int powerFactor = 15;

  /// Joules.
  static const int joules = 16;

  /// Kilojoules.
  static const int kilojoules = 17;

  /// Watt Hours.
  static const int wattHours = 18;

  /// Kilowatt Hours.
  static const int kilowattHours = 19;

  /// BTUs.
  static const int btus = 20;

  /// Therms.
  static const int therms = 21;

  /// Ton Hours.
  static const int tonHours = 22;

  /// Joules Per Kilogram Dry Air.
  static const int joulesPerKilogramDryAir = 23;

  /// BTUs Per Pound Dry Air.
  static const int btusPerPoundDryAir = 24;

  /// Cycles Per Hour.
  static const int cyclesPerHour = 25;

  /// Cycles Per Minute.
  static const int cyclesPerMinute = 26;

  /// Hertz.
  static const int hertz = 27;

  /// Grams Of Water Per Kilogram Dry Air.
  static const int gramsOfWaterPerKilogramDryAir = 28;

  /// Percent Relative Humidity.
  static const int percentRelativeHumidity = 29;

  /// Millimeters.
  static const int millimeters = 30;

  /// Meters.
  static const int meters = 31;

  /// Inches.
  static const int inches = 32;

  /// Feet.
  static const int feet = 33;

  /// Watts Per Square Foot.
  static const int wattsPerSquareFoot = 34;

  /// Watts Per Square Meter.
  static const int wattsPerSquareMeter = 35;

  /// Lumens.
  static const int lumens = 36;

  /// Luxes.
  static const int luxes = 37;

  /// Foot Candles.
  static const int footCandles = 38;

  /// Kilograms.
  static const int kilograms = 39;

  /// Pounds Mass.
  static const int poundsMass = 40;

  /// Tons.
  static const int tons = 41;

  /// Kilograms Per Second.
  static const int kilogramsPerSecond = 42;

  /// Kilograms Per Minute.
  static const int kilogramsPerMinute = 43;

  /// Kilograms Per Hour.
  static const int kilogramsPerHour = 44;

  /// Pounds Mass Per Minute.
  static const int poundsMassPerMinute = 45;

  /// Pounds Mass Per Hour.
  static const int poundsMassPerHour = 46;

  /// Watts.
  static const int watts = 47;

  /// Kilowatts.
  static const int kilowatts = 48;

  /// Megawatts.
  static const int megawatts = 49;

  /// BTUs Per Hour.
  static const int btusPerHour = 50;

  /// Horsepower.
  static const int horsepower = 51;

  /// Tons Refrigeration.
  static const int tonsRefrigeration = 52;

  /// Pascals.
  static const int pascals = 53;

  /// Kilopascals.
  static const int kilopascals = 54;

  /// Bars.
  static const int bars = 55;

  /// Pounds Force Per Square Inch.
  static const int poundsForcePerSquareInch = 56;

  /// Centimeters Of Water.
  static const int centimetersOfWater = 57;

  /// Inches Of Water.
  static const int inchesOfWater = 58;

  /// Millimeters Of Mercury.
  static const int millimetersOfMercury = 59;

  /// Centimeters Of Mercury.
  static const int centimetersOfMercury = 60;

  /// Inches Of Mercury.
  static const int inchesOfMercury = 61;

  /// Degrees Celsius.
  static const int degreesCelsius = 62;

  /// Kelvin.
  static const int kelvin = 63;

  /// Degrees Fahrenheit.
  static const int degreesFahrenheit = 64;

  /// Degree Days Celsius.
  static const int degreeDaysCelsius = 65;

  /// Degree Days Fahrenheit.
  static const int degreeDaysFahrenheit = 66;

  /// Years.
  static const int years = 67;

  /// Months.
  static const int months = 68;

  /// Weeks.
  static const int weeks = 69;

  /// Days.
  static const int days = 70;

  /// Hours.
  static const int hours = 71;

  /// Minutes.
  static const int minutes = 72;

  /// Seconds.
  static const int seconds = 73;

  /// Meters Per Second.
  static const int metersPerSecond = 74;

  /// Kilometers Per Hour.
  static const int kilometersPerHour = 75;

  /// Feet Per Second.
  static const int feetPerSecond = 76;

  /// Feet Per Minute.
  static const int feetPerMinute = 77;

  /// Miles Per Hour.
  static const int milesPerHour = 78;

  /// Cubic Feet.
  static const int cubicFeet = 79;

  /// Cubic Meters.
  static const int cubicMeters = 80;

  /// Imperial Gallons.
  static const int imperialGallons = 81;

  /// Liters.
  static const int liters = 82;

  /// Us Gallons.
  static const int usGallons = 83;

  /// Cubic Feet Per Minute.
  static const int cubicFeetPerMinute = 84;

  /// Cubic Meters Per Second.
  static const int cubicMetersPerSecond = 85;

  /// Imperial Gallons Per Minute.
  static const int imperialGallonsPerMinute = 86;

  /// Liters Per Second.
  static const int litersPerSecond = 87;

  /// Liters Per Minute.
  static const int litersPerMinute = 88;

  /// Us Gallons Per Minute.
  static const int usGallonsPerMinute = 89;

  /// Degrees Angular.
  static const int degreesAngular = 90;

  /// Degrees Celsius Per Hour.
  static const int degreesCelsiusPerHour = 91;

  /// Degrees Celsius Per Minute.
  static const int degreesCelsiusPerMinute = 92;

  /// Degrees Fahrenheit Per Hour.
  static const int degreesFahrenheitPerHour = 93;

  /// Degrees Fahrenheit Per Minute.
  static const int degreesFahrenheitPerMinute = 94;

  /// No Units.
  static const int noUnits = 95;

  /// Parts Per Million.
  static const int partsPerMillion = 96;

  /// Parts Per Billion.
  static const int partsPerBillion = 97;

  /// Percent.
  static const int percent = 98;

  /// Percent Per Second.
  static const int percentPerSecond = 99;

  /// Per Minute.
  static const int perMinute = 100;

  /// Per Second.
  static const int perSecond = 101;

  /// Psi Per Degree Fahrenheit.
  static const int psiPerDegreeFahrenheit = 102;

  /// Radians.
  static const int radians = 103;

  /// Revolutions Per Minute.
  static const int revolutionsPerMinute = 104;

  /// Currency1.
  static const int currency1 = 105;

  /// Currency2.
  static const int currency2 = 106;

  /// Currency3.
  static const int currency3 = 107;

  /// Currency4.
  static const int currency4 = 108;

  /// Currency5.
  static const int currency5 = 109;

  /// Currency6.
  static const int currency6 = 110;

  /// Currency7.
  static const int currency7 = 111;

  /// Currency8.
  static const int currency8 = 112;

  /// Currency9.
  static const int currency9 = 113;

  /// Currency10.
  static const int currency10 = 114;

  /// Square Inches.
  static const int squareInches = 115;

  /// Square Centimeters.
  static const int squareCentimeters = 116;

  /// BTUs Per Pound.
  static const int btusPerPound = 117;

  /// Centimeters.
  static const int centimeters = 118;

  /// Pounds Mass Per Second.
  static const int poundsMassPerSecond = 119;

  /// Delta Degrees Fahrenheit.
  static const int deltaDegreesFahrenheit = 120;

  /// Delta Kelvin.
  static const int deltaKelvin = 121;

  /// Kilohms.
  static const int kilohms = 122;

  /// Megohms.
  static const int megohms = 123;

  /// Millivolts.
  static const int millivolts = 124;

  /// Kilojoules Per Kilogram.
  static const int kilojoulesPerKilogram = 125;

  /// Megajoules.
  static const int megajoules = 126;

  /// Joules Per Degree Kelvin.
  static const int joulesPerDegreeKelvin = 127;

  /// Joules Per Kilogram Degree Kelvin.
  static const int joulesPerKilogramDegreeKelvin = 128;

  /// Kilohertz.
  static const int kilohertz = 129;

  /// Megahertz.
  static const int megahertz = 130;

  /// Per Hour.
  static const int perHour = 131;

  /// Milliwatts.
  static const int milliwatts = 132;

  /// Hectopascals.
  static const int hectopascals = 133;

  /// Millibars.
  static const int millibars = 134;

  /// Cubic Meters Per Hour.
  static const int cubicMetersPerHour = 135;

  /// Liters Per Hour.
  static const int litersPerHour = 136;

  /// Kw Hours Per Square Meter.
  static const int kwHoursPerSquareMeter = 137;

  /// Kw Hours Per Square Foot.
  static const int kwHoursPerSquareFoot = 138;

  /// Megajoules Per Square Meter.
  static const int megajoulesPerSquareMeter = 139;

  /// Megajoules Per Square Foot.
  static const int megajoulesPerSquareFoot = 140;

  /// Watts Per Square Meter Degree Kelvin.
  static const int wattsPerSquareMeterDegreeKelvin = 141;

  /// Cubic Feet Per Second.
  static const int cubicFeetPerSecond = 142;

  /// Percent Obscuration Per Foot.
  static const int percentObscurationPerFoot = 143;

  /// Percent Obscuration Per Meter.
  static const int percentObscurationPerMeter = 144;

  /// Milliohms.
  static const int milliohms = 145;

  /// Megawatt Hours.
  static const int megawattHours = 146;

  /// Kilo BTUs.
  static const int kiloBtus = 147;

  /// Mega BTUs.
  static const int megaBtus = 148;

  /// Kilojoules Per Kilogram Dry Air.
  static const int kilojoulesPerKilogramDryAir = 149;

  /// Megajoules Per Kilogram Dry Air.
  static const int megajoulesPerKilogramDryAir = 150;

  /// Kilojoules Per Degree Kelvin.
  static const int kilojoulesPerDegreeKelvin = 151;

  /// Megajoules Per Degree Kelvin.
  static const int megajoulesPerDegreeKelvin = 152;

  /// Newton.
  static const int newton = 153;

  /// Grams Per Second.
  static const int gramsPerSecond = 154;

  /// Grams Per Minute.
  static const int gramsPerMinute = 155;

  /// Tons Per Hour.
  static const int tonsPerHour = 156;

  /// Kilo BTUs Per Hour.
  static const int kiloBtusPerHour = 157;

  /// Hundredths Seconds.
  static const int hundredthsSeconds = 158;

  /// Milliseconds.
  static const int milliseconds = 159;

  /// Newton Meters.
  static const int newtonMeters = 160;

  /// Millimeters Per Second.
  static const int millimetersPerSecond = 161;

  /// Millimeters Per Minute.
  static const int millimetersPerMinute = 162;

  /// Meters Per Minute.
  static const int metersPerMinute = 163;

  /// Meters Per Hour.
  static const int metersPerHour = 164;

  /// Cubic Meters Per Minute.
  static const int cubicMetersPerMinute = 165;

  /// Meters Per Second Per Second.
  static const int metersPerSecondPerSecond = 166;

  /// Amperes Per Meter.
  static const int amperesPerMeter = 167;

  /// Amperes Per Square Meter.
  static const int amperesPerSquareMeter = 168;

  /// Ampere Square Meters.
  static const int ampereSquareMeters = 169;

  /// Farads.
  static const int farads = 170;

  /// Henrys.
  static const int henrys = 171;

  /// Ohm Meters.
  static const int ohmMeters = 172;

  /// Siemens.
  static const int siemens = 173;

  /// Siemens Per Meter.
  static const int siemensPerMeter = 174;

  /// Teslas.
  static const int teslas = 175;

  /// Volts Per Degree Kelvin.
  static const int voltsPerDegreeKelvin = 176;

  /// Volts Per Meter.
  static const int voltsPerMeter = 177;

  /// Webers.
  static const int webers = 178;

  /// Candelas.
  static const int candelas = 179;

  /// Candelas Per Square Meter.
  static const int candelasPerSquareMeter = 180;

  /// Kelvin Per Hour.
  static const int kelvinPerHour = 181;

  /// Kelvin Per Minute.
  static const int kelvinPerMinute = 182;

  /// Joule Seconds.
  static const int jouleSeconds = 183;

  /// Radians Per Second.
  static const int radiansPerSecond = 184;

  /// Square Meters Per Newton.
  static const int squareMetersPerNewton = 185;

  /// Kilograms Per Cubic Meter.
  static const int kilogramsPerCubicMeter = 186;

  /// Newton Seconds.
  static const int newtonSeconds = 187;

  /// Newtons Per Meter.
  static const int newtonsPerMeter = 188;

  /// Watts Per Meter Per Degree Kelvin.
  static const int wattsPerMeterPerDegreeKelvin = 189;

  /// Microsiemens.
  static const int microsiemens = 190;

  /// Cubic Feet Per Hour.
  static const int cubicFeetPerHour = 191;

  /// Us Gallons Per Hour.
  static const int usGallonsPerHour = 192;

  /// Kilometers.
  static const int kilometers = 193;

  /// Micrometers.
  static const int micrometers = 194;

  /// Grams.
  static const int grams = 195;

  /// Milligrams.
  static const int milligrams = 196;

  /// Milliliters.
  static const int milliliters = 197;

  /// Milliliters Per Second.
  static const int millilitersPerSecond = 198;

  /// Decibels.
  static const int decibels = 199;

  /// Decibels Millivolt.
  static const int decibelsMillivolt = 200;

  /// Decibels Volt.
  static const int decibelsVolt = 201;

  /// Millisiemens.
  static const int millisiemens = 202;

  /// Watt Reactive Hours.
  static const int wattReactiveHours = 203;

  /// Kilowatt Reactive Hours.
  static const int kilowattReactiveHours = 204;

  /// Megawatt Reactive Hours.
  static const int megawattReactiveHours = 205;

  /// Millimeters Of Water.
  static const int millimetersOfWater = 206;

  /// Per Mille.
  static const int perMille = 207;

  /// Grams Per Gram.
  static const int gramsPerGram = 208;

  /// Kilograms Per Kilogram.
  static const int kilogramsPerKilogram = 209;

  /// Grams Per Kilogram.
  static const int gramsPerKilogram = 210;

  /// Milligrams Per Gram.
  static const int milligramsPerGram = 211;

  /// Milligrams Per Kilogram.
  static const int milligramsPerKilogram = 212;

  /// Grams Per Milliliter.
  static const int gramsPerMilliliter = 213;

  /// Grams Per Liter.
  static const int gramsPerLiter = 214;

  /// Milligrams Per Liter.
  static const int milligramsPerLiter = 215;

  /// Micrograms Per Liter.
  static const int microgramsPerLiter = 216;

  /// Grams Per Cubic Meter.
  static const int gramsPerCubicMeter = 217;

  /// Milligrams Per Cubic Meter.
  static const int milligramsPerCubicMeter = 218;

  /// Micrograms Per Cubic Meter.
  static const int microgramsPerCubicMeter = 219;

  /// Nanograms Per Cubic Meter.
  static const int nanogramsPerCubicMeter = 220;

  /// Grams Per Cubic Centimeter.
  static const int gramsPerCubicCentimeter = 221;

  /// Becquerels.
  static const int becquerels = 222;

  /// Kilobecquerels.
  static const int kilobecquerels = 223;

  /// Megabecquerels.
  static const int megabecquerels = 224;

  /// Gray.
  static const int gray = 225;

  /// Milligray.
  static const int milligray = 226;

  /// Microgray.
  static const int microgray = 227;

  /// Sieverts.
  static const int sieverts = 228;

  /// Millisieverts.
  static const int millisieverts = 229;

  /// Microsieverts.
  static const int microsieverts = 230;

  /// Microsieverts Per Hour.
  static const int microsievertsPerHour = 231;

  /// Decibels A.
  static const int decibelsA = 232;

  /// Nephelometric Turbidity Unit.
  static const int nephelometricTurbidityUnit = 233;

  /// Ph.
  static const int ph = 234;

  /// Grams Per Square Meter.
  static const int gramsPerSquareMeter = 235;

  /// Minutes Per Degree Kelvin.
  static const int minutesPerDegreeKelvin = 236;

  /// Ohm Meter Squared Per Meter.
  static const int ohmMeterSquaredPerMeter = 237;

  /// Ampere Seconds.
  static const int ampereSeconds = 238;

  /// Volt Ampere Hours.
  static const int voltAmpereHours = 239;

  /// Kilovolt Ampere Hours.
  static const int kilovoltAmpereHours = 240;

  /// Megavolt Ampere Hours.
  static const int megavoltAmpereHours = 241;

  /// Volt Ampere Reactive Hours.
  static const int voltAmpereReactiveHours = 242;

  /// Kilovolt Ampere Reactive Hours.
  static const int kilovoltAmpereReactiveHours = 243;

  /// Megavolt Ampere Reactive Hours.
  static const int megavoltAmpereReactiveHours = 244;

  /// Volt Square Hours.
  static const int voltSquareHours = 245;

  /// Ampere Square Hours.
  static const int ampereSquareHours = 246;

  /// Joule Per Hours.
  static const int joulePerHours = 247;

  /// Cubic Feet Per Day.
  static const int cubicFeetPerDay = 248;

  /// Cubic Meters Per Day.
  static const int cubicMetersPerDay = 249;

  /// Watt Hours Per Cubic Meter.
  static const int wattHoursPerCubicMeter = 250;

  /// Joules Per Cubic Meter.
  static const int joulesPerCubicMeter = 251;

  /// Mole Percent.
  static const int molePercent = 252;

  /// Pascal Seconds.
  static const int pascalSeconds = 253;

  /// Million Standard Cubic Feet Per Minute.
  static const int millionStandardCubicFeetPerMinute = 254;

  /// Standard Cubic Feet Per Day.
  static const int standardCubicFeetPerDay = 47808;

  /// Million Standard Cubic Feet Per Day.
  static const int millionStandardCubicFeetPerDay = 47809;

  /// Thousand Cubic Feet Per Day.
  static const int thousandCubicFeetPerDay = 47810;

  /// Thousand Standard Cubic Feet Per Day.
  static const int thousandStandardCubicFeetPerDay = 47811;

  /// Pounds Mass Per Day.
  static const int poundsMassPerDay = 47812;

  /// Millirems.
  static const int millirems = 47814;

  /// Millirems Per Hour.
  static const int milliremsPerHour = 47815;

  /// Degrees Lovibond.
  static const int degreesLovibond = 47816;

  /// Alcohol By Volume.
  static const int alcoholByVolume = 47817;

  /// International Bittering Units.
  static const int internationalBitteringUnits = 47818;

  /// European Bitterness Units.
  static const int europeanBitternessUnits = 47819;

  /// Degrees Plato.
  static const int degreesPlato = 47820;

  /// Specific Gravity.
  static const int specificGravity = 47821;

  /// European Brewing Convention.
  static const int europeanBrewingConvention = 47822;

  /// Per Day.
  static const int perDay = 47823;

  /// Per Millisecond.
  static const int perMillisecond = 47824;

  /// Yards.
  static const int yards = 47825;

  /// Miles.
  static const int miles = 47826;

  /// Nautical Miles.
  static const int nauticalMiles = 47827;

  /// Nanograms.
  static const int nanograms = 47828;

  /// Micrograms.
  static const int micrograms = 47829;

  /// Metric Tonnes.
  static const int metricTonnes = 47830;

  /// Short Tons.
  static const int shortTons = 47831;

  /// Long Tons.
  static const int longTons = 47832;

  /// Grams Per Hour.
  static const int gramsPerHour = 47833;

  /// Grams Per Day.
  static const int gramsPerDay = 47834;

  /// Kilograms Per Day.
  static const int kilogramsPerDay = 47835;

  /// Short Tons Per Second.
  static const int shortTonsPerSecond = 47836;

  /// Short Tons Per Minute.
  static const int shortTonsPerMinute = 47837;

  /// Short Tons Per Hour.
  static const int shortTonsPerHour = 47838;

  /// Short Tons Per Day.
  static const int shortTonsPerDay = 47839;

  /// Metric Tonnes Per Second.
  static const int metricTonnesPerSecond = 47840;

  /// Metric Tonnes Per Minute.
  static const int metricTonnesPerMinute = 47841;

  /// Metric Tonnes Per Hour.
  static const int metricTonnesPerHour = 47842;

  /// Metric Tonnes Per Day.
  static const int metricTonnesPerDay = 47843;

  /// Long Tons Per Second.
  static const int longTonsPerSecond = 47844;

  /// Long Tons Per Minute.
  static const int longTonsPerMinute = 47845;

  /// Long Tons Per Hour.
  static const int longTonsPerHour = 47846;

  /// Long Tons Per Day.
  static const int longTonsPerDay = 47847;

  /// BTUs Per Second.
  static const int btusPerSecond = 47848;

  /// BTUs Per Minute.
  static const int btusPerMinute = 47849;

  /// BTUs Per Day.
  static const int btusPerDay = 47850;

  /// Kilo BTUs Per Second.
  static const int kiloBtusPerSecond = 47851;

  /// Kilo BTUs Per Minute.
  static const int kiloBtusPerMinute = 47852;

  /// Kilo BTUs Per Day.
  static const int kiloBtusPerDay = 47853;

  /// Mega BTUs Per Second.
  static const int megaBtusPerSecond = 47854;

  /// Mega BTUs Per Minute.
  static const int megaBtusPerMinute = 47855;

  /// Mega BTUs Per Hour.
  static const int megaBtusPerHour = 47856;

  /// Mega BTUs Per Day.
  static const int megaBtusPerDay = 47857;

  /// Joules Per Second.
  static const int joulesPerSecond = 47858;

  /// Joules Per Minute.
  static const int joulesPerMinute = 47859;

  /// Joules Per Day.
  static const int joulesPerDay = 47860;

  /// Kilojoules Per Second.
  static const int kilojoulesPerSecond = 47861;

  /// Kilojoules Per Minute.
  static const int kilojoulesPerMinute = 47862;

  /// Kilojoules Per Hour.
  static const int kilojoulesPerHour = 47863;

  /// Kilojoules Per Day.
  static const int kilojoulesPerDay = 47864;

  /// Megajoules Per Second.
  static const int megajoulesPerSecond = 47865;

  /// Megajoules Per Minute.
  static const int megajoulesPerMinute = 47866;

  /// Megajoules Per Hour.
  static const int megajoulesPerHour = 47867;

  /// Megajoules Per Day.
  static const int megajoulesPerDay = 47868;

  /// Degrees Celsius Per Day.
  static const int degreesCelsiusPerDay = 47869;

  /// Kelvin Per Day.
  static const int kelvinPerDay = 47870;

  /// Degrees Fahrenheit Per Day.
  static const int degreesFahrenheitPerDay = 47871;

  /// Delta Degrees Celsius.
  static const int deltaDegreesCelsius = 47872;

  /// Million Cubic Feet Per Minute.
  static const int millionCubicFeetPerMinute = 47873;

  /// Million Cubic Feet Per Day.
  static const int millionCubicFeetPerDay = 47874;

  /// Imperial Gallons Per Second.
  static const int imperialGallonsPerSecond = 47875;

  /// Imperial Gallons Per Hour.
  static const int imperialGallonsPerHour = 47876;

  /// Imperial Gallons Per Day.
  static const int imperialGallonsPerDay = 47877;

  /// Liters Per Day.
  static const int litersPerDay = 47878;

  /// Us Gallons Per Second.
  static const int usGallonsPerSecond = 47879;

  /// Us Gallons Per Day.
  static const int usGallonsPerDay = 47880;

  /// Percent Per Minute.
  static const int percentPerMinute = 47881;

  /// Percent Per Hour.
  static const int percentPerHour = 47882;

  /// Percent Per Day.
  static const int percentPerDay = 47883;

  /// Per Million.
  static const int perMillion = 47884;

  /// Per Billion.
  static const int perBillion = 47885;

  /// Micrograms Per Gram.
  static const int microgramsPerGram = 47886;

  /// Nanograms Per Gram.
  static const int nanogramsPerGram = 47887;

  /// Micrograms Per Kilogram.
  static const int microgramsPerKilogram = 47888;

  /// Nanograms Per Kilogram.
  static const int nanogramsPerKilogram = 47889;

  /// Milligrams Per Milliliter.
  static const int milligramsPerMilliliter = 47890;

  /// Micrograms Per Milliliter.
  static const int microgramsPerMilliliter = 47891;

  /// Nanograms Per Milliliter.
  static const int nanogramsPerMilliliter = 47892;

  /// Kilograms Per Liter.
  static const int kilogramsPerLiter = 47893;

  /// Nanograms Per Liter.
  static const int nanogramsPerLiter = 47894;

  /// Milligrams Per Cubic Centimeter.
  static const int milligramsPerCubicCentimeter = 47895;

  /// Micrograms Per Cubic Centimeter.
  static const int microgramsPerCubicCentimeter = 47896;

  /// Nanograms Per Cubic Centimeter.
  static const int nanogramsPerCubicCentimeter = 47897;

  /// BTU Per Hour Per Watt.
  static const int btuPerHourPerWatt = 47898;

  /// BTU Per Watt Hour Seasonal.
  static const int btuPerWattHourSeasonal = 47899;

  /// Coefficient Of Performance.
  static const int coefficientOfPerformance = 47900;

  /// Coefficient Of Performance Seasonal.
  static const int coefficientOfPerformanceSeasonal = 47901;

  /// Kilowatt Per Ton Refrigeration.
  static const int kilowattPerTonRefrigeration = 47902;

  /// Lumens Per Watt.
  static const int lumensPerWatt = 47903;

  /// Pound Force Feet.
  static const int poundForceFeet = 47904;

  /// Pound Force Inches.
  static const int poundForceInches = 47905;

  /// Ounce Force Inches.
  static const int ounceForceInches = 47906;

  /// Pounds Force Per Square Inch Absolute.
  static const int poundsForcePerSquareInchAbsolute = 47907;

  /// Pounds Force Per Square Inch Gauge.
  static const int poundsForcePerSquareInchGauge = 47908;

  /// Microsiemens Per Centimeter.
  static const int microsiemensPerCentimeter = 47909;

  /// Millisiemens Per Centimeter.
  static const int millisiemensPerCentimeter = 47910;

  /// Millisiemens Per Meter.
  static const int millisiemensPerMeter = 47911;

  /// Millions Of Us Gallons.
  static const int millionsOfUsGallons = 47912;

  /// Millions Of Imperial Gallons.
  static const int millionsOfImperialGallons = 47913;

  /// Milliliters Per Minute.
  static const int millilitersPerMinute = 47914;

  /// Mils Per Year.
  static const int milsPerYear = 47915;

  /// Millimeters Per Year.
  static const int millimetersPerYear = 47916;

  /// Pulses Per Minute.
  static const int pulsesPerMinute = 47917;

  /// Active Energy Pulse Value.
  static const int activeEnergyPulseValue = 47918;

  /// Reactive Energy Pulse Value.
  static const int reactiveEnergyPulseValue = 47919;

  /// Apparent Energy Pulse Value.
  static const int apparentEnergyPulseValue = 47920;

  /// Volt Squared Hour Pulse Value.
  static const int voltSquaredHourPulseValue = 47921;

  /// Ampere Squared Hour Pulse Value.
  static const int ampereSquaredHourPulseValue = 47922;

  /// Cubic Meter Pulse Value.
  static const int cubicMeterPulseValue = 47923;

  /// Gigawatts.
  static const int gigawatts = 47924;

  /// Gigajoules.
  static const int gigajoules = 47925;

  /// Terajoules.
  static const int terajoules = 47926;

  /// Gigawatt Hours.
  static const int gigawattHours = 47927;

  /// Gigawatt Reactive Hours.
  static const int gigawattReactiveHours = 47928;

  /// Bits Per Second.
  static const int bitsPerSecond = 47929;

  /// Kilobits Per Second.
  static const int kilobitsPerSecond = 47930;

  /// Megabits Per Second.
  static const int megabitsPerSecond = 47931;

  /// Gigabits Per Second.
  static const int gigabitsPerSecond = 47932;

  /// Bytes Per Second.
  static const int bytesPerSecond = 47933;

  /// Kilobytes Per Second.
  static const int kilobytesPerSecond = 47934;

  /// Megabytes Per Second.
  static const int megabytesPerSecond = 47935;

  /// Gigabytes Per Second.
  static const int gigabytesPerSecond = 47936;

  /// Volume1.
  static const int volume1 = 47937;

  /// Volume2.
  static const int volume2 = 47938;

  /// Volume3.
  static const int volume3 = 47939;

  /// Volume4.
  static const int volume4 = 47940;

  /// Volume5.
  static const int volume5 = 47941;

  /// Volume6.
  static const int volume6 = 47942;

  /// Volume7.
  static const int volume7 = 47943;

  /// Volume8.
  static const int volume8 = 47944;

  /// Volume9.
  static const int volume9 = 47945;

  /// Volume10.
  static const int volume10 = 47946;

  /// Volumetric Flow1.
  static const int volumetricFlow1 = 47947;

  /// Volumetric Flow2.
  static const int volumetricFlow2 = 47948;

  /// Volumetric Flow3.
  static const int volumetricFlow3 = 47949;

  /// Volumetric Flow4.
  static const int volumetricFlow4 = 47950;

  /// Volumetric Flow5.
  static const int volumetricFlow5 = 47951;

  /// Volumetric Flow6.
  static const int volumetricFlow6 = 47952;

  /// Volumetric Flow7.
  static const int volumetricFlow7 = 47953;

  /// Volumetric Flow8.
  static const int volumetricFlow8 = 47954;

  /// Volumetric Flow9.
  static const int volumetricFlow9 = 47955;

  /// Volumetric Flow10.
  static const int volumetricFlow10 = 47956;

  /// Site Unit1.
  static const int siteUnit1 = 47958;

  /// Site Unit2.
  static const int siteUnit2 = 47959;

  /// Site Unit3.
  static const int siteUnit3 = 47960;

  /// Site Unit4.
  static const int siteUnit4 = 47961;

  /// Site Unit5.
  static const int siteUnit5 = 47962;

  /// Site Unit6.
  static const int siteUnit6 = 47963;

  /// Site Unit7.
  static const int siteUnit7 = 47964;

  /// Site Unit8.
  static const int siteUnit8 = 47965;

  /// Site Unit9.
  static const int siteUnit9 = 47966;

  /// Site Unit10.
  static const int siteUnit10 = 47967;

  /// Particles Per Cubic Foot.
  static const int particlesPerCubicFoot = 47968;

  /// Particles Per Cubic Meter.
  static const int particlesPerCubicMeter = 47969;

  /// Picocuries Per Liter.
  static const int picocuriesPerLiter = 47970;

  /// Becquerels Per Cubic Meter.
  static const int becquerelsPerCubicMeter = 47971;

  /// Grains Of Water Per Pound Dry Air.
  static const int grainsOfWaterPerPoundDryAir = 47972;

  /// Degree Hours Celsius.
  static const int degreeHoursCelsius = 47973;

  /// Degree Hours Fahrenheit.
  static const int degreeHoursFahrenheit = 47974;

  /// Degree Minutes Celsius.
  static const int degreeMinutesCelsius = 47975;

  /// Degree Minutes Fahrenheit.
  static const int degreeMinutesFahrenheit = 47976;

  /// Degree Seconds Celsius.
  static const int degreeSecondsCelsius = 47977;

  /// Degree Seconds Fahrenheit.
  static const int degreeSecondsFahrenheit = 47978;

  /// Microseconds.
  static const int microseconds = 47979;

  /// Nanoseconds.
  static const int nanoseconds = 47980;

  /// Picoseconds.
  static const int picoseconds = 47981;

  static const Map<int, String> _labels = {
    squareMeters: 'Square Meters',
    squareFeet: 'Square Feet',
    milliamperes: 'Milliamperes',
    amperes: 'Amperes',
    ohms: 'Ohms',
    volts: 'Volts',
    kilovolts: 'Kilovolts',
    megavolts: 'Megavolts',
    voltAmperes: 'Volt Amperes',
    kilovoltAmperes: 'Kilovolt Amperes',
    megavoltAmperes: 'Megavolt Amperes',
    voltAmperesReactive: 'Volt Amperes Reactive',
    kilovoltAmperesReactive: 'Kilovolt Amperes Reactive',
    megavoltAmperesReactive: 'Megavolt Amperes Reactive',
    degreesPhase: 'Degrees Phase',
    powerFactor: 'Power Factor',
    joules: 'Joules',
    kilojoules: 'Kilojoules',
    wattHours: 'Watt Hours',
    kilowattHours: 'Kilowatt Hours',
    btus: 'BTUs',
    therms: 'Therms',
    tonHours: 'Ton Hours',
    joulesPerKilogramDryAir: 'Joules Per Kilogram Dry Air',
    btusPerPoundDryAir: 'BTUs Per Pound Dry Air',
    cyclesPerHour: 'Cycles Per Hour',
    cyclesPerMinute: 'Cycles Per Minute',
    hertz: 'Hertz',
    gramsOfWaterPerKilogramDryAir: 'Grams Of Water Per Kilogram Dry Air',
    percentRelativeHumidity: 'Percent Relative Humidity',
    millimeters: 'Millimeters',
    meters: 'Meters',
    inches: 'Inches',
    feet: 'Feet',
    wattsPerSquareFoot: 'Watts Per Square Foot',
    wattsPerSquareMeter: 'Watts Per Square Meter',
    lumens: 'Lumens',
    luxes: 'Luxes',
    footCandles: 'Foot Candles',
    kilograms: 'Kilograms',
    poundsMass: 'Pounds Mass',
    tons: 'Tons',
    kilogramsPerSecond: 'Kilograms Per Second',
    kilogramsPerMinute: 'Kilograms Per Minute',
    kilogramsPerHour: 'Kilograms Per Hour',
    poundsMassPerMinute: 'Pounds Mass Per Minute',
    poundsMassPerHour: 'Pounds Mass Per Hour',
    watts: 'Watts',
    kilowatts: 'Kilowatts',
    megawatts: 'Megawatts',
    btusPerHour: 'BTUs Per Hour',
    horsepower: 'Horsepower',
    tonsRefrigeration: 'Tons Refrigeration',
    pascals: 'Pascals',
    kilopascals: 'Kilopascals',
    bars: 'Bars',
    poundsForcePerSquareInch: 'Pounds Force Per Square Inch',
    centimetersOfWater: 'Centimeters Of Water',
    inchesOfWater: 'Inches Of Water',
    millimetersOfMercury: 'Millimeters Of Mercury',
    centimetersOfMercury: 'Centimeters Of Mercury',
    inchesOfMercury: 'Inches Of Mercury',
    degreesCelsius: 'Degrees Celsius',
    kelvin: 'Kelvin',
    degreesFahrenheit: 'Degrees Fahrenheit',
    degreeDaysCelsius: 'Degree Days Celsius',
    degreeDaysFahrenheit: 'Degree Days Fahrenheit',
    years: 'Years',
    months: 'Months',
    weeks: 'Weeks',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    metersPerSecond: 'Meters Per Second',
    kilometersPerHour: 'Kilometers Per Hour',
    feetPerSecond: 'Feet Per Second',
    feetPerMinute: 'Feet Per Minute',
    milesPerHour: 'Miles Per Hour',
    cubicFeet: 'Cubic Feet',
    cubicMeters: 'Cubic Meters',
    imperialGallons: 'Imperial Gallons',
    liters: 'Liters',
    usGallons: 'Us Gallons',
    cubicFeetPerMinute: 'Cubic Feet Per Minute',
    cubicMetersPerSecond: 'Cubic Meters Per Second',
    imperialGallonsPerMinute: 'Imperial Gallons Per Minute',
    litersPerSecond: 'Liters Per Second',
    litersPerMinute: 'Liters Per Minute',
    usGallonsPerMinute: 'Us Gallons Per Minute',
    degreesAngular: 'Degrees Angular',
    degreesCelsiusPerHour: 'Degrees Celsius Per Hour',
    degreesCelsiusPerMinute: 'Degrees Celsius Per Minute',
    degreesFahrenheitPerHour: 'Degrees Fahrenheit Per Hour',
    degreesFahrenheitPerMinute: 'Degrees Fahrenheit Per Minute',
    noUnits: 'No Units',
    partsPerMillion: 'Parts Per Million',
    partsPerBillion: 'Parts Per Billion',
    percent: 'Percent',
    percentPerSecond: 'Percent Per Second',
    perMinute: 'Per Minute',
    perSecond: 'Per Second',
    psiPerDegreeFahrenheit: 'Psi Per Degree Fahrenheit',
    radians: 'Radians',
    revolutionsPerMinute: 'Revolutions Per Minute',
    currency1: 'Currency1',
    currency2: 'Currency2',
    currency3: 'Currency3',
    currency4: 'Currency4',
    currency5: 'Currency5',
    currency6: 'Currency6',
    currency7: 'Currency7',
    currency8: 'Currency8',
    currency9: 'Currency9',
    currency10: 'Currency10',
    squareInches: 'Square Inches',
    squareCentimeters: 'Square Centimeters',
    btusPerPound: 'BTUs Per Pound',
    centimeters: 'Centimeters',
    poundsMassPerSecond: 'Pounds Mass Per Second',
    deltaDegreesFahrenheit: 'Delta Degrees Fahrenheit',
    deltaKelvin: 'Delta Kelvin',
    kilohms: 'Kilohms',
    megohms: 'Megohms',
    millivolts: 'Millivolts',
    kilojoulesPerKilogram: 'Kilojoules Per Kilogram',
    megajoules: 'Megajoules',
    joulesPerDegreeKelvin: 'Joules Per Degree Kelvin',
    joulesPerKilogramDegreeKelvin: 'Joules Per Kilogram Degree Kelvin',
    kilohertz: 'Kilohertz',
    megahertz: 'Megahertz',
    perHour: 'Per Hour',
    milliwatts: 'Milliwatts',
    hectopascals: 'Hectopascals',
    millibars: 'Millibars',
    cubicMetersPerHour: 'Cubic Meters Per Hour',
    litersPerHour: 'Liters Per Hour',
    kwHoursPerSquareMeter: 'Kw Hours Per Square Meter',
    kwHoursPerSquareFoot: 'Kw Hours Per Square Foot',
    megajoulesPerSquareMeter: 'Megajoules Per Square Meter',
    megajoulesPerSquareFoot: 'Megajoules Per Square Foot',
    wattsPerSquareMeterDegreeKelvin: 'Watts Per Square Meter Degree Kelvin',
    cubicFeetPerSecond: 'Cubic Feet Per Second',
    percentObscurationPerFoot: 'Percent Obscuration Per Foot',
    percentObscurationPerMeter: 'Percent Obscuration Per Meter',
    milliohms: 'Milliohms',
    megawattHours: 'Megawatt Hours',
    kiloBtus: 'Kilo BTUs',
    megaBtus: 'Mega BTUs',
    kilojoulesPerKilogramDryAir: 'Kilojoules Per Kilogram Dry Air',
    megajoulesPerKilogramDryAir: 'Megajoules Per Kilogram Dry Air',
    kilojoulesPerDegreeKelvin: 'Kilojoules Per Degree Kelvin',
    megajoulesPerDegreeKelvin: 'Megajoules Per Degree Kelvin',
    newton: 'Newton',
    gramsPerSecond: 'Grams Per Second',
    gramsPerMinute: 'Grams Per Minute',
    tonsPerHour: 'Tons Per Hour',
    kiloBtusPerHour: 'Kilo BTUs Per Hour',
    hundredthsSeconds: 'Hundredths Seconds',
    milliseconds: 'Milliseconds',
    newtonMeters: 'Newton Meters',
    millimetersPerSecond: 'Millimeters Per Second',
    millimetersPerMinute: 'Millimeters Per Minute',
    metersPerMinute: 'Meters Per Minute',
    metersPerHour: 'Meters Per Hour',
    cubicMetersPerMinute: 'Cubic Meters Per Minute',
    metersPerSecondPerSecond: 'Meters Per Second Per Second',
    amperesPerMeter: 'Amperes Per Meter',
    amperesPerSquareMeter: 'Amperes Per Square Meter',
    ampereSquareMeters: 'Ampere Square Meters',
    farads: 'Farads',
    henrys: 'Henrys',
    ohmMeters: 'Ohm Meters',
    siemens: 'Siemens',
    siemensPerMeter: 'Siemens Per Meter',
    teslas: 'Teslas',
    voltsPerDegreeKelvin: 'Volts Per Degree Kelvin',
    voltsPerMeter: 'Volts Per Meter',
    webers: 'Webers',
    candelas: 'Candelas',
    candelasPerSquareMeter: 'Candelas Per Square Meter',
    kelvinPerHour: 'Kelvin Per Hour',
    kelvinPerMinute: 'Kelvin Per Minute',
    jouleSeconds: 'Joule Seconds',
    radiansPerSecond: 'Radians Per Second',
    squareMetersPerNewton: 'Square Meters Per Newton',
    kilogramsPerCubicMeter: 'Kilograms Per Cubic Meter',
    newtonSeconds: 'Newton Seconds',
    newtonsPerMeter: 'Newtons Per Meter',
    wattsPerMeterPerDegreeKelvin: 'Watts Per Meter Per Degree Kelvin',
    microsiemens: 'Microsiemens',
    cubicFeetPerHour: 'Cubic Feet Per Hour',
    usGallonsPerHour: 'Us Gallons Per Hour',
    kilometers: 'Kilometers',
    micrometers: 'Micrometers',
    grams: 'Grams',
    milligrams: 'Milligrams',
    milliliters: 'Milliliters',
    millilitersPerSecond: 'Milliliters Per Second',
    decibels: 'Decibels',
    decibelsMillivolt: 'Decibels Millivolt',
    decibelsVolt: 'Decibels Volt',
    millisiemens: 'Millisiemens',
    wattReactiveHours: 'Watt Reactive Hours',
    kilowattReactiveHours: 'Kilowatt Reactive Hours',
    megawattReactiveHours: 'Megawatt Reactive Hours',
    millimetersOfWater: 'Millimeters Of Water',
    perMille: 'Per Mille',
    gramsPerGram: 'Grams Per Gram',
    kilogramsPerKilogram: 'Kilograms Per Kilogram',
    gramsPerKilogram: 'Grams Per Kilogram',
    milligramsPerGram: 'Milligrams Per Gram',
    milligramsPerKilogram: 'Milligrams Per Kilogram',
    gramsPerMilliliter: 'Grams Per Milliliter',
    gramsPerLiter: 'Grams Per Liter',
    milligramsPerLiter: 'Milligrams Per Liter',
    microgramsPerLiter: 'Micrograms Per Liter',
    gramsPerCubicMeter: 'Grams Per Cubic Meter',
    milligramsPerCubicMeter: 'Milligrams Per Cubic Meter',
    microgramsPerCubicMeter: 'Micrograms Per Cubic Meter',
    nanogramsPerCubicMeter: 'Nanograms Per Cubic Meter',
    gramsPerCubicCentimeter: 'Grams Per Cubic Centimeter',
    becquerels: 'Becquerels',
    kilobecquerels: 'Kilobecquerels',
    megabecquerels: 'Megabecquerels',
    gray: 'Gray',
    milligray: 'Milligray',
    microgray: 'Microgray',
    sieverts: 'Sieverts',
    millisieverts: 'Millisieverts',
    microsieverts: 'Microsieverts',
    microsievertsPerHour: 'Microsieverts Per Hour',
    decibelsA: 'Decibels A',
    nephelometricTurbidityUnit: 'Nephelometric Turbidity Unit',
    ph: 'Ph',
    gramsPerSquareMeter: 'Grams Per Square Meter',
    minutesPerDegreeKelvin: 'Minutes Per Degree Kelvin',
    ohmMeterSquaredPerMeter: 'Ohm Meter Squared Per Meter',
    ampereSeconds: 'Ampere Seconds',
    voltAmpereHours: 'Volt Ampere Hours',
    kilovoltAmpereHours: 'Kilovolt Ampere Hours',
    megavoltAmpereHours: 'Megavolt Ampere Hours',
    voltAmpereReactiveHours: 'Volt Ampere Reactive Hours',
    kilovoltAmpereReactiveHours: 'Kilovolt Ampere Reactive Hours',
    megavoltAmpereReactiveHours: 'Megavolt Ampere Reactive Hours',
    voltSquareHours: 'Volt Square Hours',
    ampereSquareHours: 'Ampere Square Hours',
    joulePerHours: 'Joule Per Hours',
    cubicFeetPerDay: 'Cubic Feet Per Day',
    cubicMetersPerDay: 'Cubic Meters Per Day',
    wattHoursPerCubicMeter: 'Watt Hours Per Cubic Meter',
    joulesPerCubicMeter: 'Joules Per Cubic Meter',
    molePercent: 'Mole Percent',
    pascalSeconds: 'Pascal Seconds',
    millionStandardCubicFeetPerMinute: 'Million Standard Cubic Feet Per Minute',
    standardCubicFeetPerDay: 'Standard Cubic Feet Per Day',
    millionStandardCubicFeetPerDay: 'Million Standard Cubic Feet Per Day',
    thousandCubicFeetPerDay: 'Thousand Cubic Feet Per Day',
    thousandStandardCubicFeetPerDay: 'Thousand Standard Cubic Feet Per Day',
    poundsMassPerDay: 'Pounds Mass Per Day',
    millirems: 'Millirems',
    milliremsPerHour: 'Millirems Per Hour',
    degreesLovibond: 'Degrees Lovibond',
    alcoholByVolume: 'Alcohol By Volume',
    internationalBitteringUnits: 'International Bittering Units',
    europeanBitternessUnits: 'European Bitterness Units',
    degreesPlato: 'Degrees Plato',
    specificGravity: 'Specific Gravity',
    europeanBrewingConvention: 'European Brewing Convention',
    perDay: 'Per Day',
    perMillisecond: 'Per Millisecond',
    yards: 'Yards',
    miles: 'Miles',
    nauticalMiles: 'Nautical Miles',
    nanograms: 'Nanograms',
    micrograms: 'Micrograms',
    metricTonnes: 'Metric Tonnes',
    shortTons: 'Short Tons',
    longTons: 'Long Tons',
    gramsPerHour: 'Grams Per Hour',
    gramsPerDay: 'Grams Per Day',
    kilogramsPerDay: 'Kilograms Per Day',
    shortTonsPerSecond: 'Short Tons Per Second',
    shortTonsPerMinute: 'Short Tons Per Minute',
    shortTonsPerHour: 'Short Tons Per Hour',
    shortTonsPerDay: 'Short Tons Per Day',
    metricTonnesPerSecond: 'Metric Tonnes Per Second',
    metricTonnesPerMinute: 'Metric Tonnes Per Minute',
    metricTonnesPerHour: 'Metric Tonnes Per Hour',
    metricTonnesPerDay: 'Metric Tonnes Per Day',
    longTonsPerSecond: 'Long Tons Per Second',
    longTonsPerMinute: 'Long Tons Per Minute',
    longTonsPerHour: 'Long Tons Per Hour',
    longTonsPerDay: 'Long Tons Per Day',
    btusPerSecond: 'BTUs Per Second',
    btusPerMinute: 'BTUs Per Minute',
    btusPerDay: 'BTUs Per Day',
    kiloBtusPerSecond: 'Kilo BTUs Per Second',
    kiloBtusPerMinute: 'Kilo BTUs Per Minute',
    kiloBtusPerDay: 'Kilo BTUs Per Day',
    megaBtusPerSecond: 'Mega BTUs Per Second',
    megaBtusPerMinute: 'Mega BTUs Per Minute',
    megaBtusPerHour: 'Mega BTUs Per Hour',
    megaBtusPerDay: 'Mega BTUs Per Day',
    joulesPerSecond: 'Joules Per Second',
    joulesPerMinute: 'Joules Per Minute',
    joulesPerDay: 'Joules Per Day',
    kilojoulesPerSecond: 'Kilojoules Per Second',
    kilojoulesPerMinute: 'Kilojoules Per Minute',
    kilojoulesPerHour: 'Kilojoules Per Hour',
    kilojoulesPerDay: 'Kilojoules Per Day',
    megajoulesPerSecond: 'Megajoules Per Second',
    megajoulesPerMinute: 'Megajoules Per Minute',
    megajoulesPerHour: 'Megajoules Per Hour',
    megajoulesPerDay: 'Megajoules Per Day',
    degreesCelsiusPerDay: 'Degrees Celsius Per Day',
    kelvinPerDay: 'Kelvin Per Day',
    degreesFahrenheitPerDay: 'Degrees Fahrenheit Per Day',
    deltaDegreesCelsius: 'Delta Degrees Celsius',
    millionCubicFeetPerMinute: 'Million Cubic Feet Per Minute',
    millionCubicFeetPerDay: 'Million Cubic Feet Per Day',
    imperialGallonsPerSecond: 'Imperial Gallons Per Second',
    imperialGallonsPerHour: 'Imperial Gallons Per Hour',
    imperialGallonsPerDay: 'Imperial Gallons Per Day',
    litersPerDay: 'Liters Per Day',
    usGallonsPerSecond: 'Us Gallons Per Second',
    usGallonsPerDay: 'Us Gallons Per Day',
    percentPerMinute: 'Percent Per Minute',
    percentPerHour: 'Percent Per Hour',
    percentPerDay: 'Percent Per Day',
    perMillion: 'Per Million',
    perBillion: 'Per Billion',
    microgramsPerGram: 'Micrograms Per Gram',
    nanogramsPerGram: 'Nanograms Per Gram',
    microgramsPerKilogram: 'Micrograms Per Kilogram',
    nanogramsPerKilogram: 'Nanograms Per Kilogram',
    milligramsPerMilliliter: 'Milligrams Per Milliliter',
    microgramsPerMilliliter: 'Micrograms Per Milliliter',
    nanogramsPerMilliliter: 'Nanograms Per Milliliter',
    kilogramsPerLiter: 'Kilograms Per Liter',
    nanogramsPerLiter: 'Nanograms Per Liter',
    milligramsPerCubicCentimeter: 'Milligrams Per Cubic Centimeter',
    microgramsPerCubicCentimeter: 'Micrograms Per Cubic Centimeter',
    nanogramsPerCubicCentimeter: 'Nanograms Per Cubic Centimeter',
    btuPerHourPerWatt: 'BTU Per Hour Per Watt',
    btuPerWattHourSeasonal: 'BTU Per Watt Hour Seasonal',
    coefficientOfPerformance: 'Coefficient Of Performance',
    coefficientOfPerformanceSeasonal: 'Coefficient Of Performance Seasonal',
    kilowattPerTonRefrigeration: 'Kilowatt Per Ton Refrigeration',
    lumensPerWatt: 'Lumens Per Watt',
    poundForceFeet: 'Pound Force Feet',
    poundForceInches: 'Pound Force Inches',
    ounceForceInches: 'Ounce Force Inches',
    poundsForcePerSquareInchAbsolute: 'Pounds Force Per Square Inch Absolute',
    poundsForcePerSquareInchGauge: 'Pounds Force Per Square Inch Gauge',
    microsiemensPerCentimeter: 'Microsiemens Per Centimeter',
    millisiemensPerCentimeter: 'Millisiemens Per Centimeter',
    millisiemensPerMeter: 'Millisiemens Per Meter',
    millionsOfUsGallons: 'Millions Of Us Gallons',
    millionsOfImperialGallons: 'Millions Of Imperial Gallons',
    millilitersPerMinute: 'Milliliters Per Minute',
    milsPerYear: 'Mils Per Year',
    millimetersPerYear: 'Millimeters Per Year',
    pulsesPerMinute: 'Pulses Per Minute',
    activeEnergyPulseValue: 'Active Energy Pulse Value',
    reactiveEnergyPulseValue: 'Reactive Energy Pulse Value',
    apparentEnergyPulseValue: 'Apparent Energy Pulse Value',
    voltSquaredHourPulseValue: 'Volt Squared Hour Pulse Value',
    ampereSquaredHourPulseValue: 'Ampere Squared Hour Pulse Value',
    cubicMeterPulseValue: 'Cubic Meter Pulse Value',
    gigawatts: 'Gigawatts',
    gigajoules: 'Gigajoules',
    terajoules: 'Terajoules',
    gigawattHours: 'Gigawatt Hours',
    gigawattReactiveHours: 'Gigawatt Reactive Hours',
    bitsPerSecond: 'Bits Per Second',
    kilobitsPerSecond: 'Kilobits Per Second',
    megabitsPerSecond: 'Megabits Per Second',
    gigabitsPerSecond: 'Gigabits Per Second',
    bytesPerSecond: 'Bytes Per Second',
    kilobytesPerSecond: 'Kilobytes Per Second',
    megabytesPerSecond: 'Megabytes Per Second',
    gigabytesPerSecond: 'Gigabytes Per Second',
    volume1: 'Volume1',
    volume2: 'Volume2',
    volume3: 'Volume3',
    volume4: 'Volume4',
    volume5: 'Volume5',
    volume6: 'Volume6',
    volume7: 'Volume7',
    volume8: 'Volume8',
    volume9: 'Volume9',
    volume10: 'Volume10',
    volumetricFlow1: 'Volumetric Flow1',
    volumetricFlow2: 'Volumetric Flow2',
    volumetricFlow3: 'Volumetric Flow3',
    volumetricFlow4: 'Volumetric Flow4',
    volumetricFlow5: 'Volumetric Flow5',
    volumetricFlow6: 'Volumetric Flow6',
    volumetricFlow7: 'Volumetric Flow7',
    volumetricFlow8: 'Volumetric Flow8',
    volumetricFlow9: 'Volumetric Flow9',
    volumetricFlow10: 'Volumetric Flow10',
    siteUnit1: 'Site Unit1',
    siteUnit2: 'Site Unit2',
    siteUnit3: 'Site Unit3',
    siteUnit4: 'Site Unit4',
    siteUnit5: 'Site Unit5',
    siteUnit6: 'Site Unit6',
    siteUnit7: 'Site Unit7',
    siteUnit8: 'Site Unit8',
    siteUnit9: 'Site Unit9',
    siteUnit10: 'Site Unit10',
    particlesPerCubicFoot: 'Particles Per Cubic Foot',
    particlesPerCubicMeter: 'Particles Per Cubic Meter',
    picocuriesPerLiter: 'Picocuries Per Liter',
    becquerelsPerCubicMeter: 'Becquerels Per Cubic Meter',
    grainsOfWaterPerPoundDryAir: 'Grains Of Water Per Pound Dry Air',
    degreeHoursCelsius: 'Degree Hours Celsius',
    degreeHoursFahrenheit: 'Degree Hours Fahrenheit',
    degreeMinutesCelsius: 'Degree Minutes Celsius',
    degreeMinutesFahrenheit: 'Degree Minutes Fahrenheit',
    degreeSecondsCelsius: 'Degree Seconds Celsius',
    degreeSecondsFahrenheit: 'Degree Seconds Fahrenheit',
    microseconds: 'Microseconds',
    nanoseconds: 'Nanoseconds',
    picoseconds: 'Picoseconds',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Units $value';
}
