// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet engineering units (BACnetEngineeringUnits).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetEngineeringUnits(value)`.
extension type const BacnetEngineeringUnits(int value) implements int {
  /// Square Meters.
  static const squareMeters = BacnetEngineeringUnits(0);

  /// Square Feet.
  static const squareFeet = BacnetEngineeringUnits(1);

  /// Milliamperes.
  static const milliamperes = BacnetEngineeringUnits(2);

  /// Amperes.
  static const amperes = BacnetEngineeringUnits(3);

  /// Ohms.
  static const ohms = BacnetEngineeringUnits(4);

  /// Volts.
  static const volts = BacnetEngineeringUnits(5);

  /// Kilovolts.
  static const kilovolts = BacnetEngineeringUnits(6);

  /// Megavolts.
  static const megavolts = BacnetEngineeringUnits(7);

  /// Volt Amperes.
  static const voltAmperes = BacnetEngineeringUnits(8);

  /// Kilovolt Amperes.
  static const kilovoltAmperes = BacnetEngineeringUnits(9);

  /// Megavolt Amperes.
  static const megavoltAmperes = BacnetEngineeringUnits(10);

  /// Volt Amperes Reactive.
  static const voltAmperesReactive = BacnetEngineeringUnits(11);

  /// Kilovolt Amperes Reactive.
  static const kilovoltAmperesReactive = BacnetEngineeringUnits(12);

  /// Megavolt Amperes Reactive.
  static const megavoltAmperesReactive = BacnetEngineeringUnits(13);

  /// Degrees Phase.
  static const degreesPhase = BacnetEngineeringUnits(14);

  /// Power Factor.
  static const powerFactor = BacnetEngineeringUnits(15);

  /// Joules.
  static const joules = BacnetEngineeringUnits(16);

  /// Kilojoules.
  static const kilojoules = BacnetEngineeringUnits(17);

  /// Watt Hours.
  static const wattHours = BacnetEngineeringUnits(18);

  /// Kilowatt Hours.
  static const kilowattHours = BacnetEngineeringUnits(19);

  /// BTUs.
  static const btus = BacnetEngineeringUnits(20);

  /// Therms.
  static const therms = BacnetEngineeringUnits(21);

  /// Ton Hours.
  static const tonHours = BacnetEngineeringUnits(22);

  /// Joules Per Kilogram Dry Air.
  static const joulesPerKilogramDryAir = BacnetEngineeringUnits(23);

  /// BTUs Per Pound Dry Air.
  static const btusPerPoundDryAir = BacnetEngineeringUnits(24);

  /// Cycles Per Hour.
  static const cyclesPerHour = BacnetEngineeringUnits(25);

  /// Cycles Per Minute.
  static const cyclesPerMinute = BacnetEngineeringUnits(26);

  /// Hertz.
  static const hertz = BacnetEngineeringUnits(27);

  /// Grams Of Water Per Kilogram Dry Air.
  static const gramsOfWaterPerKilogramDryAir = BacnetEngineeringUnits(28);

  /// Percent Relative Humidity.
  static const percentRelativeHumidity = BacnetEngineeringUnits(29);

  /// Millimeters.
  static const millimeters = BacnetEngineeringUnits(30);

  /// Meters.
  static const meters = BacnetEngineeringUnits(31);

  /// Inches.
  static const inches = BacnetEngineeringUnits(32);

  /// Feet.
  static const feet = BacnetEngineeringUnits(33);

  /// Watts Per Square Foot.
  static const wattsPerSquareFoot = BacnetEngineeringUnits(34);

  /// Watts Per Square Meter.
  static const wattsPerSquareMeter = BacnetEngineeringUnits(35);

  /// Lumens.
  static const lumens = BacnetEngineeringUnits(36);

  /// Luxes.
  static const luxes = BacnetEngineeringUnits(37);

  /// Foot Candles.
  static const footCandles = BacnetEngineeringUnits(38);

  /// Kilograms.
  static const kilograms = BacnetEngineeringUnits(39);

  /// Pounds Mass.
  static const poundsMass = BacnetEngineeringUnits(40);

  /// Tons.
  static const tons = BacnetEngineeringUnits(41);

  /// Kilograms Per Second.
  static const kilogramsPerSecond = BacnetEngineeringUnits(42);

  /// Kilograms Per Minute.
  static const kilogramsPerMinute = BacnetEngineeringUnits(43);

  /// Kilograms Per Hour.
  static const kilogramsPerHour = BacnetEngineeringUnits(44);

  /// Pounds Mass Per Minute.
  static const poundsMassPerMinute = BacnetEngineeringUnits(45);

  /// Pounds Mass Per Hour.
  static const poundsMassPerHour = BacnetEngineeringUnits(46);

  /// Watts.
  static const watts = BacnetEngineeringUnits(47);

  /// Kilowatts.
  static const kilowatts = BacnetEngineeringUnits(48);

  /// Megawatts.
  static const megawatts = BacnetEngineeringUnits(49);

  /// BTUs Per Hour.
  static const btusPerHour = BacnetEngineeringUnits(50);

  /// Horsepower.
  static const horsepower = BacnetEngineeringUnits(51);

  /// Tons Refrigeration.
  static const tonsRefrigeration = BacnetEngineeringUnits(52);

  /// Pascals.
  static const pascals = BacnetEngineeringUnits(53);

  /// Kilopascals.
  static const kilopascals = BacnetEngineeringUnits(54);

  /// Bars.
  static const bars = BacnetEngineeringUnits(55);

  /// Pounds Force Per Square Inch.
  static const poundsForcePerSquareInch = BacnetEngineeringUnits(56);

  /// Centimeters Of Water.
  static const centimetersOfWater = BacnetEngineeringUnits(57);

  /// Inches Of Water.
  static const inchesOfWater = BacnetEngineeringUnits(58);

  /// Millimeters Of Mercury.
  static const millimetersOfMercury = BacnetEngineeringUnits(59);

  /// Centimeters Of Mercury.
  static const centimetersOfMercury = BacnetEngineeringUnits(60);

  /// Inches Of Mercury.
  static const inchesOfMercury = BacnetEngineeringUnits(61);

  /// Degrees Celsius.
  static const degreesCelsius = BacnetEngineeringUnits(62);

  /// Kelvin.
  static const kelvin = BacnetEngineeringUnits(63);

  /// Degrees Fahrenheit.
  static const degreesFahrenheit = BacnetEngineeringUnits(64);

  /// Degree Days Celsius.
  static const degreeDaysCelsius = BacnetEngineeringUnits(65);

  /// Degree Days Fahrenheit.
  static const degreeDaysFahrenheit = BacnetEngineeringUnits(66);

  /// Years.
  static const years = BacnetEngineeringUnits(67);

  /// Months.
  static const months = BacnetEngineeringUnits(68);

  /// Weeks.
  static const weeks = BacnetEngineeringUnits(69);

  /// Days.
  static const days = BacnetEngineeringUnits(70);

  /// Hours.
  static const hours = BacnetEngineeringUnits(71);

  /// Minutes.
  static const minutes = BacnetEngineeringUnits(72);

  /// Seconds.
  static const seconds = BacnetEngineeringUnits(73);

  /// Meters Per Second.
  static const metersPerSecond = BacnetEngineeringUnits(74);

  /// Kilometers Per Hour.
  static const kilometersPerHour = BacnetEngineeringUnits(75);

  /// Feet Per Second.
  static const feetPerSecond = BacnetEngineeringUnits(76);

  /// Feet Per Minute.
  static const feetPerMinute = BacnetEngineeringUnits(77);

  /// Miles Per Hour.
  static const milesPerHour = BacnetEngineeringUnits(78);

  /// Cubic Feet.
  static const cubicFeet = BacnetEngineeringUnits(79);

  /// Cubic Meters.
  static const cubicMeters = BacnetEngineeringUnits(80);

  /// Imperial Gallons.
  static const imperialGallons = BacnetEngineeringUnits(81);

  /// Liters.
  static const liters = BacnetEngineeringUnits(82);

  /// Us Gallons.
  static const usGallons = BacnetEngineeringUnits(83);

  /// Cubic Feet Per Minute.
  static const cubicFeetPerMinute = BacnetEngineeringUnits(84);

  /// Cubic Meters Per Second.
  static const cubicMetersPerSecond = BacnetEngineeringUnits(85);

  /// Imperial Gallons Per Minute.
  static const imperialGallonsPerMinute = BacnetEngineeringUnits(86);

  /// Liters Per Second.
  static const litersPerSecond = BacnetEngineeringUnits(87);

  /// Liters Per Minute.
  static const litersPerMinute = BacnetEngineeringUnits(88);

  /// Us Gallons Per Minute.
  static const usGallonsPerMinute = BacnetEngineeringUnits(89);

  /// Degrees Angular.
  static const degreesAngular = BacnetEngineeringUnits(90);

  /// Degrees Celsius Per Hour.
  static const degreesCelsiusPerHour = BacnetEngineeringUnits(91);

  /// Degrees Celsius Per Minute.
  static const degreesCelsiusPerMinute = BacnetEngineeringUnits(92);

  /// Degrees Fahrenheit Per Hour.
  static const degreesFahrenheitPerHour = BacnetEngineeringUnits(93);

  /// Degrees Fahrenheit Per Minute.
  static const degreesFahrenheitPerMinute = BacnetEngineeringUnits(94);

  /// No Units.
  static const noUnits = BacnetEngineeringUnits(95);

  /// Parts Per Million.
  static const partsPerMillion = BacnetEngineeringUnits(96);

  /// Parts Per Billion.
  static const partsPerBillion = BacnetEngineeringUnits(97);

  /// Percent.
  static const percent = BacnetEngineeringUnits(98);

  /// Percent Per Second.
  static const percentPerSecond = BacnetEngineeringUnits(99);

  /// Per Minute.
  static const perMinute = BacnetEngineeringUnits(100);

  /// Per Second.
  static const perSecond = BacnetEngineeringUnits(101);

  /// Psi Per Degree Fahrenheit.
  static const psiPerDegreeFahrenheit = BacnetEngineeringUnits(102);

  /// Radians.
  static const radians = BacnetEngineeringUnits(103);

  /// Revolutions Per Minute.
  static const revolutionsPerMinute = BacnetEngineeringUnits(104);

  /// Currency1.
  static const currency1 = BacnetEngineeringUnits(105);

  /// Currency2.
  static const currency2 = BacnetEngineeringUnits(106);

  /// Currency3.
  static const currency3 = BacnetEngineeringUnits(107);

  /// Currency4.
  static const currency4 = BacnetEngineeringUnits(108);

  /// Currency5.
  static const currency5 = BacnetEngineeringUnits(109);

  /// Currency6.
  static const currency6 = BacnetEngineeringUnits(110);

  /// Currency7.
  static const currency7 = BacnetEngineeringUnits(111);

  /// Currency8.
  static const currency8 = BacnetEngineeringUnits(112);

  /// Currency9.
  static const currency9 = BacnetEngineeringUnits(113);

  /// Currency10.
  static const currency10 = BacnetEngineeringUnits(114);

  /// Square Inches.
  static const squareInches = BacnetEngineeringUnits(115);

  /// Square Centimeters.
  static const squareCentimeters = BacnetEngineeringUnits(116);

  /// BTUs Per Pound.
  static const btusPerPound = BacnetEngineeringUnits(117);

  /// Centimeters.
  static const centimeters = BacnetEngineeringUnits(118);

  /// Pounds Mass Per Second.
  static const poundsMassPerSecond = BacnetEngineeringUnits(119);

  /// Delta Degrees Fahrenheit.
  static const deltaDegreesFahrenheit = BacnetEngineeringUnits(120);

  /// Delta Kelvin.
  static const deltaKelvin = BacnetEngineeringUnits(121);

  /// Kilohms.
  static const kilohms = BacnetEngineeringUnits(122);

  /// Megohms.
  static const megohms = BacnetEngineeringUnits(123);

  /// Millivolts.
  static const millivolts = BacnetEngineeringUnits(124);

  /// Kilojoules Per Kilogram.
  static const kilojoulesPerKilogram = BacnetEngineeringUnits(125);

  /// Megajoules.
  static const megajoules = BacnetEngineeringUnits(126);

  /// Joules Per Degree Kelvin.
  static const joulesPerDegreeKelvin = BacnetEngineeringUnits(127);

  /// Joules Per Kilogram Degree Kelvin.
  static const joulesPerKilogramDegreeKelvin = BacnetEngineeringUnits(128);

  /// Kilohertz.
  static const kilohertz = BacnetEngineeringUnits(129);

  /// Megahertz.
  static const megahertz = BacnetEngineeringUnits(130);

  /// Per Hour.
  static const perHour = BacnetEngineeringUnits(131);

  /// Milliwatts.
  static const milliwatts = BacnetEngineeringUnits(132);

  /// Hectopascals.
  static const hectopascals = BacnetEngineeringUnits(133);

  /// Millibars.
  static const millibars = BacnetEngineeringUnits(134);

  /// Cubic Meters Per Hour.
  static const cubicMetersPerHour = BacnetEngineeringUnits(135);

  /// Liters Per Hour.
  static const litersPerHour = BacnetEngineeringUnits(136);

  /// Kw Hours Per Square Meter.
  static const kwHoursPerSquareMeter = BacnetEngineeringUnits(137);

  /// Kw Hours Per Square Foot.
  static const kwHoursPerSquareFoot = BacnetEngineeringUnits(138);

  /// Megajoules Per Square Meter.
  static const megajoulesPerSquareMeter = BacnetEngineeringUnits(139);

  /// Megajoules Per Square Foot.
  static const megajoulesPerSquareFoot = BacnetEngineeringUnits(140);

  /// Watts Per Square Meter Degree Kelvin.
  static const wattsPerSquareMeterDegreeKelvin = BacnetEngineeringUnits(141);

  /// Cubic Feet Per Second.
  static const cubicFeetPerSecond = BacnetEngineeringUnits(142);

  /// Percent Obscuration Per Foot.
  static const percentObscurationPerFoot = BacnetEngineeringUnits(143);

  /// Percent Obscuration Per Meter.
  static const percentObscurationPerMeter = BacnetEngineeringUnits(144);

  /// Milliohms.
  static const milliohms = BacnetEngineeringUnits(145);

  /// Megawatt Hours.
  static const megawattHours = BacnetEngineeringUnits(146);

  /// Kilo BTUs.
  static const kiloBtus = BacnetEngineeringUnits(147);

  /// Mega BTUs.
  static const megaBtus = BacnetEngineeringUnits(148);

  /// Kilojoules Per Kilogram Dry Air.
  static const kilojoulesPerKilogramDryAir = BacnetEngineeringUnits(149);

  /// Megajoules Per Kilogram Dry Air.
  static const megajoulesPerKilogramDryAir = BacnetEngineeringUnits(150);

  /// Kilojoules Per Degree Kelvin.
  static const kilojoulesPerDegreeKelvin = BacnetEngineeringUnits(151);

  /// Megajoules Per Degree Kelvin.
  static const megajoulesPerDegreeKelvin = BacnetEngineeringUnits(152);

  /// Newton.
  static const newton = BacnetEngineeringUnits(153);

  /// Grams Per Second.
  static const gramsPerSecond = BacnetEngineeringUnits(154);

  /// Grams Per Minute.
  static const gramsPerMinute = BacnetEngineeringUnits(155);

  /// Tons Per Hour.
  static const tonsPerHour = BacnetEngineeringUnits(156);

  /// Kilo BTUs Per Hour.
  static const kiloBtusPerHour = BacnetEngineeringUnits(157);

  /// Hundredths Seconds.
  static const hundredthsSeconds = BacnetEngineeringUnits(158);

  /// Milliseconds.
  static const milliseconds = BacnetEngineeringUnits(159);

  /// Newton Meters.
  static const newtonMeters = BacnetEngineeringUnits(160);

  /// Millimeters Per Second.
  static const millimetersPerSecond = BacnetEngineeringUnits(161);

  /// Millimeters Per Minute.
  static const millimetersPerMinute = BacnetEngineeringUnits(162);

  /// Meters Per Minute.
  static const metersPerMinute = BacnetEngineeringUnits(163);

  /// Meters Per Hour.
  static const metersPerHour = BacnetEngineeringUnits(164);

  /// Cubic Meters Per Minute.
  static const cubicMetersPerMinute = BacnetEngineeringUnits(165);

  /// Meters Per Second Per Second.
  static const metersPerSecondPerSecond = BacnetEngineeringUnits(166);

  /// Amperes Per Meter.
  static const amperesPerMeter = BacnetEngineeringUnits(167);

  /// Amperes Per Square Meter.
  static const amperesPerSquareMeter = BacnetEngineeringUnits(168);

  /// Ampere Square Meters.
  static const ampereSquareMeters = BacnetEngineeringUnits(169);

  /// Farads.
  static const farads = BacnetEngineeringUnits(170);

  /// Henrys.
  static const henrys = BacnetEngineeringUnits(171);

  /// Ohm Meters.
  static const ohmMeters = BacnetEngineeringUnits(172);

  /// Siemens.
  static const siemens = BacnetEngineeringUnits(173);

  /// Siemens Per Meter.
  static const siemensPerMeter = BacnetEngineeringUnits(174);

  /// Teslas.
  static const teslas = BacnetEngineeringUnits(175);

  /// Volts Per Degree Kelvin.
  static const voltsPerDegreeKelvin = BacnetEngineeringUnits(176);

  /// Volts Per Meter.
  static const voltsPerMeter = BacnetEngineeringUnits(177);

  /// Webers.
  static const webers = BacnetEngineeringUnits(178);

  /// Candelas.
  static const candelas = BacnetEngineeringUnits(179);

  /// Candelas Per Square Meter.
  static const candelasPerSquareMeter = BacnetEngineeringUnits(180);

  /// Kelvin Per Hour.
  static const kelvinPerHour = BacnetEngineeringUnits(181);

  /// Kelvin Per Minute.
  static const kelvinPerMinute = BacnetEngineeringUnits(182);

  /// Joule Seconds.
  static const jouleSeconds = BacnetEngineeringUnits(183);

  /// Radians Per Second.
  static const radiansPerSecond = BacnetEngineeringUnits(184);

  /// Square Meters Per Newton.
  static const squareMetersPerNewton = BacnetEngineeringUnits(185);

  /// Kilograms Per Cubic Meter.
  static const kilogramsPerCubicMeter = BacnetEngineeringUnits(186);

  /// Newton Seconds.
  static const newtonSeconds = BacnetEngineeringUnits(187);

  /// Newtons Per Meter.
  static const newtonsPerMeter = BacnetEngineeringUnits(188);

  /// Watts Per Meter Per Degree Kelvin.
  static const wattsPerMeterPerDegreeKelvin = BacnetEngineeringUnits(189);

  /// Microsiemens.
  static const microsiemens = BacnetEngineeringUnits(190);

  /// Cubic Feet Per Hour.
  static const cubicFeetPerHour = BacnetEngineeringUnits(191);

  /// Us Gallons Per Hour.
  static const usGallonsPerHour = BacnetEngineeringUnits(192);

  /// Kilometers.
  static const kilometers = BacnetEngineeringUnits(193);

  /// Micrometers.
  static const micrometers = BacnetEngineeringUnits(194);

  /// Grams.
  static const grams = BacnetEngineeringUnits(195);

  /// Milligrams.
  static const milligrams = BacnetEngineeringUnits(196);

  /// Milliliters.
  static const milliliters = BacnetEngineeringUnits(197);

  /// Milliliters Per Second.
  static const millilitersPerSecond = BacnetEngineeringUnits(198);

  /// Decibels.
  static const decibels = BacnetEngineeringUnits(199);

  /// Decibels Millivolt.
  static const decibelsMillivolt = BacnetEngineeringUnits(200);

  /// Decibels Volt.
  static const decibelsVolt = BacnetEngineeringUnits(201);

  /// Millisiemens.
  static const millisiemens = BacnetEngineeringUnits(202);

  /// Watt Reactive Hours.
  static const wattReactiveHours = BacnetEngineeringUnits(203);

  /// Kilowatt Reactive Hours.
  static const kilowattReactiveHours = BacnetEngineeringUnits(204);

  /// Megawatt Reactive Hours.
  static const megawattReactiveHours = BacnetEngineeringUnits(205);

  /// Millimeters Of Water.
  static const millimetersOfWater = BacnetEngineeringUnits(206);

  /// Per Mille.
  static const perMille = BacnetEngineeringUnits(207);

  /// Grams Per Gram.
  static const gramsPerGram = BacnetEngineeringUnits(208);

  /// Kilograms Per Kilogram.
  static const kilogramsPerKilogram = BacnetEngineeringUnits(209);

  /// Grams Per Kilogram.
  static const gramsPerKilogram = BacnetEngineeringUnits(210);

  /// Milligrams Per Gram.
  static const milligramsPerGram = BacnetEngineeringUnits(211);

  /// Milligrams Per Kilogram.
  static const milligramsPerKilogram = BacnetEngineeringUnits(212);

  /// Grams Per Milliliter.
  static const gramsPerMilliliter = BacnetEngineeringUnits(213);

  /// Grams Per Liter.
  static const gramsPerLiter = BacnetEngineeringUnits(214);

  /// Milligrams Per Liter.
  static const milligramsPerLiter = BacnetEngineeringUnits(215);

  /// Micrograms Per Liter.
  static const microgramsPerLiter = BacnetEngineeringUnits(216);

  /// Grams Per Cubic Meter.
  static const gramsPerCubicMeter = BacnetEngineeringUnits(217);

  /// Milligrams Per Cubic Meter.
  static const milligramsPerCubicMeter = BacnetEngineeringUnits(218);

  /// Micrograms Per Cubic Meter.
  static const microgramsPerCubicMeter = BacnetEngineeringUnits(219);

  /// Nanograms Per Cubic Meter.
  static const nanogramsPerCubicMeter = BacnetEngineeringUnits(220);

  /// Grams Per Cubic Centimeter.
  static const gramsPerCubicCentimeter = BacnetEngineeringUnits(221);

  /// Becquerels.
  static const becquerels = BacnetEngineeringUnits(222);

  /// Kilobecquerels.
  static const kilobecquerels = BacnetEngineeringUnits(223);

  /// Megabecquerels.
  static const megabecquerels = BacnetEngineeringUnits(224);

  /// Gray.
  static const gray = BacnetEngineeringUnits(225);

  /// Milligray.
  static const milligray = BacnetEngineeringUnits(226);

  /// Microgray.
  static const microgray = BacnetEngineeringUnits(227);

  /// Sieverts.
  static const sieverts = BacnetEngineeringUnits(228);

  /// Millisieverts.
  static const millisieverts = BacnetEngineeringUnits(229);

  /// Microsieverts.
  static const microsieverts = BacnetEngineeringUnits(230);

  /// Microsieverts Per Hour.
  static const microsievertsPerHour = BacnetEngineeringUnits(231);

  /// Decibels A.
  static const decibelsA = BacnetEngineeringUnits(232);

  /// Nephelometric Turbidity Unit.
  static const nephelometricTurbidityUnit = BacnetEngineeringUnits(233);

  /// Ph.
  static const ph = BacnetEngineeringUnits(234);

  /// Grams Per Square Meter.
  static const gramsPerSquareMeter = BacnetEngineeringUnits(235);

  /// Minutes Per Degree Kelvin.
  static const minutesPerDegreeKelvin = BacnetEngineeringUnits(236);

  /// Ohm Meter Squared Per Meter.
  static const ohmMeterSquaredPerMeter = BacnetEngineeringUnits(237);

  /// Ampere Seconds.
  static const ampereSeconds = BacnetEngineeringUnits(238);

  /// Volt Ampere Hours.
  static const voltAmpereHours = BacnetEngineeringUnits(239);

  /// Kilovolt Ampere Hours.
  static const kilovoltAmpereHours = BacnetEngineeringUnits(240);

  /// Megavolt Ampere Hours.
  static const megavoltAmpereHours = BacnetEngineeringUnits(241);

  /// Volt Ampere Reactive Hours.
  static const voltAmpereReactiveHours = BacnetEngineeringUnits(242);

  /// Kilovolt Ampere Reactive Hours.
  static const kilovoltAmpereReactiveHours = BacnetEngineeringUnits(243);

  /// Megavolt Ampere Reactive Hours.
  static const megavoltAmpereReactiveHours = BacnetEngineeringUnits(244);

  /// Volt Square Hours.
  static const voltSquareHours = BacnetEngineeringUnits(245);

  /// Ampere Square Hours.
  static const ampereSquareHours = BacnetEngineeringUnits(246);

  /// Joule Per Hours.
  static const joulePerHours = BacnetEngineeringUnits(247);

  /// Cubic Feet Per Day.
  static const cubicFeetPerDay = BacnetEngineeringUnits(248);

  /// Cubic Meters Per Day.
  static const cubicMetersPerDay = BacnetEngineeringUnits(249);

  /// Watt Hours Per Cubic Meter.
  static const wattHoursPerCubicMeter = BacnetEngineeringUnits(250);

  /// Joules Per Cubic Meter.
  static const joulesPerCubicMeter = BacnetEngineeringUnits(251);

  /// Mole Percent.
  static const molePercent = BacnetEngineeringUnits(252);

  /// Pascal Seconds.
  static const pascalSeconds = BacnetEngineeringUnits(253);

  /// Million Standard Cubic Feet Per Minute.
  static const millionStandardCubicFeetPerMinute = BacnetEngineeringUnits(254);

  /// Standard Cubic Feet Per Day.
  static const standardCubicFeetPerDay = BacnetEngineeringUnits(47808);

  /// Million Standard Cubic Feet Per Day.
  static const millionStandardCubicFeetPerDay = BacnetEngineeringUnits(47809);

  /// Thousand Cubic Feet Per Day.
  static const thousandCubicFeetPerDay = BacnetEngineeringUnits(47810);

  /// Thousand Standard Cubic Feet Per Day.
  static const thousandStandardCubicFeetPerDay = BacnetEngineeringUnits(47811);

  /// Pounds Mass Per Day.
  static const poundsMassPerDay = BacnetEngineeringUnits(47812);

  /// Millirems.
  static const millirems = BacnetEngineeringUnits(47814);

  /// Millirems Per Hour.
  static const milliremsPerHour = BacnetEngineeringUnits(47815);

  /// Degrees Lovibond.
  static const degreesLovibond = BacnetEngineeringUnits(47816);

  /// Alcohol By Volume.
  static const alcoholByVolume = BacnetEngineeringUnits(47817);

  /// International Bittering Units.
  static const internationalBitteringUnits = BacnetEngineeringUnits(47818);

  /// European Bitterness Units.
  static const europeanBitternessUnits = BacnetEngineeringUnits(47819);

  /// Degrees Plato.
  static const degreesPlato = BacnetEngineeringUnits(47820);

  /// Specific Gravity.
  static const specificGravity = BacnetEngineeringUnits(47821);

  /// European Brewing Convention.
  static const europeanBrewingConvention = BacnetEngineeringUnits(47822);

  /// Per Day.
  static const perDay = BacnetEngineeringUnits(47823);

  /// Per Millisecond.
  static const perMillisecond = BacnetEngineeringUnits(47824);

  /// Yards.
  static const yards = BacnetEngineeringUnits(47825);

  /// Miles.
  static const miles = BacnetEngineeringUnits(47826);

  /// Nautical Miles.
  static const nauticalMiles = BacnetEngineeringUnits(47827);

  /// Nanograms.
  static const nanograms = BacnetEngineeringUnits(47828);

  /// Micrograms.
  static const micrograms = BacnetEngineeringUnits(47829);

  /// Metric Tonnes.
  static const metricTonnes = BacnetEngineeringUnits(47830);

  /// Short Tons.
  static const shortTons = BacnetEngineeringUnits(47831);

  /// Long Tons.
  static const longTons = BacnetEngineeringUnits(47832);

  /// Grams Per Hour.
  static const gramsPerHour = BacnetEngineeringUnits(47833);

  /// Grams Per Day.
  static const gramsPerDay = BacnetEngineeringUnits(47834);

  /// Kilograms Per Day.
  static const kilogramsPerDay = BacnetEngineeringUnits(47835);

  /// Short Tons Per Second.
  static const shortTonsPerSecond = BacnetEngineeringUnits(47836);

  /// Short Tons Per Minute.
  static const shortTonsPerMinute = BacnetEngineeringUnits(47837);

  /// Short Tons Per Hour.
  static const shortTonsPerHour = BacnetEngineeringUnits(47838);

  /// Short Tons Per Day.
  static const shortTonsPerDay = BacnetEngineeringUnits(47839);

  /// Metric Tonnes Per Second.
  static const metricTonnesPerSecond = BacnetEngineeringUnits(47840);

  /// Metric Tonnes Per Minute.
  static const metricTonnesPerMinute = BacnetEngineeringUnits(47841);

  /// Metric Tonnes Per Hour.
  static const metricTonnesPerHour = BacnetEngineeringUnits(47842);

  /// Metric Tonnes Per Day.
  static const metricTonnesPerDay = BacnetEngineeringUnits(47843);

  /// Long Tons Per Second.
  static const longTonsPerSecond = BacnetEngineeringUnits(47844);

  /// Long Tons Per Minute.
  static const longTonsPerMinute = BacnetEngineeringUnits(47845);

  /// Long Tons Per Hour.
  static const longTonsPerHour = BacnetEngineeringUnits(47846);

  /// Long Tons Per Day.
  static const longTonsPerDay = BacnetEngineeringUnits(47847);

  /// BTUs Per Second.
  static const btusPerSecond = BacnetEngineeringUnits(47848);

  /// BTUs Per Minute.
  static const btusPerMinute = BacnetEngineeringUnits(47849);

  /// BTUs Per Day.
  static const btusPerDay = BacnetEngineeringUnits(47850);

  /// Kilo BTUs Per Second.
  static const kiloBtusPerSecond = BacnetEngineeringUnits(47851);

  /// Kilo BTUs Per Minute.
  static const kiloBtusPerMinute = BacnetEngineeringUnits(47852);

  /// Kilo BTUs Per Day.
  static const kiloBtusPerDay = BacnetEngineeringUnits(47853);

  /// Mega BTUs Per Second.
  static const megaBtusPerSecond = BacnetEngineeringUnits(47854);

  /// Mega BTUs Per Minute.
  static const megaBtusPerMinute = BacnetEngineeringUnits(47855);

  /// Mega BTUs Per Hour.
  static const megaBtusPerHour = BacnetEngineeringUnits(47856);

  /// Mega BTUs Per Day.
  static const megaBtusPerDay = BacnetEngineeringUnits(47857);

  /// Joules Per Second.
  static const joulesPerSecond = BacnetEngineeringUnits(47858);

  /// Joules Per Minute.
  static const joulesPerMinute = BacnetEngineeringUnits(47859);

  /// Joules Per Day.
  static const joulesPerDay = BacnetEngineeringUnits(47860);

  /// Kilojoules Per Second.
  static const kilojoulesPerSecond = BacnetEngineeringUnits(47861);

  /// Kilojoules Per Minute.
  static const kilojoulesPerMinute = BacnetEngineeringUnits(47862);

  /// Kilojoules Per Hour.
  static const kilojoulesPerHour = BacnetEngineeringUnits(47863);

  /// Kilojoules Per Day.
  static const kilojoulesPerDay = BacnetEngineeringUnits(47864);

  /// Megajoules Per Second.
  static const megajoulesPerSecond = BacnetEngineeringUnits(47865);

  /// Megajoules Per Minute.
  static const megajoulesPerMinute = BacnetEngineeringUnits(47866);

  /// Megajoules Per Hour.
  static const megajoulesPerHour = BacnetEngineeringUnits(47867);

  /// Megajoules Per Day.
  static const megajoulesPerDay = BacnetEngineeringUnits(47868);

  /// Degrees Celsius Per Day.
  static const degreesCelsiusPerDay = BacnetEngineeringUnits(47869);

  /// Kelvin Per Day.
  static const kelvinPerDay = BacnetEngineeringUnits(47870);

  /// Degrees Fahrenheit Per Day.
  static const degreesFahrenheitPerDay = BacnetEngineeringUnits(47871);

  /// Delta Degrees Celsius.
  static const deltaDegreesCelsius = BacnetEngineeringUnits(47872);

  /// Million Cubic Feet Per Minute.
  static const millionCubicFeetPerMinute = BacnetEngineeringUnits(47873);

  /// Million Cubic Feet Per Day.
  static const millionCubicFeetPerDay = BacnetEngineeringUnits(47874);

  /// Imperial Gallons Per Second.
  static const imperialGallonsPerSecond = BacnetEngineeringUnits(47875);

  /// Imperial Gallons Per Hour.
  static const imperialGallonsPerHour = BacnetEngineeringUnits(47876);

  /// Imperial Gallons Per Day.
  static const imperialGallonsPerDay = BacnetEngineeringUnits(47877);

  /// Liters Per Day.
  static const litersPerDay = BacnetEngineeringUnits(47878);

  /// Us Gallons Per Second.
  static const usGallonsPerSecond = BacnetEngineeringUnits(47879);

  /// Us Gallons Per Day.
  static const usGallonsPerDay = BacnetEngineeringUnits(47880);

  /// Percent Per Minute.
  static const percentPerMinute = BacnetEngineeringUnits(47881);

  /// Percent Per Hour.
  static const percentPerHour = BacnetEngineeringUnits(47882);

  /// Percent Per Day.
  static const percentPerDay = BacnetEngineeringUnits(47883);

  /// Per Million.
  static const perMillion = BacnetEngineeringUnits(47884);

  /// Per Billion.
  static const perBillion = BacnetEngineeringUnits(47885);

  /// Micrograms Per Gram.
  static const microgramsPerGram = BacnetEngineeringUnits(47886);

  /// Nanograms Per Gram.
  static const nanogramsPerGram = BacnetEngineeringUnits(47887);

  /// Micrograms Per Kilogram.
  static const microgramsPerKilogram = BacnetEngineeringUnits(47888);

  /// Nanograms Per Kilogram.
  static const nanogramsPerKilogram = BacnetEngineeringUnits(47889);

  /// Milligrams Per Milliliter.
  static const milligramsPerMilliliter = BacnetEngineeringUnits(47890);

  /// Micrograms Per Milliliter.
  static const microgramsPerMilliliter = BacnetEngineeringUnits(47891);

  /// Nanograms Per Milliliter.
  static const nanogramsPerMilliliter = BacnetEngineeringUnits(47892);

  /// Kilograms Per Liter.
  static const kilogramsPerLiter = BacnetEngineeringUnits(47893);

  /// Nanograms Per Liter.
  static const nanogramsPerLiter = BacnetEngineeringUnits(47894);

  /// Milligrams Per Cubic Centimeter.
  static const milligramsPerCubicCentimeter = BacnetEngineeringUnits(47895);

  /// Micrograms Per Cubic Centimeter.
  static const microgramsPerCubicCentimeter = BacnetEngineeringUnits(47896);

  /// Nanograms Per Cubic Centimeter.
  static const nanogramsPerCubicCentimeter = BacnetEngineeringUnits(47897);

  /// BTU Per Hour Per Watt.
  static const btuPerHourPerWatt = BacnetEngineeringUnits(47898);

  /// BTU Per Watt Hour Seasonal.
  static const btuPerWattHourSeasonal = BacnetEngineeringUnits(47899);

  /// Coefficient Of Performance.
  static const coefficientOfPerformance = BacnetEngineeringUnits(47900);

  /// Coefficient Of Performance Seasonal.
  static const coefficientOfPerformanceSeasonal = BacnetEngineeringUnits(47901);

  /// Kilowatt Per Ton Refrigeration.
  static const kilowattPerTonRefrigeration = BacnetEngineeringUnits(47902);

  /// Lumens Per Watt.
  static const lumensPerWatt = BacnetEngineeringUnits(47903);

  /// Pound Force Feet.
  static const poundForceFeet = BacnetEngineeringUnits(47904);

  /// Pound Force Inches.
  static const poundForceInches = BacnetEngineeringUnits(47905);

  /// Ounce Force Inches.
  static const ounceForceInches = BacnetEngineeringUnits(47906);

  /// Pounds Force Per Square Inch Absolute.
  static const poundsForcePerSquareInchAbsolute = BacnetEngineeringUnits(47907);

  /// Pounds Force Per Square Inch Gauge.
  static const poundsForcePerSquareInchGauge = BacnetEngineeringUnits(47908);

  /// Microsiemens Per Centimeter.
  static const microsiemensPerCentimeter = BacnetEngineeringUnits(47909);

  /// Millisiemens Per Centimeter.
  static const millisiemensPerCentimeter = BacnetEngineeringUnits(47910);

  /// Millisiemens Per Meter.
  static const millisiemensPerMeter = BacnetEngineeringUnits(47911);

  /// Millions Of Us Gallons.
  static const millionsOfUsGallons = BacnetEngineeringUnits(47912);

  /// Millions Of Imperial Gallons.
  static const millionsOfImperialGallons = BacnetEngineeringUnits(47913);

  /// Milliliters Per Minute.
  static const millilitersPerMinute = BacnetEngineeringUnits(47914);

  /// Mils Per Year.
  static const milsPerYear = BacnetEngineeringUnits(47915);

  /// Millimeters Per Year.
  static const millimetersPerYear = BacnetEngineeringUnits(47916);

  /// Pulses Per Minute.
  static const pulsesPerMinute = BacnetEngineeringUnits(47917);

  /// Active Energy Pulse Value.
  static const activeEnergyPulseValue = BacnetEngineeringUnits(47918);

  /// Reactive Energy Pulse Value.
  static const reactiveEnergyPulseValue = BacnetEngineeringUnits(47919);

  /// Apparent Energy Pulse Value.
  static const apparentEnergyPulseValue = BacnetEngineeringUnits(47920);

  /// Volt Squared Hour Pulse Value.
  static const voltSquaredHourPulseValue = BacnetEngineeringUnits(47921);

  /// Ampere Squared Hour Pulse Value.
  static const ampereSquaredHourPulseValue = BacnetEngineeringUnits(47922);

  /// Cubic Meter Pulse Value.
  static const cubicMeterPulseValue = BacnetEngineeringUnits(47923);

  /// Gigawatts.
  static const gigawatts = BacnetEngineeringUnits(47924);

  /// Gigajoules.
  static const gigajoules = BacnetEngineeringUnits(47925);

  /// Terajoules.
  static const terajoules = BacnetEngineeringUnits(47926);

  /// Gigawatt Hours.
  static const gigawattHours = BacnetEngineeringUnits(47927);

  /// Gigawatt Reactive Hours.
  static const gigawattReactiveHours = BacnetEngineeringUnits(47928);

  /// Bits Per Second.
  static const bitsPerSecond = BacnetEngineeringUnits(47929);

  /// Kilobits Per Second.
  static const kilobitsPerSecond = BacnetEngineeringUnits(47930);

  /// Megabits Per Second.
  static const megabitsPerSecond = BacnetEngineeringUnits(47931);

  /// Gigabits Per Second.
  static const gigabitsPerSecond = BacnetEngineeringUnits(47932);

  /// Bytes Per Second.
  static const bytesPerSecond = BacnetEngineeringUnits(47933);

  /// Kilobytes Per Second.
  static const kilobytesPerSecond = BacnetEngineeringUnits(47934);

  /// Megabytes Per Second.
  static const megabytesPerSecond = BacnetEngineeringUnits(47935);

  /// Gigabytes Per Second.
  static const gigabytesPerSecond = BacnetEngineeringUnits(47936);

  /// Volume1.
  static const volume1 = BacnetEngineeringUnits(47937);

  /// Volume2.
  static const volume2 = BacnetEngineeringUnits(47938);

  /// Volume3.
  static const volume3 = BacnetEngineeringUnits(47939);

  /// Volume4.
  static const volume4 = BacnetEngineeringUnits(47940);

  /// Volume5.
  static const volume5 = BacnetEngineeringUnits(47941);

  /// Volume6.
  static const volume6 = BacnetEngineeringUnits(47942);

  /// Volume7.
  static const volume7 = BacnetEngineeringUnits(47943);

  /// Volume8.
  static const volume8 = BacnetEngineeringUnits(47944);

  /// Volume9.
  static const volume9 = BacnetEngineeringUnits(47945);

  /// Volume10.
  static const volume10 = BacnetEngineeringUnits(47946);

  /// Volumetric Flow1.
  static const volumetricFlow1 = BacnetEngineeringUnits(47947);

  /// Volumetric Flow2.
  static const volumetricFlow2 = BacnetEngineeringUnits(47948);

  /// Volumetric Flow3.
  static const volumetricFlow3 = BacnetEngineeringUnits(47949);

  /// Volumetric Flow4.
  static const volumetricFlow4 = BacnetEngineeringUnits(47950);

  /// Volumetric Flow5.
  static const volumetricFlow5 = BacnetEngineeringUnits(47951);

  /// Volumetric Flow6.
  static const volumetricFlow6 = BacnetEngineeringUnits(47952);

  /// Volumetric Flow7.
  static const volumetricFlow7 = BacnetEngineeringUnits(47953);

  /// Volumetric Flow8.
  static const volumetricFlow8 = BacnetEngineeringUnits(47954);

  /// Volumetric Flow9.
  static const volumetricFlow9 = BacnetEngineeringUnits(47955);

  /// Volumetric Flow10.
  static const volumetricFlow10 = BacnetEngineeringUnits(47956);

  /// Site Unit1.
  static const siteUnit1 = BacnetEngineeringUnits(47958);

  /// Site Unit2.
  static const siteUnit2 = BacnetEngineeringUnits(47959);

  /// Site Unit3.
  static const siteUnit3 = BacnetEngineeringUnits(47960);

  /// Site Unit4.
  static const siteUnit4 = BacnetEngineeringUnits(47961);

  /// Site Unit5.
  static const siteUnit5 = BacnetEngineeringUnits(47962);

  /// Site Unit6.
  static const siteUnit6 = BacnetEngineeringUnits(47963);

  /// Site Unit7.
  static const siteUnit7 = BacnetEngineeringUnits(47964);

  /// Site Unit8.
  static const siteUnit8 = BacnetEngineeringUnits(47965);

  /// Site Unit9.
  static const siteUnit9 = BacnetEngineeringUnits(47966);

  /// Site Unit10.
  static const siteUnit10 = BacnetEngineeringUnits(47967);

  /// Particles Per Cubic Foot.
  static const particlesPerCubicFoot = BacnetEngineeringUnits(47968);

  /// Particles Per Cubic Meter.
  static const particlesPerCubicMeter = BacnetEngineeringUnits(47969);

  /// Picocuries Per Liter.
  static const picocuriesPerLiter = BacnetEngineeringUnits(47970);

  /// Becquerels Per Cubic Meter.
  static const becquerelsPerCubicMeter = BacnetEngineeringUnits(47971);

  /// Grains Of Water Per Pound Dry Air.
  static const grainsOfWaterPerPoundDryAir = BacnetEngineeringUnits(47972);

  /// Degree Hours Celsius.
  static const degreeHoursCelsius = BacnetEngineeringUnits(47973);

  /// Degree Hours Fahrenheit.
  static const degreeHoursFahrenheit = BacnetEngineeringUnits(47974);

  /// Degree Minutes Celsius.
  static const degreeMinutesCelsius = BacnetEngineeringUnits(47975);

  /// Degree Minutes Fahrenheit.
  static const degreeMinutesFahrenheit = BacnetEngineeringUnits(47976);

  /// Degree Seconds Celsius.
  static const degreeSecondsCelsius = BacnetEngineeringUnits(47977);

  /// Degree Seconds Fahrenheit.
  static const degreeSecondsFahrenheit = BacnetEngineeringUnits(47978);

  /// Microseconds.
  static const microseconds = BacnetEngineeringUnits(47979);

  /// Nanoseconds.
  static const nanoseconds = BacnetEngineeringUnits(47980);

  /// Picoseconds.
  static const picoseconds = BacnetEngineeringUnits(47981);

  static const Map<BacnetEngineeringUnits, String> _labels = {
    squareMeters: 'Square Meters',
    squareFeet: 'Square Feet',
    milliamperes: 'Milliamperes',
    amperes: 'Amperes',
    ohms: 'Ohms',
    volts: 'Volts',
    kilovolts: 'Kilovolts',
    megavolts: 'Megavolts',
    voltAmperes: 'Volt Amperes',
    kilovoltAmperes: 'Kilovolt Amperes',
    megavoltAmperes: 'Megavolt Amperes',
    voltAmperesReactive: 'Volt Amperes Reactive',
    kilovoltAmperesReactive: 'Kilovolt Amperes Reactive',
    megavoltAmperesReactive: 'Megavolt Amperes Reactive',
    degreesPhase: 'Degrees Phase',
    powerFactor: 'Power Factor',
    joules: 'Joules',
    kilojoules: 'Kilojoules',
    wattHours: 'Watt Hours',
    kilowattHours: 'Kilowatt Hours',
    btus: 'BTUs',
    therms: 'Therms',
    tonHours: 'Ton Hours',
    joulesPerKilogramDryAir: 'Joules Per Kilogram Dry Air',
    btusPerPoundDryAir: 'BTUs Per Pound Dry Air',
    cyclesPerHour: 'Cycles Per Hour',
    cyclesPerMinute: 'Cycles Per Minute',
    hertz: 'Hertz',
    gramsOfWaterPerKilogramDryAir: 'Grams Of Water Per Kilogram Dry Air',
    percentRelativeHumidity: 'Percent Relative Humidity',
    millimeters: 'Millimeters',
    meters: 'Meters',
    inches: 'Inches',
    feet: 'Feet',
    wattsPerSquareFoot: 'Watts Per Square Foot',
    wattsPerSquareMeter: 'Watts Per Square Meter',
    lumens: 'Lumens',
    luxes: 'Luxes',
    footCandles: 'Foot Candles',
    kilograms: 'Kilograms',
    poundsMass: 'Pounds Mass',
    tons: 'Tons',
    kilogramsPerSecond: 'Kilograms Per Second',
    kilogramsPerMinute: 'Kilograms Per Minute',
    kilogramsPerHour: 'Kilograms Per Hour',
    poundsMassPerMinute: 'Pounds Mass Per Minute',
    poundsMassPerHour: 'Pounds Mass Per Hour',
    watts: 'Watts',
    kilowatts: 'Kilowatts',
    megawatts: 'Megawatts',
    btusPerHour: 'BTUs Per Hour',
    horsepower: 'Horsepower',
    tonsRefrigeration: 'Tons Refrigeration',
    pascals: 'Pascals',
    kilopascals: 'Kilopascals',
    bars: 'Bars',
    poundsForcePerSquareInch: 'Pounds Force Per Square Inch',
    centimetersOfWater: 'Centimeters Of Water',
    inchesOfWater: 'Inches Of Water',
    millimetersOfMercury: 'Millimeters Of Mercury',
    centimetersOfMercury: 'Centimeters Of Mercury',
    inchesOfMercury: 'Inches Of Mercury',
    degreesCelsius: 'Degrees Celsius',
    kelvin: 'Kelvin',
    degreesFahrenheit: 'Degrees Fahrenheit',
    degreeDaysCelsius: 'Degree Days Celsius',
    degreeDaysFahrenheit: 'Degree Days Fahrenheit',
    years: 'Years',
    months: 'Months',
    weeks: 'Weeks',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    metersPerSecond: 'Meters Per Second',
    kilometersPerHour: 'Kilometers Per Hour',
    feetPerSecond: 'Feet Per Second',
    feetPerMinute: 'Feet Per Minute',
    milesPerHour: 'Miles Per Hour',
    cubicFeet: 'Cubic Feet',
    cubicMeters: 'Cubic Meters',
    imperialGallons: 'Imperial Gallons',
    liters: 'Liters',
    usGallons: 'Us Gallons',
    cubicFeetPerMinute: 'Cubic Feet Per Minute',
    cubicMetersPerSecond: 'Cubic Meters Per Second',
    imperialGallonsPerMinute: 'Imperial Gallons Per Minute',
    litersPerSecond: 'Liters Per Second',
    litersPerMinute: 'Liters Per Minute',
    usGallonsPerMinute: 'Us Gallons Per Minute',
    degreesAngular: 'Degrees Angular',
    degreesCelsiusPerHour: 'Degrees Celsius Per Hour',
    degreesCelsiusPerMinute: 'Degrees Celsius Per Minute',
    degreesFahrenheitPerHour: 'Degrees Fahrenheit Per Hour',
    degreesFahrenheitPerMinute: 'Degrees Fahrenheit Per Minute',
    noUnits: 'No Units',
    partsPerMillion: 'Parts Per Million',
    partsPerBillion: 'Parts Per Billion',
    percent: 'Percent',
    percentPerSecond: 'Percent Per Second',
    perMinute: 'Per Minute',
    perSecond: 'Per Second',
    psiPerDegreeFahrenheit: 'Psi Per Degree Fahrenheit',
    radians: 'Radians',
    revolutionsPerMinute: 'Revolutions Per Minute',
    currency1: 'Currency1',
    currency2: 'Currency2',
    currency3: 'Currency3',
    currency4: 'Currency4',
    currency5: 'Currency5',
    currency6: 'Currency6',
    currency7: 'Currency7',
    currency8: 'Currency8',
    currency9: 'Currency9',
    currency10: 'Currency10',
    squareInches: 'Square Inches',
    squareCentimeters: 'Square Centimeters',
    btusPerPound: 'BTUs Per Pound',
    centimeters: 'Centimeters',
    poundsMassPerSecond: 'Pounds Mass Per Second',
    deltaDegreesFahrenheit: 'Delta Degrees Fahrenheit',
    deltaKelvin: 'Delta Kelvin',
    kilohms: 'Kilohms',
    megohms: 'Megohms',
    millivolts: 'Millivolts',
    kilojoulesPerKilogram: 'Kilojoules Per Kilogram',
    megajoules: 'Megajoules',
    joulesPerDegreeKelvin: 'Joules Per Degree Kelvin',
    joulesPerKilogramDegreeKelvin: 'Joules Per Kilogram Degree Kelvin',
    kilohertz: 'Kilohertz',
    megahertz: 'Megahertz',
    perHour: 'Per Hour',
    milliwatts: 'Milliwatts',
    hectopascals: 'Hectopascals',
    millibars: 'Millibars',
    cubicMetersPerHour: 'Cubic Meters Per Hour',
    litersPerHour: 'Liters Per Hour',
    kwHoursPerSquareMeter: 'Kw Hours Per Square Meter',
    kwHoursPerSquareFoot: 'Kw Hours Per Square Foot',
    megajoulesPerSquareMeter: 'Megajoules Per Square Meter',
    megajoulesPerSquareFoot: 'Megajoules Per Square Foot',
    wattsPerSquareMeterDegreeKelvin: 'Watts Per Square Meter Degree Kelvin',
    cubicFeetPerSecond: 'Cubic Feet Per Second',
    percentObscurationPerFoot: 'Percent Obscuration Per Foot',
    percentObscurationPerMeter: 'Percent Obscuration Per Meter',
    milliohms: 'Milliohms',
    megawattHours: 'Megawatt Hours',
    kiloBtus: 'Kilo BTUs',
    megaBtus: 'Mega BTUs',
    kilojoulesPerKilogramDryAir: 'Kilojoules Per Kilogram Dry Air',
    megajoulesPerKilogramDryAir: 'Megajoules Per Kilogram Dry Air',
    kilojoulesPerDegreeKelvin: 'Kilojoules Per Degree Kelvin',
    megajoulesPerDegreeKelvin: 'Megajoules Per Degree Kelvin',
    newton: 'Newton',
    gramsPerSecond: 'Grams Per Second',
    gramsPerMinute: 'Grams Per Minute',
    tonsPerHour: 'Tons Per Hour',
    kiloBtusPerHour: 'Kilo BTUs Per Hour',
    hundredthsSeconds: 'Hundredths Seconds',
    milliseconds: 'Milliseconds',
    newtonMeters: 'Newton Meters',
    millimetersPerSecond: 'Millimeters Per Second',
    millimetersPerMinute: 'Millimeters Per Minute',
    metersPerMinute: 'Meters Per Minute',
    metersPerHour: 'Meters Per Hour',
    cubicMetersPerMinute: 'Cubic Meters Per Minute',
    metersPerSecondPerSecond: 'Meters Per Second Per Second',
    amperesPerMeter: 'Amperes Per Meter',
    amperesPerSquareMeter: 'Amperes Per Square Meter',
    ampereSquareMeters: 'Ampere Square Meters',
    farads: 'Farads',
    henrys: 'Henrys',
    ohmMeters: 'Ohm Meters',
    siemens: 'Siemens',
    siemensPerMeter: 'Siemens Per Meter',
    teslas: 'Teslas',
    voltsPerDegreeKelvin: 'Volts Per Degree Kelvin',
    voltsPerMeter: 'Volts Per Meter',
    webers: 'Webers',
    candelas: 'Candelas',
    candelasPerSquareMeter: 'Candelas Per Square Meter',
    kelvinPerHour: 'Kelvin Per Hour',
    kelvinPerMinute: 'Kelvin Per Minute',
    jouleSeconds: 'Joule Seconds',
    radiansPerSecond: 'Radians Per Second',
    squareMetersPerNewton: 'Square Meters Per Newton',
    kilogramsPerCubicMeter: 'Kilograms Per Cubic Meter',
    newtonSeconds: 'Newton Seconds',
    newtonsPerMeter: 'Newtons Per Meter',
    wattsPerMeterPerDegreeKelvin: 'Watts Per Meter Per Degree Kelvin',
    microsiemens: 'Microsiemens',
    cubicFeetPerHour: 'Cubic Feet Per Hour',
    usGallonsPerHour: 'Us Gallons Per Hour',
    kilometers: 'Kilometers',
    micrometers: 'Micrometers',
    grams: 'Grams',
    milligrams: 'Milligrams',
    milliliters: 'Milliliters',
    millilitersPerSecond: 'Milliliters Per Second',
    decibels: 'Decibels',
    decibelsMillivolt: 'Decibels Millivolt',
    decibelsVolt: 'Decibels Volt',
    millisiemens: 'Millisiemens',
    wattReactiveHours: 'Watt Reactive Hours',
    kilowattReactiveHours: 'Kilowatt Reactive Hours',
    megawattReactiveHours: 'Megawatt Reactive Hours',
    millimetersOfWater: 'Millimeters Of Water',
    perMille: 'Per Mille',
    gramsPerGram: 'Grams Per Gram',
    kilogramsPerKilogram: 'Kilograms Per Kilogram',
    gramsPerKilogram: 'Grams Per Kilogram',
    milligramsPerGram: 'Milligrams Per Gram',
    milligramsPerKilogram: 'Milligrams Per Kilogram',
    gramsPerMilliliter: 'Grams Per Milliliter',
    gramsPerLiter: 'Grams Per Liter',
    milligramsPerLiter: 'Milligrams Per Liter',
    microgramsPerLiter: 'Micrograms Per Liter',
    gramsPerCubicMeter: 'Grams Per Cubic Meter',
    milligramsPerCubicMeter: 'Milligrams Per Cubic Meter',
    microgramsPerCubicMeter: 'Micrograms Per Cubic Meter',
    nanogramsPerCubicMeter: 'Nanograms Per Cubic Meter',
    gramsPerCubicCentimeter: 'Grams Per Cubic Centimeter',
    becquerels: 'Becquerels',
    kilobecquerels: 'Kilobecquerels',
    megabecquerels: 'Megabecquerels',
    gray: 'Gray',
    milligray: 'Milligray',
    microgray: 'Microgray',
    sieverts: 'Sieverts',
    millisieverts: 'Millisieverts',
    microsieverts: 'Microsieverts',
    microsievertsPerHour: 'Microsieverts Per Hour',
    decibelsA: 'Decibels A',
    nephelometricTurbidityUnit: 'Nephelometric Turbidity Unit',
    ph: 'Ph',
    gramsPerSquareMeter: 'Grams Per Square Meter',
    minutesPerDegreeKelvin: 'Minutes Per Degree Kelvin',
    ohmMeterSquaredPerMeter: 'Ohm Meter Squared Per Meter',
    ampereSeconds: 'Ampere Seconds',
    voltAmpereHours: 'Volt Ampere Hours',
    kilovoltAmpereHours: 'Kilovolt Ampere Hours',
    megavoltAmpereHours: 'Megavolt Ampere Hours',
    voltAmpereReactiveHours: 'Volt Ampere Reactive Hours',
    kilovoltAmpereReactiveHours: 'Kilovolt Ampere Reactive Hours',
    megavoltAmpereReactiveHours: 'Megavolt Ampere Reactive Hours',
    voltSquareHours: 'Volt Square Hours',
    ampereSquareHours: 'Ampere Square Hours',
    joulePerHours: 'Joule Per Hours',
    cubicFeetPerDay: 'Cubic Feet Per Day',
    cubicMetersPerDay: 'Cubic Meters Per Day',
    wattHoursPerCubicMeter: 'Watt Hours Per Cubic Meter',
    joulesPerCubicMeter: 'Joules Per Cubic Meter',
    molePercent: 'Mole Percent',
    pascalSeconds: 'Pascal Seconds',
    millionStandardCubicFeetPerMinute: 'Million Standard Cubic Feet Per Minute',
    standardCubicFeetPerDay: 'Standard Cubic Feet Per Day',
    millionStandardCubicFeetPerDay: 'Million Standard Cubic Feet Per Day',
    thousandCubicFeetPerDay: 'Thousand Cubic Feet Per Day',
    thousandStandardCubicFeetPerDay: 'Thousand Standard Cubic Feet Per Day',
    poundsMassPerDay: 'Pounds Mass Per Day',
    millirems: 'Millirems',
    milliremsPerHour: 'Millirems Per Hour',
    degreesLovibond: 'Degrees Lovibond',
    alcoholByVolume: 'Alcohol By Volume',
    internationalBitteringUnits: 'International Bittering Units',
    europeanBitternessUnits: 'European Bitterness Units',
    degreesPlato: 'Degrees Plato',
    specificGravity: 'Specific Gravity',
    europeanBrewingConvention: 'European Brewing Convention',
    perDay: 'Per Day',
    perMillisecond: 'Per Millisecond',
    yards: 'Yards',
    miles: 'Miles',
    nauticalMiles: 'Nautical Miles',
    nanograms: 'Nanograms',
    micrograms: 'Micrograms',
    metricTonnes: 'Metric Tonnes',
    shortTons: 'Short Tons',
    longTons: 'Long Tons',
    gramsPerHour: 'Grams Per Hour',
    gramsPerDay: 'Grams Per Day',
    kilogramsPerDay: 'Kilograms Per Day',
    shortTonsPerSecond: 'Short Tons Per Second',
    shortTonsPerMinute: 'Short Tons Per Minute',
    shortTonsPerHour: 'Short Tons Per Hour',
    shortTonsPerDay: 'Short Tons Per Day',
    metricTonnesPerSecond: 'Metric Tonnes Per Second',
    metricTonnesPerMinute: 'Metric Tonnes Per Minute',
    metricTonnesPerHour: 'Metric Tonnes Per Hour',
    metricTonnesPerDay: 'Metric Tonnes Per Day',
    longTonsPerSecond: 'Long Tons Per Second',
    longTonsPerMinute: 'Long Tons Per Minute',
    longTonsPerHour: 'Long Tons Per Hour',
    longTonsPerDay: 'Long Tons Per Day',
    btusPerSecond: 'BTUs Per Second',
    btusPerMinute: 'BTUs Per Minute',
    btusPerDay: 'BTUs Per Day',
    kiloBtusPerSecond: 'Kilo BTUs Per Second',
    kiloBtusPerMinute: 'Kilo BTUs Per Minute',
    kiloBtusPerDay: 'Kilo BTUs Per Day',
    megaBtusPerSecond: 'Mega BTUs Per Second',
    megaBtusPerMinute: 'Mega BTUs Per Minute',
    megaBtusPerHour: 'Mega BTUs Per Hour',
    megaBtusPerDay: 'Mega BTUs Per Day',
    joulesPerSecond: 'Joules Per Second',
    joulesPerMinute: 'Joules Per Minute',
    joulesPerDay: 'Joules Per Day',
    kilojoulesPerSecond: 'Kilojoules Per Second',
    kilojoulesPerMinute: 'Kilojoules Per Minute',
    kilojoulesPerHour: 'Kilojoules Per Hour',
    kilojoulesPerDay: 'Kilojoules Per Day',
    megajoulesPerSecond: 'Megajoules Per Second',
    megajoulesPerMinute: 'Megajoules Per Minute',
    megajoulesPerHour: 'Megajoules Per Hour',
    megajoulesPerDay: 'Megajoules Per Day',
    degreesCelsiusPerDay: 'Degrees Celsius Per Day',
    kelvinPerDay: 'Kelvin Per Day',
    degreesFahrenheitPerDay: 'Degrees Fahrenheit Per Day',
    deltaDegreesCelsius: 'Delta Degrees Celsius',
    millionCubicFeetPerMinute: 'Million Cubic Feet Per Minute',
    millionCubicFeetPerDay: 'Million Cubic Feet Per Day',
    imperialGallonsPerSecond: 'Imperial Gallons Per Second',
    imperialGallonsPerHour: 'Imperial Gallons Per Hour',
    imperialGallonsPerDay: 'Imperial Gallons Per Day',
    litersPerDay: 'Liters Per Day',
    usGallonsPerSecond: 'Us Gallons Per Second',
    usGallonsPerDay: 'Us Gallons Per Day',
    percentPerMinute: 'Percent Per Minute',
    percentPerHour: 'Percent Per Hour',
    percentPerDay: 'Percent Per Day',
    perMillion: 'Per Million',
    perBillion: 'Per Billion',
    microgramsPerGram: 'Micrograms Per Gram',
    nanogramsPerGram: 'Nanograms Per Gram',
    microgramsPerKilogram: 'Micrograms Per Kilogram',
    nanogramsPerKilogram: 'Nanograms Per Kilogram',
    milligramsPerMilliliter: 'Milligrams Per Milliliter',
    microgramsPerMilliliter: 'Micrograms Per Milliliter',
    nanogramsPerMilliliter: 'Nanograms Per Milliliter',
    kilogramsPerLiter: 'Kilograms Per Liter',
    nanogramsPerLiter: 'Nanograms Per Liter',
    milligramsPerCubicCentimeter: 'Milligrams Per Cubic Centimeter',
    microgramsPerCubicCentimeter: 'Micrograms Per Cubic Centimeter',
    nanogramsPerCubicCentimeter: 'Nanograms Per Cubic Centimeter',
    btuPerHourPerWatt: 'BTU Per Hour Per Watt',
    btuPerWattHourSeasonal: 'BTU Per Watt Hour Seasonal',
    coefficientOfPerformance: 'Coefficient Of Performance',
    coefficientOfPerformanceSeasonal: 'Coefficient Of Performance Seasonal',
    kilowattPerTonRefrigeration: 'Kilowatt Per Ton Refrigeration',
    lumensPerWatt: 'Lumens Per Watt',
    poundForceFeet: 'Pound Force Feet',
    poundForceInches: 'Pound Force Inches',
    ounceForceInches: 'Ounce Force Inches',
    poundsForcePerSquareInchAbsolute: 'Pounds Force Per Square Inch Absolute',
    poundsForcePerSquareInchGauge: 'Pounds Force Per Square Inch Gauge',
    microsiemensPerCentimeter: 'Microsiemens Per Centimeter',
    millisiemensPerCentimeter: 'Millisiemens Per Centimeter',
    millisiemensPerMeter: 'Millisiemens Per Meter',
    millionsOfUsGallons: 'Millions Of Us Gallons',
    millionsOfImperialGallons: 'Millions Of Imperial Gallons',
    millilitersPerMinute: 'Milliliters Per Minute',
    milsPerYear: 'Mils Per Year',
    millimetersPerYear: 'Millimeters Per Year',
    pulsesPerMinute: 'Pulses Per Minute',
    activeEnergyPulseValue: 'Active Energy Pulse Value',
    reactiveEnergyPulseValue: 'Reactive Energy Pulse Value',
    apparentEnergyPulseValue: 'Apparent Energy Pulse Value',
    voltSquaredHourPulseValue: 'Volt Squared Hour Pulse Value',
    ampereSquaredHourPulseValue: 'Ampere Squared Hour Pulse Value',
    cubicMeterPulseValue: 'Cubic Meter Pulse Value',
    gigawatts: 'Gigawatts',
    gigajoules: 'Gigajoules',
    terajoules: 'Terajoules',
    gigawattHours: 'Gigawatt Hours',
    gigawattReactiveHours: 'Gigawatt Reactive Hours',
    bitsPerSecond: 'Bits Per Second',
    kilobitsPerSecond: 'Kilobits Per Second',
    megabitsPerSecond: 'Megabits Per Second',
    gigabitsPerSecond: 'Gigabits Per Second',
    bytesPerSecond: 'Bytes Per Second',
    kilobytesPerSecond: 'Kilobytes Per Second',
    megabytesPerSecond: 'Megabytes Per Second',
    gigabytesPerSecond: 'Gigabytes Per Second',
    volume1: 'Volume1',
    volume2: 'Volume2',
    volume3: 'Volume3',
    volume4: 'Volume4',
    volume5: 'Volume5',
    volume6: 'Volume6',
    volume7: 'Volume7',
    volume8: 'Volume8',
    volume9: 'Volume9',
    volume10: 'Volume10',
    volumetricFlow1: 'Volumetric Flow1',
    volumetricFlow2: 'Volumetric Flow2',
    volumetricFlow3: 'Volumetric Flow3',
    volumetricFlow4: 'Volumetric Flow4',
    volumetricFlow5: 'Volumetric Flow5',
    volumetricFlow6: 'Volumetric Flow6',
    volumetricFlow7: 'Volumetric Flow7',
    volumetricFlow8: 'Volumetric Flow8',
    volumetricFlow9: 'Volumetric Flow9',
    volumetricFlow10: 'Volumetric Flow10',
    siteUnit1: 'Site Unit1',
    siteUnit2: 'Site Unit2',
    siteUnit3: 'Site Unit3',
    siteUnit4: 'Site Unit4',
    siteUnit5: 'Site Unit5',
    siteUnit6: 'Site Unit6',
    siteUnit7: 'Site Unit7',
    siteUnit8: 'Site Unit8',
    siteUnit9: 'Site Unit9',
    siteUnit10: 'Site Unit10',
    particlesPerCubicFoot: 'Particles Per Cubic Foot',
    particlesPerCubicMeter: 'Particles Per Cubic Meter',
    picocuriesPerLiter: 'Picocuries Per Liter',
    becquerelsPerCubicMeter: 'Becquerels Per Cubic Meter',
    grainsOfWaterPerPoundDryAir: 'Grains Of Water Per Pound Dry Air',
    degreeHoursCelsius: 'Degree Hours Celsius',
    degreeHoursFahrenheit: 'Degree Hours Fahrenheit',
    degreeMinutesCelsius: 'Degree Minutes Celsius',
    degreeMinutesFahrenheit: 'Degree Minutes Fahrenheit',
    degreeSecondsCelsius: 'Degree Seconds Celsius',
    degreeSecondsFahrenheit: 'Degree Seconds Fahrenheit',
    microseconds: 'Microseconds',
    nanoseconds: 'Nanoseconds',
    picoseconds: 'Picoseconds',
  };

  /// All values defined by this library.
  static Iterable<BacnetEngineeringUnits> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Units $value';

  /// Human readable name of this value.
  String get label => getName(value);
}
