// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet event states (BACnetEventState).
abstract final class BacnetEventState {
  /// Normal.
  static const int normal = 0;

  /// Fault.
  static const int fault = 1;

  /// Off Normal.
  static const int offNormal = 2;

  /// High Limit.
  static const int highLimit = 3;

  /// Low Limit.
  static const int lowLimit = 4;

  /// Life Safety Alarm.
  static const int lifeSafetyAlarm = 5;

  static const Map<int, String> _labels = {
    normal: 'Normal',
    fault: 'Fault',
    offNormal: 'Off Normal',
    highLimit: 'High Limit',
    lowLimit: 'Low Limit',
    lifeSafetyAlarm: 'Life Safety Alarm',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Event State $value';
}

/// BACnet reliability values (BACnetReliability).
abstract final class BacnetReliability {
  /// No Fault Detected.
  static const int noFaultDetected = 0;

  /// No Sensor.
  static const int noSensor = 1;

  /// Over Range.
  static const int overRange = 2;

  /// Under Range.
  static const int underRange = 3;

  /// Open Loop.
  static const int openLoop = 4;

  /// Shorted Loop.
  static const int shortedLoop = 5;

  /// No Output.
  static const int noOutput = 6;

  /// Unreliable Other.
  static const int unreliableOther = 7;

  /// Process Error.
  static const int processError = 8;

  /// Multi State Fault.
  static const int multiStateFault = 9;

  /// Configuration Error.
  static const int configurationError = 10;

  /// Communication Failure.
  static const int communicationFailure = 12;

  /// Member Fault.
  static const int memberFault = 13;

  /// Monitored Object Fault.
  static const int monitoredObjectFault = 14;

  /// Tripped.
  static const int tripped = 15;

  /// Lamp Failure.
  static const int lampFailure = 16;

  /// Activation Failure.
  static const int activationFailure = 17;

  /// Renew DHCP Failure.
  static const int renewDhcpFailure = 18;

  /// Renew FD Registration Failure.
  static const int renewFdRegistrationFailure = 19;

  /// Restart Auto Negotiation Failure.
  static const int restartAutoNegotiationFailure = 20;

  /// Restart Failure.
  static const int restartFailure = 21;

  /// Faults Listed.
  static const int faultsListed = 23;

  /// Referenced Object Fault.
  static const int referencedObjectFault = 24;

  /// Multi State Out Of Range.
  static const int multiStateOutOfRange = 25;

  static const Map<int, String> _labels = {
    noFaultDetected: 'No Fault Detected',
    noSensor: 'No Sensor',
    overRange: 'Over Range',
    underRange: 'Under Range',
    openLoop: 'Open Loop',
    shortedLoop: 'Shorted Loop',
    noOutput: 'No Output',
    unreliableOther: 'Unreliable Other',
    processError: 'Process Error',
    multiStateFault: 'Multi State Fault',
    configurationError: 'Configuration Error',
    communicationFailure: 'Communication Failure',
    memberFault: 'Member Fault',
    monitoredObjectFault: 'Monitored Object Fault',
    tripped: 'Tripped',
    lampFailure: 'Lamp Failure',
    activationFailure: 'Activation Failure',
    renewDhcpFailure: 'Renew DHCP Failure',
    renewFdRegistrationFailure: 'Renew FD Registration Failure',
    restartAutoNegotiationFailure: 'Restart Auto Negotiation Failure',
    restartFailure: 'Restart Failure',
    faultsListed: 'Faults Listed',
    referencedObjectFault: 'Referenced Object Fault',
    multiStateOutOfRange: 'Multi State Out Of Range',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Reliability $value';
}

/// BACnet device status values (BACnetDeviceStatus).
abstract final class BacnetDeviceStatus {
  /// Operational.
  static const int operational = 0;

  /// Operational Read Only.
  static const int operationalReadOnly = 1;

  /// Download Required.
  static const int downloadRequired = 2;

  /// Download In Progress.
  static const int downloadInProgress = 3;

  /// Non Operational.
  static const int nonOperational = 4;

  /// Backup In Progress.
  static const int backupInProgress = 5;

  static const Map<int, String> _labels = {
    operational: 'Operational',
    operationalReadOnly: 'Operational Read Only',
    downloadRequired: 'Download Required',
    downloadInProgress: 'Download In Progress',
    nonOperational: 'Non Operational',
    backupInProgress: 'Backup In Progress',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Device Status $value';
}

/// BACnet segmentation support (BACnetSegmentation).
abstract final class BacnetSegmentation {
  /// Both.
  static const int both = 0;

  /// Transmit.
  static const int transmit = 1;

  /// Receive.
  static const int receive = 2;

  /// None.
  static const int none = 3;

  static const Map<int, String> _labels = {
    both: 'Both',
    transmit: 'Transmit',
    receive: 'Receive',
    none: 'None',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Segmentation $value';
}
