// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet event states (BACnetEventState).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetEventState(value)`.
extension type const BacnetEventState(int value) implements int {
  /// Normal.
  static const normal = BacnetEventState(0);

  /// Fault.
  static const fault = BacnetEventState(1);

  /// Off Normal.
  static const offNormal = BacnetEventState(2);

  /// High Limit.
  static const highLimit = BacnetEventState(3);

  /// Low Limit.
  static const lowLimit = BacnetEventState(4);

  /// Life Safety Alarm.
  static const lifeSafetyAlarm = BacnetEventState(5);

  static const Map<BacnetEventState, String> _labels = {
    normal: 'Normal',
    fault: 'Fault',
    offNormal: 'Off Normal',
    highLimit: 'High Limit',
    lowLimit: 'Low Limit',
    lifeSafetyAlarm: 'Life Safety Alarm',
  };

  /// All values defined by this library.
  static Iterable<BacnetEventState> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Event State $value';

  /// Human readable name of this value.
  String get label => getName(value);
}

/// BACnet reliability values (BACnetReliability).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetReliability(value)`.
extension type const BacnetReliability(int value) implements int {
  /// No Fault Detected.
  static const noFaultDetected = BacnetReliability(0);

  /// No Sensor.
  static const noSensor = BacnetReliability(1);

  /// Over Range.
  static const overRange = BacnetReliability(2);

  /// Under Range.
  static const underRange = BacnetReliability(3);

  /// Open Loop.
  static const openLoop = BacnetReliability(4);

  /// Shorted Loop.
  static const shortedLoop = BacnetReliability(5);

  /// No Output.
  static const noOutput = BacnetReliability(6);

  /// Unreliable Other.
  static const unreliableOther = BacnetReliability(7);

  /// Process Error.
  static const processError = BacnetReliability(8);

  /// Multi State Fault.
  static const multiStateFault = BacnetReliability(9);

  /// Configuration Error.
  static const configurationError = BacnetReliability(10);

  /// Communication Failure.
  static const communicationFailure = BacnetReliability(12);

  /// Member Fault.
  static const memberFault = BacnetReliability(13);

  /// Monitored Object Fault.
  static const monitoredObjectFault = BacnetReliability(14);

  /// Tripped.
  static const tripped = BacnetReliability(15);

  /// Lamp Failure.
  static const lampFailure = BacnetReliability(16);

  /// Activation Failure.
  static const activationFailure = BacnetReliability(17);

  /// Renew DHCP Failure.
  static const renewDhcpFailure = BacnetReliability(18);

  /// Renew FD Registration Failure.
  static const renewFdRegistrationFailure = BacnetReliability(19);

  /// Restart Auto Negotiation Failure.
  static const restartAutoNegotiationFailure = BacnetReliability(20);

  /// Restart Failure.
  static const restartFailure = BacnetReliability(21);

  /// Faults Listed.
  static const faultsListed = BacnetReliability(23);

  /// Referenced Object Fault.
  static const referencedObjectFault = BacnetReliability(24);

  /// Multi State Out Of Range.
  static const multiStateOutOfRange = BacnetReliability(25);

  static const Map<BacnetReliability, String> _labels = {
    noFaultDetected: 'No Fault Detected',
    noSensor: 'No Sensor',
    overRange: 'Over Range',
    underRange: 'Under Range',
    openLoop: 'Open Loop',
    shortedLoop: 'Shorted Loop',
    noOutput: 'No Output',
    unreliableOther: 'Unreliable Other',
    processError: 'Process Error',
    multiStateFault: 'Multi State Fault',
    configurationError: 'Configuration Error',
    communicationFailure: 'Communication Failure',
    memberFault: 'Member Fault',
    monitoredObjectFault: 'Monitored Object Fault',
    tripped: 'Tripped',
    lampFailure: 'Lamp Failure',
    activationFailure: 'Activation Failure',
    renewDhcpFailure: 'Renew DHCP Failure',
    renewFdRegistrationFailure: 'Renew FD Registration Failure',
    restartAutoNegotiationFailure: 'Restart Auto Negotiation Failure',
    restartFailure: 'Restart Failure',
    faultsListed: 'Faults Listed',
    referencedObjectFault: 'Referenced Object Fault',
    multiStateOutOfRange: 'Multi State Out Of Range',
  };

  /// All values defined by this library.
  static Iterable<BacnetReliability> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Reliability $value';

  /// Human readable name of this value.
  String get label => getName(value);
}

/// BACnet device status values (BACnetDeviceStatus).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetDeviceStatus(value)`.
extension type const BacnetDeviceStatus(int value) implements int {
  /// Operational.
  static const operational = BacnetDeviceStatus(0);

  /// Operational Read Only.
  static const operationalReadOnly = BacnetDeviceStatus(1);

  /// Download Required.
  static const downloadRequired = BacnetDeviceStatus(2);

  /// Download In Progress.
  static const downloadInProgress = BacnetDeviceStatus(3);

  /// Non Operational.
  static const nonOperational = BacnetDeviceStatus(4);

  /// Backup In Progress.
  static const backupInProgress = BacnetDeviceStatus(5);

  static const Map<BacnetDeviceStatus, String> _labels = {
    operational: 'Operational',
    operationalReadOnly: 'Operational Read Only',
    downloadRequired: 'Download Required',
    downloadInProgress: 'Download In Progress',
    nonOperational: 'Non Operational',
    backupInProgress: 'Backup In Progress',
  };

  /// All values defined by this library.
  static Iterable<BacnetDeviceStatus> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Device Status $value';

  /// Human readable name of this value.
  String get label => getName(value);
}

/// BACnet segmentation support (BACnetSegmentation).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetSegmentation(value)`.
extension type const BacnetSegmentation(int value) implements int {
  /// Both.
  static const both = BacnetSegmentation(0);

  /// Transmit.
  static const transmit = BacnetSegmentation(1);

  /// Receive.
  static const receive = BacnetSegmentation(2);

  /// None.
  static const none = BacnetSegmentation(3);

  static const Map<BacnetSegmentation, String> _labels = {
    both: 'Both',
    transmit: 'Transmit',
    receive: 'Receive',
    none: 'None',
  };

  /// All values defined by this library.
  static Iterable<BacnetSegmentation> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Segmentation $value';

  /// Human readable name of this value.
  String get label => getName(value);
}
