// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet error classes (BACnetErrorClass).
abstract final class BacnetErrorClass {
  /// Device.
  static const int device = 0;

  /// Object.
  static const int object = 1;

  /// Property.
  static const int property = 2;

  /// Resources.
  static const int resources = 3;

  /// Security.
  static const int security = 4;

  /// Services.
  static const int services = 5;

  /// VT.
  static const int vt = 6;

  /// Communication.
  static const int communication = 7;

  static const Map<int, String> _labels = {
    device: 'Device',
    object: 'Object',
    property: 'Property',
    resources: 'Resources',
    security: 'Security',
    services: 'Services',
    vt: 'VT',
    communication: 'Communication',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) =>
      _labels[value] ?? 'Unknown Class ($value)';
}

/// BACnet error codes (BACnetErrorCode).
abstract final class BacnetErrorCode {
  /// Other.
  static const int other = 0;

  /// Authentication Failed.
  static const int authenticationFailed = 1;

  /// Configuration In Progress.
  static const int configurationInProgress = 2;

  /// Device Busy.
  static const int deviceBusy = 3;

  /// Dynamic Creation Not Supported.
  static const int dynamicCreationNotSupported = 4;

  /// File Access Denied.
  static const int fileAccessDenied = 5;

  /// Incompatible Security Levels.
  static const int incompatibleSecurityLevels = 6;

  /// Inconsistent Parameters.
  static const int inconsistentParameters = 7;

  /// Inconsistent Selection Criterion.
  static const int inconsistentSelectionCriterion = 8;

  /// Invalid Data Type.
  static const int invalidDataType = 9;

  /// Invalid File Access Method.
  static const int invalidFileAccessMethod = 10;

  /// Invalid File Start Position.
  static const int invalidFileStartPosition = 11;

  /// Invalid Operator Name.
  static const int invalidOperatorName = 12;

  /// Invalid Parameter Data Type.
  static const int invalidParameterDataType = 13;

  /// Invalid Time Stamp.
  static const int invalidTimeStamp = 14;

  /// Key Generation Error.
  static const int keyGeneration = 15;

  /// Missing Required Parameter.
  static const int missingRequiredParameter = 16;

  /// No Objects Of Specified Type.
  static const int noObjectsOfSpecifiedType = 17;

  /// No Space For Object.
  static const int noSpaceForObject = 18;

  /// No Space To Add List Element.
  static const int noSpaceToAddListElement = 19;

  /// No Space To Write Property.
  static const int noSpaceToWriteProperty = 20;

  /// No VT Sessions Available.
  static const int noVtSessionsAvailable = 21;

  /// Property Is Not A List.
  static const int propertyIsNotAList = 22;

  /// Object Deletion Not Permitted.
  static const int objectDeletionNotPermitted = 23;

  /// Object Identifier Already Exists.
  static const int objectIdentifierAlreadyExists = 24;

  /// Operational Problem.
  static const int operationalProblem = 25;

  /// Password Failure.
  static const int passwordFailure = 26;

  /// Read Access Denied.
  static const int readAccessDenied = 27;

  /// Security Not Supported.
  static const int securityNotSupported = 28;

  /// Service Request Denied.
  static const int serviceRequestDenied = 29;

  /// Timeout.
  static const int timeout = 30;

  /// Unknown Object.
  static const int unknownObject = 31;

  /// Unknown Property.
  static const int unknownProperty = 32;

  /// Unknown VT Class.
  static const int unknownVtClass = 34;

  /// Unknown VT Session.
  static const int unknownVtSession = 35;

  /// Unsupported Object Type.
  static const int unsupportedObjectType = 36;

  /// Value Out Of Range.
  static const int valueOutOfRange = 37;

  /// VT Session Already Closed.
  static const int vtSessionAlreadyClosed = 38;

  /// VT Session Termination Failure.
  static const int vtSessionTerminationFailure = 39;

  /// Write Access Denied.
  static const int writeAccessDenied = 40;

  /// Character Set Not Supported.
  static const int characterSetNotSupported = 41;

  /// Invalid Array Index.
  static const int invalidArrayIndex = 42;

  /// COV Subscription Failed.
  static const int covSubscriptionFailed = 43;

  /// Not COV Property.
  static const int notCovProperty = 44;

  /// Optional Functionality Not Supported.
  static const int optionalFunctionalityNotSupported = 45;

  /// Invalid Configuration Data.
  static const int invalidConfigurationData = 46;

  /// Datatype Not Supported.
  static const int datatypeNotSupported = 47;

  /// Duplicate Name.
  static const int duplicateName = 48;

  /// Duplicate Object ID.
  static const int duplicateObjectId = 49;

  /// Property Is Not An Array.
  static const int propertyIsNotAnArray = 50;

  /// Abort Buffer Overflow.
  static const int abortBufferOverflow = 51;

  /// Abort Invalid APDU In This State.
  static const int abortInvalidApduInThisState = 52;

  /// Abort Preempted By Higher Priority Task.
  static const int abortPreemptedByHigherPriorityTask = 53;

  /// Abort Segmentation Not Supported.
  static const int abortSegmentationNotSupported = 54;

  /// Abort Other.
  static const int abortOther = 56;

  /// Invalid Tag.
  static const int invalidTag = 57;

  /// Network Down.
  static const int networkDown = 58;

  /// Reject Buffer Overflow.
  static const int rejectBufferOverflow = 59;

  /// Reject Inconsistent Parameters.
  static const int rejectInconsistentParameters = 60;

  /// Reject Invalid Parameter Data Type.
  static const int rejectInvalidParameterDataType = 61;

  /// Reject Invalid Tag.
  static const int rejectInvalidTag = 62;

  /// Reject Missing Required Parameter.
  static const int rejectMissingRequiredParameter = 63;

  /// Reject Parameter Out Of Range.
  static const int rejectParameterOutOfRange = 64;

  /// Reject Too Many Arguments.
  static const int rejectTooManyArguments = 65;

  /// Reject Undefined Enumeration.
  static const int rejectUndefinedEnumeration = 66;

  /// Reject Unrecognized Service.
  static const int rejectUnrecognizedService = 67;

  /// Reject Other.
  static const int rejectOther = 69;

  /// Unknown Device.
  static const int unknownDevice = 70;

  /// Unknown Route.
  static const int unknownRoute = 71;

  /// Value Not Initialized.
  static const int valueNotInitialized = 72;

  /// Invalid Event State.
  static const int invalidEventState = 73;

  /// No Alarm Configured.
  static const int noAlarmConfigured = 74;

  /// Log Buffer Full.
  static const int logBufferFull = 75;

  /// Logged Value Purged.
  static const int loggedValuePurged = 76;

  /// No Property Specified.
  static const int noPropertySpecified = 77;

  /// Not Configured For Triggered Logging.
  static const int notConfiguredForTriggeredLogging = 78;

  /// Unknown Subscription.
  static const int unknownSubscription = 79;

  /// Parameter Out Of Range.
  static const int parameterOutOfRange = 80;

  /// List Element Not Found.
  static const int listElementNotFound = 81;

  /// Busy.
  static const int busy = 82;

  /// Communication Disabled.
  static const int communicationDisabled = 83;

  /// Success.
  static const int success = 84;

  /// Access Denied.
  static const int accessDenied = 85;

  /// Bad Destination Address.
  static const int badDestinationAddress = 86;

  /// Bad Destination Device ID.
  static const int badDestinationDeviceId = 87;

  /// Bad Signature.
  static const int badSignature = 88;

  /// Bad Source Address.
  static const int badSourceAddress = 89;

  /// Bad Timestamp.
  static const int badTimestamp = 90;

  /// Cannot Use Key.
  static const int cannotUseKey = 91;

  /// Cannot Verify Message ID.
  static const int cannotVerifyMessageId = 92;

  /// Correct Key Revision.
  static const int correctKeyRevision = 93;

  /// Destination Device ID Required.
  static const int destinationDeviceIdRequired = 94;

  /// Duplicate Message.
  static const int duplicateMessage = 95;

  /// Encryption Not Configured.
  static const int encryptionNotConfigured = 96;

  /// Encryption Required.
  static const int encryptionRequired = 97;

  /// Incorrect Key.
  static const int incorrectKey = 98;

  /// Invalid Key Data.
  static const int invalidKeyData = 99;

  /// Key Update In Progress.
  static const int keyUpdateInProgress = 100;

  /// Malformed Message.
  static const int malformedMessage = 101;

  /// Not Key Server.
  static const int notKeyServer = 102;

  /// Security Not Configured.
  static const int securityNotConfigured = 103;

  /// Source Security Required.
  static const int sourceSecurityRequired = 104;

  /// Too Many Keys.
  static const int tooManyKeys = 105;

  /// Unknown Authentication Type.
  static const int unknownAuthenticationType = 106;

  /// Unknown Key.
  static const int unknownKey = 107;

  /// Unknown Key Revision.
  static const int unknownKeyRevision = 108;

  /// Unknown Source Message.
  static const int unknownSourceMessage = 109;

  /// Not Router To Dnet.
  static const int notRouterToDnet = 110;

  /// Router Busy.
  static const int routerBusy = 111;

  /// Unknown Network Message.
  static const int unknownNetworkMessage = 112;

  /// Message Too Long.
  static const int messageTooLong = 113;

  /// Security Error.
  static const int securityError = 114;

  /// Addressing Error.
  static const int addressingError = 115;

  /// Write Bdt Failed.
  static const int writeBdtFailed = 116;

  /// Read Bdt Failed.
  static const int readBdtFailed = 117;

  /// Register Foreign Device Failed.
  static const int registerForeignDeviceFailed = 118;

  /// Read Fdt Failed.
  static const int readFdtFailed = 119;

  /// Delete Fdt Entry Failed.
  static const int deleteFdtEntryFailed = 120;

  /// Distribute Broadcast Failed.
  static const int distributeBroadcastFailed = 121;

  /// Unknown File Size.
  static const int unknownFileSize = 122;

  /// Abort APDU Too Long.
  static const int abortApduTooLong = 123;

  /// Abort Application Exceeded Reply Time.
  static const int abortApplicationExceededReplyTime = 124;

  /// Abort Out Of Resources.
  static const int abortOutOfResources = 125;

  /// Abort TSM Timeout.
  static const int abortTsmTimeout = 126;

  /// Abort Window Size Out Of Range.
  static const int abortWindowSizeOutOfRange = 127;

  /// File Full.
  static const int fileFull = 128;

  /// Inconsistent Configuration.
  static const int inconsistentConfiguration = 129;

  /// Inconsistent Object Type.
  static const int inconsistentObjectType = 130;

  /// Internal Error.
  static const int internalError = 131;

  /// Not Configured.
  static const int notConfigured = 132;

  /// Out Of Memory.
  static const int outOfMemory = 133;

  /// Value Too Long.
  static const int valueTooLong = 134;

  /// Abort Insufficient Security.
  static const int abortInsufficientSecurity = 135;

  /// Abort Security Error.
  static const int abortSecurityError = 136;

  /// Duplicate Entry.
  static const int duplicateEntry = 137;

  /// Invalid Value In This State.
  static const int invalidValueInThisState = 138;

  /// Invalid Operation In This State.
  static const int invalidOperationInThisState = 139;

  /// List Item Not Numbered.
  static const int listItemNotNumbered = 140;

  /// List Item Not Timestamped.
  static const int listItemNotTimestamped = 141;

  /// Invalid Data Encoding.
  static const int invalidDataEncoding = 142;

  /// Bvlc Function Unknown.
  static const int bvlcFunctionUnknown = 143;

  /// Header Encoding Error.
  static const int headerEncodingError = 145;

  /// Header Not Understood.
  static const int headerNotUnderstood = 146;

  /// Message Incomplete.
  static const int messageIncomplete = 147;

  /// Not A BACnet SC Hub.
  static const int notABacnetScHub = 148;

  /// Payload Expected.
  static const int payloadExpected = 149;

  /// Unexpected Data.
  static const int unexpectedData = 150;

  /// Node Duplicate VMAC.
  static const int nodeDuplicateVmac = 151;

  /// Http Unexpected Response Code.
  static const int httpUnexpectedResponseCode = 152;

  /// Http No Upgrade.
  static const int httpNoUpgrade = 153;

  /// Http Resource Not Local.
  static const int httpResourceNotLocal = 154;

  /// Http Proxy Authentication Failed.
  static const int httpProxyAuthenticationFailed = 155;

  /// Http Response Timeout.
  static const int httpResponseTimeout = 156;

  /// Http Response Syntax Error.
  static const int httpResponseSyntaxError = 157;

  /// Http Response Value Error.
  static const int httpResponseValueError = 158;

  /// Http Response Missing Header.
  static const int httpResponseMissingHeader = 159;

  /// Http Websocket Header Error.
  static const int httpWebsocketHeaderError = 160;

  /// Http Upgrade Required.
  static const int httpUpgradeRequired = 161;

  /// Http Upgrade Error.
  static const int httpUpgradeError = 162;

  /// Http Temporary Unavailable.
  static const int httpTemporaryUnavailable = 163;

  /// Http Not A Server.
  static const int httpNotAServer = 164;

  /// Http Error.
  static const int httpError = 165;

  /// Websocket Scheme Not Supported.
  static const int websocketSchemeNotSupported = 166;

  /// Websocket Unknown Control Message.
  static const int websocketUnknownControlMessage = 167;

  /// Websocket Close Error.
  static const int websocketCloseError = 168;

  /// Websocket Closed By Peer.
  static const int websocketClosedByPeer = 169;

  /// Websocket Endpoint Leaves.
  static const int websocketEndpointLeaves = 170;

  /// Websocket Protocol Error.
  static const int websocketProtocolError = 171;

  /// Websocket Data Not Accepted.
  static const int websocketDataNotAccepted = 172;

  /// Websocket Closed Abnormally.
  static const int websocketClosedAbnormally = 173;

  /// Websocket Data Inconsistent.
  static const int websocketDataInconsistent = 174;

  /// Websocket Data Against Policy.
  static const int websocketDataAgainstPolicy = 175;

  /// Websocket Frame Too Long.
  static const int websocketFrameTooLong = 176;

  /// Websocket Extension Missing.
  static const int websocketExtensionMissing = 177;

  /// Websocket Request Unavailable.
  static const int websocketRequestUnavailable = 178;

  /// Websocket Error.
  static const int websocketError = 179;

  /// Tls Client Certificate Error.
  static const int tlsClientCertificateError = 180;

  /// Tls Server Certificate Error.
  static const int tlsServerCertificateError = 181;

  /// Tls Client Authentication Failed.
  static const int tlsClientAuthenticationFailed = 182;

  /// Tls Server Authentication Failed.
  static const int tlsServerAuthenticationFailed = 183;

  /// Tls Client Certificate Expired.
  static const int tlsClientCertificateExpired = 184;

  /// Tls Server Certificate Expired.
  static const int tlsServerCertificateExpired = 185;

  /// Tls Client Certificate Revoked.
  static const int tlsClientCertificateRevoked = 186;

  /// Tls Server Certificate Revoked.
  static const int tlsServerCertificateRevoked = 187;

  /// Tls Error.
  static const int tlsError = 188;

  /// DNS Unavailable.
  static const int dnsUnavailable = 189;

  /// DNS Name Resolution Failed.
  static const int dnsNameResolutionFailed = 190;

  /// DNS Resolver Failure.
  static const int dnsResolverFailure = 191;

  /// DNS Error.
  static const int dnsError = 192;

  /// Tcp Connect Timeout.
  static const int tcpConnectTimeout = 193;

  /// Tcp Connection Refused.
  static const int tcpConnectionRefused = 194;

  /// Tcp Closed By Local.
  static const int tcpClosedByLocal = 195;

  /// Tcp Closed Other.
  static const int tcpClosedOther = 196;

  /// Tcp Error.
  static const int tcpError = 197;

  /// IP Address Not Reachable.
  static const int ipAddressNotReachable = 198;

  /// IP Error.
  static const int ipError = 199;

  /// Certificate Expired.
  static const int certificateExpired = 200;

  /// Certificate Invalid.
  static const int certificateInvalid = 201;

  /// Certificate Malformed.
  static const int certificateMalformed = 202;

  /// Certificate Revoked.
  static const int certificateRevoked = 203;

  /// Unknown Security Key.
  static const int unknownSecurityKey = 204;

  /// Referenced Port In Error.
  static const int referencedPortInError = 205;

  /// Not Enabled.
  static const int notEnabled = 206;

  /// Adjust Scope Required.
  static const int adjustScopeRequired = 207;

  /// Auth Scope Required.
  static const int authScopeRequired = 208;

  /// Bind Scope Required.
  static const int bindScopeRequired = 209;

  /// Config Scope Required.
  static const int configScopeRequired = 210;

  /// Control Scope Required.
  static const int controlScopeRequired = 211;

  /// Extended Scope Required.
  static const int extendedScopeRequired = 212;

  /// Incorrect Client.
  static const int incorrectClient = 213;

  /// Install Scope Required.
  static const int installScopeRequired = 214;

  /// Insufficient Scope.
  static const int insufficientScope = 215;

  /// No Default Scope.
  static const int noDefaultScope = 216;

  /// No Policy.
  static const int noPolicy = 217;

  /// Revoked Token.
  static const int revokedToken = 218;

  /// Override Scope Required.
  static const int overrideScopeRequired = 219;

  /// Inactive Token.
  static const int inactiveToken = 220;

  /// Unknown Audience.
  static const int unknownAudience = 221;

  /// Unknown Client.
  static const int unknownClient = 222;

  /// Unknown Scope.
  static const int unknownScope = 223;

  /// View Scope Required.
  static const int viewScopeRequired = 224;

  /// Incorrect Audience.
  static const int incorrectAudience = 225;

  /// Incorrect Client Origin.
  static const int incorrectClientOrigin = 226;

  /// Invalid Array Size.
  static const int invalidArraySize = 227;

  /// Incorrect Issuer.
  static const int incorrectIssuer = 228;

  /// Invalid Token.
  static const int invalidToken = 229;

  static const Map<int, String> _labels = {
    other: 'Other',
    authenticationFailed: 'Authentication Failed',
    configurationInProgress: 'Configuration In Progress',
    deviceBusy: 'Device Busy',
    dynamicCreationNotSupported: 'Dynamic Creation Not Supported',
    fileAccessDenied: 'File Access Denied',
    incompatibleSecurityLevels: 'Incompatible Security Levels',
    inconsistentParameters: 'Inconsistent Parameters',
    inconsistentSelectionCriterion: 'Inconsistent Selection Criterion',
    invalidDataType: 'Invalid Data Type',
    invalidFileAccessMethod: 'Invalid File Access Method',
    invalidFileStartPosition: 'Invalid File Start Position',
    invalidOperatorName: 'Invalid Operator Name',
    invalidParameterDataType: 'Invalid Parameter Data Type',
    invalidTimeStamp: 'Invalid Time Stamp',
    keyGeneration: 'Key Generation Error',
    missingRequiredParameter: 'Missing Required Parameter',
    noObjectsOfSpecifiedType: 'No Objects Of Specified Type',
    noSpaceForObject: 'No Space For Object',
    noSpaceToAddListElement: 'No Space To Add List Element',
    noSpaceToWriteProperty: 'No Space To Write Property',
    noVtSessionsAvailable: 'No VT Sessions Available',
    propertyIsNotAList: 'Property Is Not A List',
    objectDeletionNotPermitted: 'Object Deletion Not Permitted',
    objectIdentifierAlreadyExists: 'Object Identifier Already Exists',
    operationalProblem: 'Operational Problem',
    passwordFailure: 'Password Failure',
    readAccessDenied: 'Read Access Denied',
    securityNotSupported: 'Security Not Supported',
    serviceRequestDenied: 'Service Request Denied',
    timeout: 'Timeout',
    unknownObject: 'Unknown Object',
    unknownProperty: 'Unknown Property',
    unknownVtClass: 'Unknown VT Class',
    unknownVtSession: 'Unknown VT Session',
    unsupportedObjectType: 'Unsupported Object Type',
    valueOutOfRange: 'Value Out Of Range',
    vtSessionAlreadyClosed: 'VT Session Already Closed',
    vtSessionTerminationFailure: 'VT Session Termination Failure',
    writeAccessDenied: 'Write Access Denied',
    characterSetNotSupported: 'Character Set Not Supported',
    invalidArrayIndex: 'Invalid Array Index',
    covSubscriptionFailed: 'COV Subscription Failed',
    notCovProperty: 'Not COV Property',
    optionalFunctionalityNotSupported: 'Optional Functionality Not Supported',
    invalidConfigurationData: 'Invalid Configuration Data',
    datatypeNotSupported: 'Datatype Not Supported',
    duplicateName: 'Duplicate Name',
    duplicateObjectId: 'Duplicate Object ID',
    propertyIsNotAnArray: 'Property Is Not An Array',
    abortBufferOverflow: 'Abort Buffer Overflow',
    abortInvalidApduInThisState: 'Abort Invalid APDU In This State',
    abortPreemptedByHigherPriorityTask:
        'Abort Preempted By Higher Priority Task',
    abortSegmentationNotSupported: 'Abort Segmentation Not Supported',
    abortOther: 'Abort Other',
    invalidTag: 'Invalid Tag',
    networkDown: 'Network Down',
    rejectBufferOverflow: 'Reject Buffer Overflow',
    rejectInconsistentParameters: 'Reject Inconsistent Parameters',
    rejectInvalidParameterDataType: 'Reject Invalid Parameter Data Type',
    rejectInvalidTag: 'Reject Invalid Tag',
    rejectMissingRequiredParameter: 'Reject Missing Required Parameter',
    rejectParameterOutOfRange: 'Reject Parameter Out Of Range',
    rejectTooManyArguments: 'Reject Too Many Arguments',
    rejectUndefinedEnumeration: 'Reject Undefined Enumeration',
    rejectUnrecognizedService: 'Reject Unrecognized Service',
    rejectOther: 'Reject Other',
    unknownDevice: 'Unknown Device',
    unknownRoute: 'Unknown Route',
    valueNotInitialized: 'Value Not Initialized',
    invalidEventState: 'Invalid Event State',
    noAlarmConfigured: 'No Alarm Configured',
    logBufferFull: 'Log Buffer Full',
    loggedValuePurged: 'Logged Value Purged',
    noPropertySpecified: 'No Property Specified',
    notConfiguredForTriggeredLogging: 'Not Configured For Triggered Logging',
    unknownSubscription: 'Unknown Subscription',
    parameterOutOfRange: 'Parameter Out Of Range',
    listElementNotFound: 'List Element Not Found',
    busy: 'Busy',
    communicationDisabled: 'Communication Disabled',
    success: 'Success',
    accessDenied: 'Access Denied',
    badDestinationAddress: 'Bad Destination Address',
    badDestinationDeviceId: 'Bad Destination Device ID',
    badSignature: 'Bad Signature',
    badSourceAddress: 'Bad Source Address',
    badTimestamp: 'Bad Timestamp',
    cannotUseKey: 'Cannot Use Key',
    cannotVerifyMessageId: 'Cannot Verify Message ID',
    correctKeyRevision: 'Correct Key Revision',
    destinationDeviceIdRequired: 'Destination Device ID Required',
    duplicateMessage: 'Duplicate Message',
    encryptionNotConfigured: 'Encryption Not Configured',
    encryptionRequired: 'Encryption Required',
    incorrectKey: 'Incorrect Key',
    invalidKeyData: 'Invalid Key Data',
    keyUpdateInProgress: 'Key Update In Progress',
    malformedMessage: 'Malformed Message',
    notKeyServer: 'Not Key Server',
    securityNotConfigured: 'Security Not Configured',
    sourceSecurityRequired: 'Source Security Required',
    tooManyKeys: 'Too Many Keys',
    unknownAuthenticationType: 'Unknown Authentication Type',
    unknownKey: 'Unknown Key',
    unknownKeyRevision: 'Unknown Key Revision',
    unknownSourceMessage: 'Unknown Source Message',
    notRouterToDnet: 'Not Router To Dnet',
    routerBusy: 'Router Busy',
    unknownNetworkMessage: 'Unknown Network Message',
    messageTooLong: 'Message Too Long',
    securityError: 'Security Error',
    addressingError: 'Addressing Error',
    writeBdtFailed: 'Write Bdt Failed',
    readBdtFailed: 'Read Bdt Failed',
    registerForeignDeviceFailed: 'Register Foreign Device Failed',
    readFdtFailed: 'Read Fdt Failed',
    deleteFdtEntryFailed: 'Delete Fdt Entry Failed',
    distributeBroadcastFailed: 'Distribute Broadcast Failed',
    unknownFileSize: 'Unknown File Size',
    abortApduTooLong: 'Abort APDU Too Long',
    abortApplicationExceededReplyTime: 'Abort Application Exceeded Reply Time',
    abortOutOfResources: 'Abort Out Of Resources',
    abortTsmTimeout: 'Abort TSM Timeout',
    abortWindowSizeOutOfRange: 'Abort Window Size Out Of Range',
    fileFull: 'File Full',
    inconsistentConfiguration: 'Inconsistent Configuration',
    inconsistentObjectType: 'Inconsistent Object Type',
    internalError: 'Internal Error',
    notConfigured: 'Not Configured',
    outOfMemory: 'Out Of Memory',
    valueTooLong: 'Value Too Long',
    abortInsufficientSecurity: 'Abort Insufficient Security',
    abortSecurityError: 'Abort Security Error',
    duplicateEntry: 'Duplicate Entry',
    invalidValueInThisState: 'Invalid Value In This State',
    invalidOperationInThisState: 'Invalid Operation In This State',
    listItemNotNumbered: 'List Item Not Numbered',
    listItemNotTimestamped: 'List Item Not Timestamped',
    invalidDataEncoding: 'Invalid Data Encoding',
    bvlcFunctionUnknown: 'Bvlc Function Unknown',
    headerEncodingError: 'Header Encoding Error',
    headerNotUnderstood: 'Header Not Understood',
    messageIncomplete: 'Message Incomplete',
    notABacnetScHub: 'Not A BACnet SC Hub',
    payloadExpected: 'Payload Expected',
    unexpectedData: 'Unexpected Data',
    nodeDuplicateVmac: 'Node Duplicate VMAC',
    httpUnexpectedResponseCode: 'Http Unexpected Response Code',
    httpNoUpgrade: 'Http No Upgrade',
    httpResourceNotLocal: 'Http Resource Not Local',
    httpProxyAuthenticationFailed: 'Http Proxy Authentication Failed',
    httpResponseTimeout: 'Http Response Timeout',
    httpResponseSyntaxError: 'Http Response Syntax Error',
    httpResponseValueError: 'Http Response Value Error',
    httpResponseMissingHeader: 'Http Response Missing Header',
    httpWebsocketHeaderError: 'Http Websocket Header Error',
    httpUpgradeRequired: 'Http Upgrade Required',
    httpUpgradeError: 'Http Upgrade Error',
    httpTemporaryUnavailable: 'Http Temporary Unavailable',
    httpNotAServer: 'Http Not A Server',
    httpError: 'Http Error',
    websocketSchemeNotSupported: 'Websocket Scheme Not Supported',
    websocketUnknownControlMessage: 'Websocket Unknown Control Message',
    websocketCloseError: 'Websocket Close Error',
    websocketClosedByPeer: 'Websocket Closed By Peer',
    websocketEndpointLeaves: 'Websocket Endpoint Leaves',
    websocketProtocolError: 'Websocket Protocol Error',
    websocketDataNotAccepted: 'Websocket Data Not Accepted',
    websocketClosedAbnormally: 'Websocket Closed Abnormally',
    websocketDataInconsistent: 'Websocket Data Inconsistent',
    websocketDataAgainstPolicy: 'Websocket Data Against Policy',
    websocketFrameTooLong: 'Websocket Frame Too Long',
    websocketExtensionMissing: 'Websocket Extension Missing',
    websocketRequestUnavailable: 'Websocket Request Unavailable',
    websocketError: 'Websocket Error',
    tlsClientCertificateError: 'Tls Client Certificate Error',
    tlsServerCertificateError: 'Tls Server Certificate Error',
    tlsClientAuthenticationFailed: 'Tls Client Authentication Failed',
    tlsServerAuthenticationFailed: 'Tls Server Authentication Failed',
    tlsClientCertificateExpired: 'Tls Client Certificate Expired',
    tlsServerCertificateExpired: 'Tls Server Certificate Expired',
    tlsClientCertificateRevoked: 'Tls Client Certificate Revoked',
    tlsServerCertificateRevoked: 'Tls Server Certificate Revoked',
    tlsError: 'Tls Error',
    dnsUnavailable: 'DNS Unavailable',
    dnsNameResolutionFailed: 'DNS Name Resolution Failed',
    dnsResolverFailure: 'DNS Resolver Failure',
    dnsError: 'DNS Error',
    tcpConnectTimeout: 'Tcp Connect Timeout',
    tcpConnectionRefused: 'Tcp Connection Refused',
    tcpClosedByLocal: 'Tcp Closed By Local',
    tcpClosedOther: 'Tcp Closed Other',
    tcpError: 'Tcp Error',
    ipAddressNotReachable: 'IP Address Not Reachable',
    ipError: 'IP Error',
    certificateExpired: 'Certificate Expired',
    certificateInvalid: 'Certificate Invalid',
    certificateMalformed: 'Certificate Malformed',
    certificateRevoked: 'Certificate Revoked',
    unknownSecurityKey: 'Unknown Security Key',
    referencedPortInError: 'Referenced Port In Error',
    notEnabled: 'Not Enabled',
    adjustScopeRequired: 'Adjust Scope Required',
    authScopeRequired: 'Auth Scope Required',
    bindScopeRequired: 'Bind Scope Required',
    configScopeRequired: 'Config Scope Required',
    controlScopeRequired: 'Control Scope Required',
    extendedScopeRequired: 'Extended Scope Required',
    incorrectClient: 'Incorrect Client',
    installScopeRequired: 'Install Scope Required',
    insufficientScope: 'Insufficient Scope',
    noDefaultScope: 'No Default Scope',
    noPolicy: 'No Policy',
    revokedToken: 'Revoked Token',
    overrideScopeRequired: 'Override Scope Required',
    inactiveToken: 'Inactive Token',
    unknownAudience: 'Unknown Audience',
    unknownClient: 'Unknown Client',
    unknownScope: 'Unknown Scope',
    viewScopeRequired: 'View Scope Required',
    incorrectAudience: 'Incorrect Audience',
    incorrectClientOrigin: 'Incorrect Client Origin',
    invalidArraySize: 'Invalid Array Size',
    incorrectIssuer: 'Incorrect Issuer',
    invalidToken: 'Invalid Token',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Error Code $value';
}

/// BACnet abort reasons (BACnetAbortReason).
abstract final class BacnetAbortReason {
  /// Other.
  static const int other = 0;

  /// Buffer Overflow.
  static const int bufferOverflow = 1;

  /// Invalid APDU In This State.
  static const int invalidApduInThisState = 2;

  /// Preempted By Higher Priority Task.
  static const int preemptedByHigherPriorityTask = 3;

  /// Segmentation Not Supported.
  static const int segmentationNotSupported = 4;

  /// Security Error.
  static const int securityError = 5;

  /// Insufficient Security.
  static const int insufficientSecurity = 6;

  /// Window Size Out Of Range.
  static const int windowSizeOutOfRange = 7;

  /// Application Exceeded Reply Time.
  static const int applicationExceededReplyTime = 8;

  /// Out Of Resources.
  static const int outOfResources = 9;

  /// TSM Timeout.
  static const int tsmTimeout = 10;

  /// APDU Too Long.
  static const int apduTooLong = 11;

  static const Map<int, String> _labels = {
    other: 'Other',
    bufferOverflow: 'Buffer Overflow',
    invalidApduInThisState: 'Invalid APDU In This State',
    preemptedByHigherPriorityTask: 'Preempted By Higher Priority Task',
    segmentationNotSupported: 'Segmentation Not Supported',
    securityError: 'Security Error',
    insufficientSecurity: 'Insufficient Security',
    windowSizeOutOfRange: 'Window Size Out Of Range',
    applicationExceededReplyTime: 'Application Exceeded Reply Time',
    outOfResources: 'Out Of Resources',
    tsmTimeout: 'TSM Timeout',
    apduTooLong: 'APDU Too Long',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Abort Reason $value';
}

/// BACnet reject reasons (BACnetRejectReason).
abstract final class BacnetRejectReason {
  /// Other.
  static const int other = 0;

  /// Buffer Overflow.
  static const int bufferOverflow = 1;

  /// Inconsistent Parameters.
  static const int inconsistentParameters = 2;

  /// Invalid Parameter Data Type.
  static const int invalidParameterDataType = 3;

  /// Invalid Tag.
  static const int invalidTag = 4;

  /// Missing Required Parameter.
  static const int missingRequiredParameter = 5;

  /// Parameter Out Of Range.
  static const int parameterOutOfRange = 6;

  /// Too Many Arguments.
  static const int tooManyArguments = 7;

  /// Undefined Enumeration.
  static const int undefinedEnumeration = 8;

  /// Unrecognized Service.
  static const int unrecognizedService = 9;

  /// Invalid Data Encoding.
  static const int invalidDataEncoding = 10;

  static const Map<int, String> _labels = {
    other: 'Other',
    bufferOverflow: 'Buffer Overflow',
    inconsistentParameters: 'Inconsistent Parameters',
    invalidParameterDataType: 'Invalid Parameter Data Type',
    invalidTag: 'Invalid Tag',
    missingRequiredParameter: 'Missing Required Parameter',
    parameterOutOfRange: 'Parameter Out Of Range',
    tooManyArguments: 'Too Many Arguments',
    undefinedEnumeration: 'Undefined Enumeration',
    unrecognizedService: 'Unrecognized Service',
    invalidDataEncoding: 'Invalid Data Encoding',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Reject Reason $value';
}
