// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet error classes (BACnetErrorClass).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetErrorClass(value)`.
extension type const BacnetErrorClass(int value) implements int {
  /// Device.
  static const device = BacnetErrorClass(0);

  /// Object.
  static const object = BacnetErrorClass(1);

  /// Property.
  static const property = BacnetErrorClass(2);

  /// Resources.
  static const resources = BacnetErrorClass(3);

  /// Security.
  static const security = BacnetErrorClass(4);

  /// Services.
  static const services = BacnetErrorClass(5);

  /// VT.
  static const vt = BacnetErrorClass(6);

  /// Communication.
  static const communication = BacnetErrorClass(7);

  static const Map<BacnetErrorClass, String> _labels = {
    device: 'Device',
    object: 'Object',
    property: 'Property',
    resources: 'Resources',
    security: 'Security',
    services: 'Services',
    vt: 'VT',
    communication: 'Communication',
  };

  /// All values defined by this library.
  static Iterable<BacnetErrorClass> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) =>
      _labels[value] ?? 'Unknown Class ($value)';

  /// Human readable name of this value.
  String get label => getName(value);
}

/// BACnet error codes (BACnetErrorCode).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetErrorCode(value)`.
extension type const BacnetErrorCode(int value) implements int {
  /// Other.
  static const other = BacnetErrorCode(0);

  /// Authentication Failed.
  static const authenticationFailed = BacnetErrorCode(1);

  /// Configuration In Progress.
  static const configurationInProgress = BacnetErrorCode(2);

  /// Device Busy.
  static const deviceBusy = BacnetErrorCode(3);

  /// Dynamic Creation Not Supported.
  static const dynamicCreationNotSupported = BacnetErrorCode(4);

  /// File Access Denied.
  static const fileAccessDenied = BacnetErrorCode(5);

  /// Incompatible Security Levels.
  static const incompatibleSecurityLevels = BacnetErrorCode(6);

  /// Inconsistent Parameters.
  static const inconsistentParameters = BacnetErrorCode(7);

  /// Inconsistent Selection Criterion.
  static const inconsistentSelectionCriterion = BacnetErrorCode(8);

  /// Invalid Data Type.
  static const invalidDataType = BacnetErrorCode(9);

  /// Invalid File Access Method.
  static const invalidFileAccessMethod = BacnetErrorCode(10);

  /// Invalid File Start Position.
  static const invalidFileStartPosition = BacnetErrorCode(11);

  /// Invalid Operator Name.
  static const invalidOperatorName = BacnetErrorCode(12);

  /// Invalid Parameter Data Type.
  static const invalidParameterDataType = BacnetErrorCode(13);

  /// Invalid Time Stamp.
  static const invalidTimeStamp = BacnetErrorCode(14);

  /// Key Generation Error.
  static const keyGeneration = BacnetErrorCode(15);

  /// Missing Required Parameter.
  static const missingRequiredParameter = BacnetErrorCode(16);

  /// No Objects Of Specified Type.
  static const noObjectsOfSpecifiedType = BacnetErrorCode(17);

  /// No Space For Object.
  static const noSpaceForObject = BacnetErrorCode(18);

  /// No Space To Add List Element.
  static const noSpaceToAddListElement = BacnetErrorCode(19);

  /// No Space To Write Property.
  static const noSpaceToWriteProperty = BacnetErrorCode(20);

  /// No VT Sessions Available.
  static const noVtSessionsAvailable = BacnetErrorCode(21);

  /// Property Is Not A List.
  static const propertyIsNotAList = BacnetErrorCode(22);

  /// Object Deletion Not Permitted.
  static const objectDeletionNotPermitted = BacnetErrorCode(23);

  /// Object Identifier Already Exists.
  static const objectIdentifierAlreadyExists = BacnetErrorCode(24);

  /// Operational Problem.
  static const operationalProblem = BacnetErrorCode(25);

  /// Password Failure.
  static const passwordFailure = BacnetErrorCode(26);

  /// Read Access Denied.
  static const readAccessDenied = BacnetErrorCode(27);

  /// Security Not Supported.
  static const securityNotSupported = BacnetErrorCode(28);

  /// Service Request Denied.
  static const serviceRequestDenied = BacnetErrorCode(29);

  /// Timeout.
  static const timeout = BacnetErrorCode(30);

  /// Unknown Object.
  static const unknownObject = BacnetErrorCode(31);

  /// Unknown Property.
  static const unknownProperty = BacnetErrorCode(32);

  /// Unknown VT Class.
  static const unknownVtClass = BacnetErrorCode(34);

  /// Unknown VT Session.
  static const unknownVtSession = BacnetErrorCode(35);

  /// Unsupported Object Type.
  static const unsupportedObjectType = BacnetErrorCode(36);

  /// Value Out Of Range.
  static const valueOutOfRange = BacnetErrorCode(37);

  /// VT Session Already Closed.
  static const vtSessionAlreadyClosed = BacnetErrorCode(38);

  /// VT Session Termination Failure.
  static const vtSessionTerminationFailure = BacnetErrorCode(39);

  /// Write Access Denied.
  static const writeAccessDenied = BacnetErrorCode(40);

  /// Character Set Not Supported.
  static const characterSetNotSupported = BacnetErrorCode(41);

  /// Invalid Array Index.
  static const invalidArrayIndex = BacnetErrorCode(42);

  /// COV Subscription Failed.
  static const covSubscriptionFailed = BacnetErrorCode(43);

  /// Not COV Property.
  static const notCovProperty = BacnetErrorCode(44);

  /// Optional Functionality Not Supported.
  static const optionalFunctionalityNotSupported = BacnetErrorCode(45);

  /// Invalid Configuration Data.
  static const invalidConfigurationData = BacnetErrorCode(46);

  /// Datatype Not Supported.
  static const datatypeNotSupported = BacnetErrorCode(47);

  /// Duplicate Name.
  static const duplicateName = BacnetErrorCode(48);

  /// Duplicate Object ID.
  static const duplicateObjectId = BacnetErrorCode(49);

  /// Property Is Not An Array.
  static const propertyIsNotAnArray = BacnetErrorCode(50);

  /// Abort Buffer Overflow.
  static const abortBufferOverflow = BacnetErrorCode(51);

  /// Abort Invalid APDU In This State.
  static const abortInvalidApduInThisState = BacnetErrorCode(52);

  /// Abort Preempted By Higher Priority Task.
  static const abortPreemptedByHigherPriorityTask = BacnetErrorCode(53);

  /// Abort Segmentation Not Supported.
  static const abortSegmentationNotSupported = BacnetErrorCode(54);

  /// Abort Other.
  static const abortOther = BacnetErrorCode(56);

  /// Invalid Tag.
  static const invalidTag = BacnetErrorCode(57);

  /// Network Down.
  static const networkDown = BacnetErrorCode(58);

  /// Reject Buffer Overflow.
  static const rejectBufferOverflow = BacnetErrorCode(59);

  /// Reject Inconsistent Parameters.
  static const rejectInconsistentParameters = BacnetErrorCode(60);

  /// Reject Invalid Parameter Data Type.
  static const rejectInvalidParameterDataType = BacnetErrorCode(61);

  /// Reject Invalid Tag.
  static const rejectInvalidTag = BacnetErrorCode(62);

  /// Reject Missing Required Parameter.
  static const rejectMissingRequiredParameter = BacnetErrorCode(63);

  /// Reject Parameter Out Of Range.
  static const rejectParameterOutOfRange = BacnetErrorCode(64);

  /// Reject Too Many Arguments.
  static const rejectTooManyArguments = BacnetErrorCode(65);

  /// Reject Undefined Enumeration.
  static const rejectUndefinedEnumeration = BacnetErrorCode(66);

  /// Reject Unrecognized Service.
  static const rejectUnrecognizedService = BacnetErrorCode(67);

  /// Reject Other.
  static const rejectOther = BacnetErrorCode(69);

  /// Unknown Device.
  static const unknownDevice = BacnetErrorCode(70);

  /// Unknown Route.
  static const unknownRoute = BacnetErrorCode(71);

  /// Value Not Initialized.
  static const valueNotInitialized = BacnetErrorCode(72);

  /// Invalid Event State.
  static const invalidEventState = BacnetErrorCode(73);

  /// No Alarm Configured.
  static const noAlarmConfigured = BacnetErrorCode(74);

  /// Log Buffer Full.
  static const logBufferFull = BacnetErrorCode(75);

  /// Logged Value Purged.
  static const loggedValuePurged = BacnetErrorCode(76);

  /// No Property Specified.
  static const noPropertySpecified = BacnetErrorCode(77);

  /// Not Configured For Triggered Logging.
  static const notConfiguredForTriggeredLogging = BacnetErrorCode(78);

  /// Unknown Subscription.
  static const unknownSubscription = BacnetErrorCode(79);

  /// Parameter Out Of Range.
  static const parameterOutOfRange = BacnetErrorCode(80);

  /// List Element Not Found.
  static const listElementNotFound = BacnetErrorCode(81);

  /// Busy.
  static const busy = BacnetErrorCode(82);

  /// Communication Disabled.
  static const communicationDisabled = BacnetErrorCode(83);

  /// Success.
  static const success = BacnetErrorCode(84);

  /// Access Denied.
  static const accessDenied = BacnetErrorCode(85);

  /// Bad Destination Address.
  static const badDestinationAddress = BacnetErrorCode(86);

  /// Bad Destination Device ID.
  static const badDestinationDeviceId = BacnetErrorCode(87);

  /// Bad Signature.
  static const badSignature = BacnetErrorCode(88);

  /// Bad Source Address.
  static const badSourceAddress = BacnetErrorCode(89);

  /// Bad Timestamp.
  static const badTimestamp = BacnetErrorCode(90);

  /// Cannot Use Key.
  static const cannotUseKey = BacnetErrorCode(91);

  /// Cannot Verify Message ID.
  static const cannotVerifyMessageId = BacnetErrorCode(92);

  /// Correct Key Revision.
  static const correctKeyRevision = BacnetErrorCode(93);

  /// Destination Device ID Required.
  static const destinationDeviceIdRequired = BacnetErrorCode(94);

  /// Duplicate Message.
  static const duplicateMessage = BacnetErrorCode(95);

  /// Encryption Not Configured.
  static const encryptionNotConfigured = BacnetErrorCode(96);

  /// Encryption Required.
  static const encryptionRequired = BacnetErrorCode(97);

  /// Incorrect Key.
  static const incorrectKey = BacnetErrorCode(98);

  /// Invalid Key Data.
  static const invalidKeyData = BacnetErrorCode(99);

  /// Key Update In Progress.
  static const keyUpdateInProgress = BacnetErrorCode(100);

  /// Malformed Message.
  static const malformedMessage = BacnetErrorCode(101);

  /// Not Key Server.
  static const notKeyServer = BacnetErrorCode(102);

  /// Security Not Configured.
  static const securityNotConfigured = BacnetErrorCode(103);

  /// Source Security Required.
  static const sourceSecurityRequired = BacnetErrorCode(104);

  /// Too Many Keys.
  static const tooManyKeys = BacnetErrorCode(105);

  /// Unknown Authentication Type.
  static const unknownAuthenticationType = BacnetErrorCode(106);

  /// Unknown Key.
  static const unknownKey = BacnetErrorCode(107);

  /// Unknown Key Revision.
  static const unknownKeyRevision = BacnetErrorCode(108);

  /// Unknown Source Message.
  static const unknownSourceMessage = BacnetErrorCode(109);

  /// Not Router To Dnet.
  static const notRouterToDnet = BacnetErrorCode(110);

  /// Router Busy.
  static const routerBusy = BacnetErrorCode(111);

  /// Unknown Network Message.
  static const unknownNetworkMessage = BacnetErrorCode(112);

  /// Message Too Long.
  static const messageTooLong = BacnetErrorCode(113);

  /// Security Error.
  static const securityError = BacnetErrorCode(114);

  /// Addressing Error.
  static const addressingError = BacnetErrorCode(115);

  /// Write Bdt Failed.
  static const writeBdtFailed = BacnetErrorCode(116);

  /// Read Bdt Failed.
  static const readBdtFailed = BacnetErrorCode(117);

  /// Register Foreign Device Failed.
  static const registerForeignDeviceFailed = BacnetErrorCode(118);

  /// Read Fdt Failed.
  static const readFdtFailed = BacnetErrorCode(119);

  /// Delete Fdt Entry Failed.
  static const deleteFdtEntryFailed = BacnetErrorCode(120);

  /// Distribute Broadcast Failed.
  static const distributeBroadcastFailed = BacnetErrorCode(121);

  /// Unknown File Size.
  static const unknownFileSize = BacnetErrorCode(122);

  /// Abort APDU Too Long.
  static const abortApduTooLong = BacnetErrorCode(123);

  /// Abort Application Exceeded Reply Time.
  static const abortApplicationExceededReplyTime = BacnetErrorCode(124);

  /// Abort Out Of Resources.
  static const abortOutOfResources = BacnetErrorCode(125);

  /// Abort TSM Timeout.
  static const abortTsmTimeout = BacnetErrorCode(126);

  /// Abort Window Size Out Of Range.
  static const abortWindowSizeOutOfRange = BacnetErrorCode(127);

  /// File Full.
  static const fileFull = BacnetErrorCode(128);

  /// Inconsistent Configuration.
  static const inconsistentConfiguration = BacnetErrorCode(129);

  /// Inconsistent Object Type.
  static const inconsistentObjectType = BacnetErrorCode(130);

  /// Internal Error.
  static const internalError = BacnetErrorCode(131);

  /// Not Configured.
  static const notConfigured = BacnetErrorCode(132);

  /// Out Of Memory.
  static const outOfMemory = BacnetErrorCode(133);

  /// Value Too Long.
  static const valueTooLong = BacnetErrorCode(134);

  /// Abort Insufficient Security.
  static const abortInsufficientSecurity = BacnetErrorCode(135);

  /// Abort Security Error.
  static const abortSecurityError = BacnetErrorCode(136);

  /// Duplicate Entry.
  static const duplicateEntry = BacnetErrorCode(137);

  /// Invalid Value In This State.
  static const invalidValueInThisState = BacnetErrorCode(138);

  /// Invalid Operation In This State.
  static const invalidOperationInThisState = BacnetErrorCode(139);

  /// List Item Not Numbered.
  static const listItemNotNumbered = BacnetErrorCode(140);

  /// List Item Not Timestamped.
  static const listItemNotTimestamped = BacnetErrorCode(141);

  /// Invalid Data Encoding.
  static const invalidDataEncoding = BacnetErrorCode(142);

  /// Bvlc Function Unknown.
  static const bvlcFunctionUnknown = BacnetErrorCode(143);

  /// Header Encoding Error.
  static const headerEncodingError = BacnetErrorCode(145);

  /// Header Not Understood.
  static const headerNotUnderstood = BacnetErrorCode(146);

  /// Message Incomplete.
  static const messageIncomplete = BacnetErrorCode(147);

  /// Not A BACnet SC Hub.
  static const notABacnetScHub = BacnetErrorCode(148);

  /// Payload Expected.
  static const payloadExpected = BacnetErrorCode(149);

  /// Unexpected Data.
  static const unexpectedData = BacnetErrorCode(150);

  /// Node Duplicate VMAC.
  static const nodeDuplicateVmac = BacnetErrorCode(151);

  /// Http Unexpected Response Code.
  static const httpUnexpectedResponseCode = BacnetErrorCode(152);

  /// Http No Upgrade.
  static const httpNoUpgrade = BacnetErrorCode(153);

  /// Http Resource Not Local.
  static const httpResourceNotLocal = BacnetErrorCode(154);

  /// Http Proxy Authentication Failed.
  static const httpProxyAuthenticationFailed = BacnetErrorCode(155);

  /// Http Response Timeout.
  static const httpResponseTimeout = BacnetErrorCode(156);

  /// Http Response Syntax Error.
  static const httpResponseSyntaxError = BacnetErrorCode(157);

  /// Http Response Value Error.
  static const httpResponseValueError = BacnetErrorCode(158);

  /// Http Response Missing Header.
  static const httpResponseMissingHeader = BacnetErrorCode(159);

  /// Http Websocket Header Error.
  static const httpWebsocketHeaderError = BacnetErrorCode(160);

  /// Http Upgrade Required.
  static const httpUpgradeRequired = BacnetErrorCode(161);

  /// Http Upgrade Error.
  static const httpUpgradeError = BacnetErrorCode(162);

  /// Http Temporary Unavailable.
  static const httpTemporaryUnavailable = BacnetErrorCode(163);

  /// Http Not A Server.
  static const httpNotAServer = BacnetErrorCode(164);

  /// Http Error.
  static const httpError = BacnetErrorCode(165);

  /// Websocket Scheme Not Supported.
  static const websocketSchemeNotSupported = BacnetErrorCode(166);

  /// Websocket Unknown Control Message.
  static const websocketUnknownControlMessage = BacnetErrorCode(167);

  /// Websocket Close Error.
  static const websocketCloseError = BacnetErrorCode(168);

  /// Websocket Closed By Peer.
  static const websocketClosedByPeer = BacnetErrorCode(169);

  /// Websocket Endpoint Leaves.
  static const websocketEndpointLeaves = BacnetErrorCode(170);

  /// Websocket Protocol Error.
  static const websocketProtocolError = BacnetErrorCode(171);

  /// Websocket Data Not Accepted.
  static const websocketDataNotAccepted = BacnetErrorCode(172);

  /// Websocket Closed Abnormally.
  static const websocketClosedAbnormally = BacnetErrorCode(173);

  /// Websocket Data Inconsistent.
  static const websocketDataInconsistent = BacnetErrorCode(174);

  /// Websocket Data Against Policy.
  static const websocketDataAgainstPolicy = BacnetErrorCode(175);

  /// Websocket Frame Too Long.
  static const websocketFrameTooLong = BacnetErrorCode(176);

  /// Websocket Extension Missing.
  static const websocketExtensionMissing = BacnetErrorCode(177);

  /// Websocket Request Unavailable.
  static const websocketRequestUnavailable = BacnetErrorCode(178);

  /// Websocket Error.
  static const websocketError = BacnetErrorCode(179);

  /// Tls Client Certificate Error.
  static const tlsClientCertificateError = BacnetErrorCode(180);

  /// Tls Server Certificate Error.
  static const tlsServerCertificateError = BacnetErrorCode(181);

  /// Tls Client Authentication Failed.
  static const tlsClientAuthenticationFailed = BacnetErrorCode(182);

  /// Tls Server Authentication Failed.
  static const tlsServerAuthenticationFailed = BacnetErrorCode(183);

  /// Tls Client Certificate Expired.
  static const tlsClientCertificateExpired = BacnetErrorCode(184);

  /// Tls Server Certificate Expired.
  static const tlsServerCertificateExpired = BacnetErrorCode(185);

  /// Tls Client Certificate Revoked.
  static const tlsClientCertificateRevoked = BacnetErrorCode(186);

  /// Tls Server Certificate Revoked.
  static const tlsServerCertificateRevoked = BacnetErrorCode(187);

  /// Tls Error.
  static const tlsError = BacnetErrorCode(188);

  /// DNS Unavailable.
  static const dnsUnavailable = BacnetErrorCode(189);

  /// DNS Name Resolution Failed.
  static const dnsNameResolutionFailed = BacnetErrorCode(190);

  /// DNS Resolver Failure.
  static const dnsResolverFailure = BacnetErrorCode(191);

  /// DNS Error.
  static const dnsError = BacnetErrorCode(192);

  /// Tcp Connect Timeout.
  static const tcpConnectTimeout = BacnetErrorCode(193);

  /// Tcp Connection Refused.
  static const tcpConnectionRefused = BacnetErrorCode(194);

  /// Tcp Closed By Local.
  static const tcpClosedByLocal = BacnetErrorCode(195);

  /// Tcp Closed Other.
  static const tcpClosedOther = BacnetErrorCode(196);

  /// Tcp Error.
  static const tcpError = BacnetErrorCode(197);

  /// IP Address Not Reachable.
  static const ipAddressNotReachable = BacnetErrorCode(198);

  /// IP Error.
  static const ipError = BacnetErrorCode(199);

  /// Certificate Expired.
  static const certificateExpired = BacnetErrorCode(200);

  /// Certificate Invalid.
  static const certificateInvalid = BacnetErrorCode(201);

  /// Certificate Malformed.
  static const certificateMalformed = BacnetErrorCode(202);

  /// Certificate Revoked.
  static const certificateRevoked = BacnetErrorCode(203);

  /// Unknown Security Key.
  static const unknownSecurityKey = BacnetErrorCode(204);

  /// Referenced Port In Error.
  static const referencedPortInError = BacnetErrorCode(205);

  /// Not Enabled.
  static const notEnabled = BacnetErrorCode(206);

  /// Adjust Scope Required.
  static const adjustScopeRequired = BacnetErrorCode(207);

  /// Auth Scope Required.
  static const authScopeRequired = BacnetErrorCode(208);

  /// Bind Scope Required.
  static const bindScopeRequired = BacnetErrorCode(209);

  /// Config Scope Required.
  static const configScopeRequired = BacnetErrorCode(210);

  /// Control Scope Required.
  static const controlScopeRequired = BacnetErrorCode(211);

  /// Extended Scope Required.
  static const extendedScopeRequired = BacnetErrorCode(212);

  /// Incorrect Client.
  static const incorrectClient = BacnetErrorCode(213);

  /// Install Scope Required.
  static const installScopeRequired = BacnetErrorCode(214);

  /// Insufficient Scope.
  static const insufficientScope = BacnetErrorCode(215);

  /// No Default Scope.
  static const noDefaultScope = BacnetErrorCode(216);

  /// No Policy.
  static const noPolicy = BacnetErrorCode(217);

  /// Revoked Token.
  static const revokedToken = BacnetErrorCode(218);

  /// Override Scope Required.
  static const overrideScopeRequired = BacnetErrorCode(219);

  /// Inactive Token.
  static const inactiveToken = BacnetErrorCode(220);

  /// Unknown Audience.
  static const unknownAudience = BacnetErrorCode(221);

  /// Unknown Client.
  static const unknownClient = BacnetErrorCode(222);

  /// Unknown Scope.
  static const unknownScope = BacnetErrorCode(223);

  /// View Scope Required.
  static const viewScopeRequired = BacnetErrorCode(224);

  /// Incorrect Audience.
  static const incorrectAudience = BacnetErrorCode(225);

  /// Incorrect Client Origin.
  static const incorrectClientOrigin = BacnetErrorCode(226);

  /// Invalid Array Size.
  static const invalidArraySize = BacnetErrorCode(227);

  /// Incorrect Issuer.
  static const incorrectIssuer = BacnetErrorCode(228);

  /// Invalid Token.
  static const invalidToken = BacnetErrorCode(229);

  static const Map<BacnetErrorCode, String> _labels = {
    other: 'Other',
    authenticationFailed: 'Authentication Failed',
    configurationInProgress: 'Configuration In Progress',
    deviceBusy: 'Device Busy',
    dynamicCreationNotSupported: 'Dynamic Creation Not Supported',
    fileAccessDenied: 'File Access Denied',
    incompatibleSecurityLevels: 'Incompatible Security Levels',
    inconsistentParameters: 'Inconsistent Parameters',
    inconsistentSelectionCriterion: 'Inconsistent Selection Criterion',
    invalidDataType: 'Invalid Data Type',
    invalidFileAccessMethod: 'Invalid File Access Method',
    invalidFileStartPosition: 'Invalid File Start Position',
    invalidOperatorName: 'Invalid Operator Name',
    invalidParameterDataType: 'Invalid Parameter Data Type',
    invalidTimeStamp: 'Invalid Time Stamp',
    keyGeneration: 'Key Generation Error',
    missingRequiredParameter: 'Missing Required Parameter',
    noObjectsOfSpecifiedType: 'No Objects Of Specified Type',
    noSpaceForObject: 'No Space For Object',
    noSpaceToAddListElement: 'No Space To Add List Element',
    noSpaceToWriteProperty: 'No Space To Write Property',
    noVtSessionsAvailable: 'No VT Sessions Available',
    propertyIsNotAList: 'Property Is Not A List',
    objectDeletionNotPermitted: 'Object Deletion Not Permitted',
    objectIdentifierAlreadyExists: 'Object Identifier Already Exists',
    operationalProblem: 'Operational Problem',
    passwordFailure: 'Password Failure',
    readAccessDenied: 'Read Access Denied',
    securityNotSupported: 'Security Not Supported',
    serviceRequestDenied: 'Service Request Denied',
    timeout: 'Timeout',
    unknownObject: 'Unknown Object',
    unknownProperty: 'Unknown Property',
    unknownVtClass: 'Unknown VT Class',
    unknownVtSession: 'Unknown VT Session',
    unsupportedObjectType: 'Unsupported Object Type',
    valueOutOfRange: 'Value Out Of Range',
    vtSessionAlreadyClosed: 'VT Session Already Closed',
    vtSessionTerminationFailure: 'VT Session Termination Failure',
    writeAccessDenied: 'Write Access Denied',
    characterSetNotSupported: 'Character Set Not Supported',
    invalidArrayIndex: 'Invalid Array Index',
    covSubscriptionFailed: 'COV Subscription Failed',
    notCovProperty: 'Not COV Property',
    optionalFunctionalityNotSupported: 'Optional Functionality Not Supported',
    invalidConfigurationData: 'Invalid Configuration Data',
    datatypeNotSupported: 'Datatype Not Supported',
    duplicateName: 'Duplicate Name',
    duplicateObjectId: 'Duplicate Object ID',
    propertyIsNotAnArray: 'Property Is Not An Array',
    abortBufferOverflow: 'Abort Buffer Overflow',
    abortInvalidApduInThisState: 'Abort Invalid APDU In This State',
    abortPreemptedByHigherPriorityTask:
        'Abort Preempted By Higher Priority Task',
    abortSegmentationNotSupported: 'Abort Segmentation Not Supported',
    abortOther: 'Abort Other',
    invalidTag: 'Invalid Tag',
    networkDown: 'Network Down',
    rejectBufferOverflow: 'Reject Buffer Overflow',
    rejectInconsistentParameters: 'Reject Inconsistent Parameters',
    rejectInvalidParameterDataType: 'Reject Invalid Parameter Data Type',
    rejectInvalidTag: 'Reject Invalid Tag',
    rejectMissingRequiredParameter: 'Reject Missing Required Parameter',
    rejectParameterOutOfRange: 'Reject Parameter Out Of Range',
    rejectTooManyArguments: 'Reject Too Many Arguments',
    rejectUndefinedEnumeration: 'Reject Undefined Enumeration',
    rejectUnrecognizedService: 'Reject Unrecognized Service',
    rejectOther: 'Reject Other',
    unknownDevice: 'Unknown Device',
    unknownRoute: 'Unknown Route',
    valueNotInitialized: 'Value Not Initialized',
    invalidEventState: 'Invalid Event State',
    noAlarmConfigured: 'No Alarm Configured',
    logBufferFull: 'Log Buffer Full',
    loggedValuePurged: 'Logged Value Purged',
    noPropertySpecified: 'No Property Specified',
    notConfiguredForTriggeredLogging: 'Not Configured For Triggered Logging',
    unknownSubscription: 'Unknown Subscription',
    parameterOutOfRange: 'Parameter Out Of Range',
    listElementNotFound: 'List Element Not Found',
    busy: 'Busy',
    communicationDisabled: 'Communication Disabled',
    success: 'Success',
    accessDenied: 'Access Denied',
    badDestinationAddress: 'Bad Destination Address',
    badDestinationDeviceId: 'Bad Destination Device ID',
    badSignature: 'Bad Signature',
    badSourceAddress: 'Bad Source Address',
    badTimestamp: 'Bad Timestamp',
    cannotUseKey: 'Cannot Use Key',
    cannotVerifyMessageId: 'Cannot Verify Message ID',
    correctKeyRevision: 'Correct Key Revision',
    destinationDeviceIdRequired: 'Destination Device ID Required',
    duplicateMessage: 'Duplicate Message',
    encryptionNotConfigured: 'Encryption Not Configured',
    encryptionRequired: 'Encryption Required',
    incorrectKey: 'Incorrect Key',
    invalidKeyData: 'Invalid Key Data',
    keyUpdateInProgress: 'Key Update In Progress',
    malformedMessage: 'Malformed Message',
    notKeyServer: 'Not Key Server',
    securityNotConfigured: 'Security Not Configured',
    sourceSecurityRequired: 'Source Security Required',
    tooManyKeys: 'Too Many Keys',
    unknownAuthenticationType: 'Unknown Authentication Type',
    unknownKey: 'Unknown Key',
    unknownKeyRevision: 'Unknown Key Revision',
    unknownSourceMessage: 'Unknown Source Message',
    notRouterToDnet: 'Not Router To Dnet',
    routerBusy: 'Router Busy',
    unknownNetworkMessage: 'Unknown Network Message',
    messageTooLong: 'Message Too Long',
    securityError: 'Security Error',
    addressingError: 'Addressing Error',
    writeBdtFailed: 'Write Bdt Failed',
    readBdtFailed: 'Read Bdt Failed',
    registerForeignDeviceFailed: 'Register Foreign Device Failed',
    readFdtFailed: 'Read Fdt Failed',
    deleteFdtEntryFailed: 'Delete Fdt Entry Failed',
    distributeBroadcastFailed: 'Distribute Broadcast Failed',
    unknownFileSize: 'Unknown File Size',
    abortApduTooLong: 'Abort APDU Too Long',
    abortApplicationExceededReplyTime: 'Abort Application Exceeded Reply Time',
    abortOutOfResources: 'Abort Out Of Resources',
    abortTsmTimeout: 'Abort TSM Timeout',
    abortWindowSizeOutOfRange: 'Abort Window Size Out Of Range',
    fileFull: 'File Full',
    inconsistentConfiguration: 'Inconsistent Configuration',
    inconsistentObjectType: 'Inconsistent Object Type',
    internalError: 'Internal Error',
    notConfigured: 'Not Configured',
    outOfMemory: 'Out Of Memory',
    valueTooLong: 'Value Too Long',
    abortInsufficientSecurity: 'Abort Insufficient Security',
    abortSecurityError: 'Abort Security Error',
    duplicateEntry: 'Duplicate Entry',
    invalidValueInThisState: 'Invalid Value In This State',
    invalidOperationInThisState: 'Invalid Operation In This State',
    listItemNotNumbered: 'List Item Not Numbered',
    listItemNotTimestamped: 'List Item Not Timestamped',
    invalidDataEncoding: 'Invalid Data Encoding',
    bvlcFunctionUnknown: 'Bvlc Function Unknown',
    headerEncodingError: 'Header Encoding Error',
    headerNotUnderstood: 'Header Not Understood',
    messageIncomplete: 'Message Incomplete',
    notABacnetScHub: 'Not A BACnet SC Hub',
    payloadExpected: 'Payload Expected',
    unexpectedData: 'Unexpected Data',
    nodeDuplicateVmac: 'Node Duplicate VMAC',
    httpUnexpectedResponseCode: 'Http Unexpected Response Code',
    httpNoUpgrade: 'Http No Upgrade',
    httpResourceNotLocal: 'Http Resource Not Local',
    httpProxyAuthenticationFailed: 'Http Proxy Authentication Failed',
    httpResponseTimeout: 'Http Response Timeout',
    httpResponseSyntaxError: 'Http Response Syntax Error',
    httpResponseValueError: 'Http Response Value Error',
    httpResponseMissingHeader: 'Http Response Missing Header',
    httpWebsocketHeaderError: 'Http Websocket Header Error',
    httpUpgradeRequired: 'Http Upgrade Required',
    httpUpgradeError: 'Http Upgrade Error',
    httpTemporaryUnavailable: 'Http Temporary Unavailable',
    httpNotAServer: 'Http Not A Server',
    httpError: 'Http Error',
    websocketSchemeNotSupported: 'Websocket Scheme Not Supported',
    websocketUnknownControlMessage: 'Websocket Unknown Control Message',
    websocketCloseError: 'Websocket Close Error',
    websocketClosedByPeer: 'Websocket Closed By Peer',
    websocketEndpointLeaves: 'Websocket Endpoint Leaves',
    websocketProtocolError: 'Websocket Protocol Error',
    websocketDataNotAccepted: 'Websocket Data Not Accepted',
    websocketClosedAbnormally: 'Websocket Closed Abnormally',
    websocketDataInconsistent: 'Websocket Data Inconsistent',
    websocketDataAgainstPolicy: 'Websocket Data Against Policy',
    websocketFrameTooLong: 'Websocket Frame Too Long',
    websocketExtensionMissing: 'Websocket Extension Missing',
    websocketRequestUnavailable: 'Websocket Request Unavailable',
    websocketError: 'Websocket Error',
    tlsClientCertificateError: 'Tls Client Certificate Error',
    tlsServerCertificateError: 'Tls Server Certificate Error',
    tlsClientAuthenticationFailed: 'Tls Client Authentication Failed',
    tlsServerAuthenticationFailed: 'Tls Server Authentication Failed',
    tlsClientCertificateExpired: 'Tls Client Certificate Expired',
    tlsServerCertificateExpired: 'Tls Server Certificate Expired',
    tlsClientCertificateRevoked: 'Tls Client Certificate Revoked',
    tlsServerCertificateRevoked: 'Tls Server Certificate Revoked',
    tlsError: 'Tls Error',
    dnsUnavailable: 'DNS Unavailable',
    dnsNameResolutionFailed: 'DNS Name Resolution Failed',
    dnsResolverFailure: 'DNS Resolver Failure',
    dnsError: 'DNS Error',
    tcpConnectTimeout: 'Tcp Connect Timeout',
    tcpConnectionRefused: 'Tcp Connection Refused',
    tcpClosedByLocal: 'Tcp Closed By Local',
    tcpClosedOther: 'Tcp Closed Other',
    tcpError: 'Tcp Error',
    ipAddressNotReachable: 'IP Address Not Reachable',
    ipError: 'IP Error',
    certificateExpired: 'Certificate Expired',
    certificateInvalid: 'Certificate Invalid',
    certificateMalformed: 'Certificate Malformed',
    certificateRevoked: 'Certificate Revoked',
    unknownSecurityKey: 'Unknown Security Key',
    referencedPortInError: 'Referenced Port In Error',
    notEnabled: 'Not Enabled',
    adjustScopeRequired: 'Adjust Scope Required',
    authScopeRequired: 'Auth Scope Required',
    bindScopeRequired: 'Bind Scope Required',
    configScopeRequired: 'Config Scope Required',
    controlScopeRequired: 'Control Scope Required',
    extendedScopeRequired: 'Extended Scope Required',
    incorrectClient: 'Incorrect Client',
    installScopeRequired: 'Install Scope Required',
    insufficientScope: 'Insufficient Scope',
    noDefaultScope: 'No Default Scope',
    noPolicy: 'No Policy',
    revokedToken: 'Revoked Token',
    overrideScopeRequired: 'Override Scope Required',
    inactiveToken: 'Inactive Token',
    unknownAudience: 'Unknown Audience',
    unknownClient: 'Unknown Client',
    unknownScope: 'Unknown Scope',
    viewScopeRequired: 'View Scope Required',
    incorrectAudience: 'Incorrect Audience',
    incorrectClientOrigin: 'Incorrect Client Origin',
    invalidArraySize: 'Invalid Array Size',
    incorrectIssuer: 'Incorrect Issuer',
    invalidToken: 'Invalid Token',
  };

  /// All values defined by this library.
  static Iterable<BacnetErrorCode> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Error Code $value';

  /// Human readable name of this value.
  String get label => getName(value);
}

/// BACnet abort reasons (BACnetAbortReason).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetAbortReason(value)`.
extension type const BacnetAbortReason(int value) implements int {
  /// Other.
  static const other = BacnetAbortReason(0);

  /// Buffer Overflow.
  static const bufferOverflow = BacnetAbortReason(1);

  /// Invalid APDU In This State.
  static const invalidApduInThisState = BacnetAbortReason(2);

  /// Preempted By Higher Priority Task.
  static const preemptedByHigherPriorityTask = BacnetAbortReason(3);

  /// Segmentation Not Supported.
  static const segmentationNotSupported = BacnetAbortReason(4);

  /// Security Error.
  static const securityError = BacnetAbortReason(5);

  /// Insufficient Security.
  static const insufficientSecurity = BacnetAbortReason(6);

  /// Window Size Out Of Range.
  static const windowSizeOutOfRange = BacnetAbortReason(7);

  /// Application Exceeded Reply Time.
  static const applicationExceededReplyTime = BacnetAbortReason(8);

  /// Out Of Resources.
  static const outOfResources = BacnetAbortReason(9);

  /// TSM Timeout.
  static const tsmTimeout = BacnetAbortReason(10);

  /// APDU Too Long.
  static const apduTooLong = BacnetAbortReason(11);

  static const Map<BacnetAbortReason, String> _labels = {
    other: 'Other',
    bufferOverflow: 'Buffer Overflow',
    invalidApduInThisState: 'Invalid APDU In This State',
    preemptedByHigherPriorityTask: 'Preempted By Higher Priority Task',
    segmentationNotSupported: 'Segmentation Not Supported',
    securityError: 'Security Error',
    insufficientSecurity: 'Insufficient Security',
    windowSizeOutOfRange: 'Window Size Out Of Range',
    applicationExceededReplyTime: 'Application Exceeded Reply Time',
    outOfResources: 'Out Of Resources',
    tsmTimeout: 'TSM Timeout',
    apduTooLong: 'APDU Too Long',
  };

  /// All values defined by this library.
  static Iterable<BacnetAbortReason> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Abort Reason $value';

  /// Human readable name of this value.
  String get label => getName(value);
}

/// BACnet reject reasons (BACnetRejectReason).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetRejectReason(value)`.
extension type const BacnetRejectReason(int value) implements int {
  /// Other.
  static const other = BacnetRejectReason(0);

  /// Buffer Overflow.
  static const bufferOverflow = BacnetRejectReason(1);

  /// Inconsistent Parameters.
  static const inconsistentParameters = BacnetRejectReason(2);

  /// Invalid Parameter Data Type.
  static const invalidParameterDataType = BacnetRejectReason(3);

  /// Invalid Tag.
  static const invalidTag = BacnetRejectReason(4);

  /// Missing Required Parameter.
  static const missingRequiredParameter = BacnetRejectReason(5);

  /// Parameter Out Of Range.
  static const parameterOutOfRange = BacnetRejectReason(6);

  /// Too Many Arguments.
  static const tooManyArguments = BacnetRejectReason(7);

  /// Undefined Enumeration.
  static const undefinedEnumeration = BacnetRejectReason(8);

  /// Unrecognized Service.
  static const unrecognizedService = BacnetRejectReason(9);

  /// Invalid Data Encoding.
  static const invalidDataEncoding = BacnetRejectReason(10);

  static const Map<BacnetRejectReason, String> _labels = {
    other: 'Other',
    bufferOverflow: 'Buffer Overflow',
    inconsistentParameters: 'Inconsistent Parameters',
    invalidParameterDataType: 'Invalid Parameter Data Type',
    invalidTag: 'Invalid Tag',
    missingRequiredParameter: 'Missing Required Parameter',
    parameterOutOfRange: 'Parameter Out Of Range',
    tooManyArguments: 'Too Many Arguments',
    undefinedEnumeration: 'Undefined Enumeration',
    unrecognizedService: 'Unrecognized Service',
    invalidDataEncoding: 'Invalid Data Encoding',
  };

  /// All values defined by this library.
  static Iterable<BacnetRejectReason> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Reject Reason $value';

  /// Human readable name of this value.
  String get label => getName(value);
}
