// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet object types (BACnetObjectType).
abstract final class BacnetObjectType {
  /// Analog Input.
  static const int analogInput = 0;

  /// Analog Output.
  static const int analogOutput = 1;

  /// Analog Value.
  static const int analogValue = 2;

  /// Binary Input.
  static const int binaryInput = 3;

  /// Binary Output.
  static const int binaryOutput = 4;

  /// Binary Value.
  static const int binaryValue = 5;

  /// Calendar.
  static const int calendar = 6;

  /// Command.
  static const int command = 7;

  /// Device.
  static const int device = 8;

  /// Event Enrollment.
  static const int eventEnrollment = 9;

  /// File.
  static const int file = 10;

  /// Group.
  static const int group = 11;

  /// Loop.
  static const int loop = 12;

  /// Multi-state Input.
  static const int multiStateInput = 13;

  /// Multi-state Output.
  static const int multiStateOutput = 14;

  /// Notification Class.
  static const int notificationClass = 15;

  /// Program.
  static const int program = 16;

  /// Schedule.
  static const int schedule = 17;

  /// Averaging.
  static const int averaging = 18;

  /// Multi-state Value.
  static const int multiStateValue = 19;

  /// Trend Log.
  static const int trendLog = 20;

  /// Life Safety Point.
  static const int lifeSafetyPoint = 21;

  /// Life Safety Zone.
  static const int lifeSafetyZone = 22;

  /// Accumulator.
  static const int accumulator = 23;

  /// Pulse Converter.
  static const int pulseConverter = 24;

  /// Event Log.
  static const int eventLog = 25;

  /// Global Group.
  static const int globalGroup = 26;

  /// Trend Log Multiple.
  static const int trendLogMultiple = 27;

  /// Load Control.
  static const int loadControl = 28;

  /// Structured View.
  static const int structuredView = 29;

  /// Access Door.
  static const int accessDoor = 30;

  /// Timer.
  static const int timer = 31;

  /// Access Credential.
  static const int accessCredential = 32;

  /// Access Point.
  static const int accessPoint = 33;

  /// Access Rights.
  static const int accessRights = 34;

  /// Access User.
  static const int accessUser = 35;

  /// Access Zone.
  static const int accessZone = 36;

  /// Credential Data Input.
  static const int credentialDataInput = 37;

  /// Network Security.
  static const int networkSecurity = 38;

  /// BitString Value.
  static const int bitStringValue = 39;

  /// CharacterString Value.
  static const int characterStringValue = 40;

  /// Date Pattern Value.
  static const int datePatternValue = 41;

  /// Date Value.
  static const int dateValue = 42;

  /// DateTime Pattern Value.
  static const int dateTimePatternValue = 43;

  /// DateTime Value.
  static const int dateTimeValue = 44;

  /// Integer Value.
  static const int integerValue = 45;

  /// Large Analog Value.
  static const int largeAnalogValue = 46;

  /// OctetString Value.
  static const int octetStringValue = 47;

  /// Positive Integer Value.
  static const int positiveIntegerValue = 48;

  /// Time Pattern Value.
  static const int timePatternValue = 49;

  /// Time Value.
  static const int timeValue = 50;

  /// Notification Forwarder.
  static const int notificationForwarder = 51;

  /// Alert Enrollment.
  static const int alertEnrollment = 52;

  /// Channel.
  static const int channel = 53;

  /// Lighting Output.
  static const int lightingOutput = 54;

  /// Binary Lighting Output.
  static const int binaryLightingOutput = 55;

  /// Network Port.
  static const int networkPort = 56;

  /// Elevator Group.
  static const int elevatorGroup = 57;

  /// Escalator.
  static const int escalator = 58;

  /// Lift.
  static const int lift = 59;

  /// Staging.
  static const int staging = 60;

  /// Audit Log.
  static const int auditLog = 61;

  /// Audit Reporter.
  static const int auditReporter = 62;

  /// Color.
  static const int color = 63;

  /// Color Temperature.
  static const int colorTemperature = 64;

  static const Map<int, String> _labels = {
    analogInput: 'Analog Input',
    analogOutput: 'Analog Output',
    analogValue: 'Analog Value',
    binaryInput: 'Binary Input',
    binaryOutput: 'Binary Output',
    binaryValue: 'Binary Value',
    calendar: 'Calendar',
    command: 'Command',
    device: 'Device',
    eventEnrollment: 'Event Enrollment',
    file: 'File',
    group: 'Group',
    loop: 'Loop',
    multiStateInput: 'Multi-state Input',
    multiStateOutput: 'Multi-state Output',
    notificationClass: 'Notification Class',
    program: 'Program',
    schedule: 'Schedule',
    averaging: 'Averaging',
    multiStateValue: 'Multi-state Value',
    trendLog: 'Trend Log',
    lifeSafetyPoint: 'Life Safety Point',
    lifeSafetyZone: 'Life Safety Zone',
    accumulator: 'Accumulator',
    pulseConverter: 'Pulse Converter',
    eventLog: 'Event Log',
    globalGroup: 'Global Group',
    trendLogMultiple: 'Trend Log Multiple',
    loadControl: 'Load Control',
    structuredView: 'Structured View',
    accessDoor: 'Access Door',
    timer: 'Timer',
    accessCredential: 'Access Credential',
    accessPoint: 'Access Point',
    accessRights: 'Access Rights',
    accessUser: 'Access User',
    accessZone: 'Access Zone',
    credentialDataInput: 'Credential Data Input',
    networkSecurity: 'Network Security',
    bitStringValue: 'BitString Value',
    characterStringValue: 'CharacterString Value',
    datePatternValue: 'Date Pattern Value',
    dateValue: 'Date Value',
    dateTimePatternValue: 'DateTime Pattern Value',
    dateTimeValue: 'DateTime Value',
    integerValue: 'Integer Value',
    largeAnalogValue: 'Large Analog Value',
    octetStringValue: 'OctetString Value',
    positiveIntegerValue: 'Positive Integer Value',
    timePatternValue: 'Time Pattern Value',
    timeValue: 'Time Value',
    notificationForwarder: 'Notification Forwarder',
    alertEnrollment: 'Alert Enrollment',
    channel: 'Channel',
    lightingOutput: 'Lighting Output',
    binaryLightingOutput: 'Binary Lighting Output',
    networkPort: 'Network Port',
    elevatorGroup: 'Elevator Group',
    escalator: 'Escalator',
    lift: 'Lift',
    staging: 'Staging',
    auditLog: 'Audit Log',
    auditReporter: 'Audit Reporter',
    color: 'Color',
    colorTemperature: 'Color Temperature',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Unknown ($value)';
}
