// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet object types (BACnetObjectType).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetObjectType(value)`.
extension type const BacnetObjectType(int value) implements int {
  /// Analog Input.
  static const analogInput = BacnetObjectType(0);

  /// Analog Output.
  static const analogOutput = BacnetObjectType(1);

  /// Analog Value.
  static const analogValue = BacnetObjectType(2);

  /// Binary Input.
  static const binaryInput = BacnetObjectType(3);

  /// Binary Output.
  static const binaryOutput = BacnetObjectType(4);

  /// Binary Value.
  static const binaryValue = BacnetObjectType(5);

  /// Calendar.
  static const calendar = BacnetObjectType(6);

  /// Command.
  static const command = BacnetObjectType(7);

  /// Device.
  static const device = BacnetObjectType(8);

  /// Event Enrollment.
  static const eventEnrollment = BacnetObjectType(9);

  /// File.
  static const file = BacnetObjectType(10);

  /// Group.
  static const group = BacnetObjectType(11);

  /// Loop.
  static const loop = BacnetObjectType(12);

  /// Multi-state Input.
  static const multiStateInput = BacnetObjectType(13);

  /// Multi-state Output.
  static const multiStateOutput = BacnetObjectType(14);

  /// Notification Class.
  static const notificationClass = BacnetObjectType(15);

  /// Program.
  static const program = BacnetObjectType(16);

  /// Schedule.
  static const schedule = BacnetObjectType(17);

  /// Averaging.
  static const averaging = BacnetObjectType(18);

  /// Multi-state Value.
  static const multiStateValue = BacnetObjectType(19);

  /// Trend Log.
  static const trendLog = BacnetObjectType(20);

  /// Life Safety Point.
  static const lifeSafetyPoint = BacnetObjectType(21);

  /// Life Safety Zone.
  static const lifeSafetyZone = BacnetObjectType(22);

  /// Accumulator.
  static const accumulator = BacnetObjectType(23);

  /// Pulse Converter.
  static const pulseConverter = BacnetObjectType(24);

  /// Event Log.
  static const eventLog = BacnetObjectType(25);

  /// Global Group.
  static const globalGroup = BacnetObjectType(26);

  /// Trend Log Multiple.
  static const trendLogMultiple = BacnetObjectType(27);

  /// Load Control.
  static const loadControl = BacnetObjectType(28);

  /// Structured View.
  static const structuredView = BacnetObjectType(29);

  /// Access Door.
  static const accessDoor = BacnetObjectType(30);

  /// Timer.
  static const timer = BacnetObjectType(31);

  /// Access Credential.
  static const accessCredential = BacnetObjectType(32);

  /// Access Point.
  static const accessPoint = BacnetObjectType(33);

  /// Access Rights.
  static const accessRights = BacnetObjectType(34);

  /// Access User.
  static const accessUser = BacnetObjectType(35);

  /// Access Zone.
  static const accessZone = BacnetObjectType(36);

  /// Credential Data Input.
  static const credentialDataInput = BacnetObjectType(37);

  /// Network Security.
  static const networkSecurity = BacnetObjectType(38);

  /// BitString Value.
  static const bitStringValue = BacnetObjectType(39);

  /// CharacterString Value.
  static const characterStringValue = BacnetObjectType(40);

  /// Date Pattern Value.
  static const datePatternValue = BacnetObjectType(41);

  /// Date Value.
  static const dateValue = BacnetObjectType(42);

  /// DateTime Pattern Value.
  static const dateTimePatternValue = BacnetObjectType(43);

  /// DateTime Value.
  static const dateTimeValue = BacnetObjectType(44);

  /// Integer Value.
  static const integerValue = BacnetObjectType(45);

  /// Large Analog Value.
  static const largeAnalogValue = BacnetObjectType(46);

  /// OctetString Value.
  static const octetStringValue = BacnetObjectType(47);

  /// Positive Integer Value.
  static const positiveIntegerValue = BacnetObjectType(48);

  /// Time Pattern Value.
  static const timePatternValue = BacnetObjectType(49);

  /// Time Value.
  static const timeValue = BacnetObjectType(50);

  /// Notification Forwarder.
  static const notificationForwarder = BacnetObjectType(51);

  /// Alert Enrollment.
  static const alertEnrollment = BacnetObjectType(52);

  /// Channel.
  static const channel = BacnetObjectType(53);

  /// Lighting Output.
  static const lightingOutput = BacnetObjectType(54);

  /// Binary Lighting Output.
  static const binaryLightingOutput = BacnetObjectType(55);

  /// Network Port.
  static const networkPort = BacnetObjectType(56);

  /// Elevator Group.
  static const elevatorGroup = BacnetObjectType(57);

  /// Escalator.
  static const escalator = BacnetObjectType(58);

  /// Lift.
  static const lift = BacnetObjectType(59);

  /// Staging.
  static const staging = BacnetObjectType(60);

  /// Audit Log.
  static const auditLog = BacnetObjectType(61);

  /// Audit Reporter.
  static const auditReporter = BacnetObjectType(62);

  /// Color.
  static const color = BacnetObjectType(63);

  /// Color Temperature.
  static const colorTemperature = BacnetObjectType(64);

  static const Map<BacnetObjectType, String> _labels = {
    analogInput: 'Analog Input',
    analogOutput: 'Analog Output',
    analogValue: 'Analog Value',
    binaryInput: 'Binary Input',
    binaryOutput: 'Binary Output',
    binaryValue: 'Binary Value',
    calendar: 'Calendar',
    command: 'Command',
    device: 'Device',
    eventEnrollment: 'Event Enrollment',
    file: 'File',
    group: 'Group',
    loop: 'Loop',
    multiStateInput: 'Multi-state Input',
    multiStateOutput: 'Multi-state Output',
    notificationClass: 'Notification Class',
    program: 'Program',
    schedule: 'Schedule',
    averaging: 'Averaging',
    multiStateValue: 'Multi-state Value',
    trendLog: 'Trend Log',
    lifeSafetyPoint: 'Life Safety Point',
    lifeSafetyZone: 'Life Safety Zone',
    accumulator: 'Accumulator',
    pulseConverter: 'Pulse Converter',
    eventLog: 'Event Log',
    globalGroup: 'Global Group',
    trendLogMultiple: 'Trend Log Multiple',
    loadControl: 'Load Control',
    structuredView: 'Structured View',
    accessDoor: 'Access Door',
    timer: 'Timer',
    accessCredential: 'Access Credential',
    accessPoint: 'Access Point',
    accessRights: 'Access Rights',
    accessUser: 'Access User',
    accessZone: 'Access Zone',
    credentialDataInput: 'Credential Data Input',
    networkSecurity: 'Network Security',
    bitStringValue: 'BitString Value',
    characterStringValue: 'CharacterString Value',
    datePatternValue: 'Date Pattern Value',
    dateValue: 'Date Value',
    dateTimePatternValue: 'DateTime Pattern Value',
    dateTimeValue: 'DateTime Value',
    integerValue: 'Integer Value',
    largeAnalogValue: 'Large Analog Value',
    octetStringValue: 'OctetString Value',
    positiveIntegerValue: 'Positive Integer Value',
    timePatternValue: 'Time Pattern Value',
    timeValue: 'Time Value',
    notificationForwarder: 'Notification Forwarder',
    alertEnrollment: 'Alert Enrollment',
    channel: 'Channel',
    lightingOutput: 'Lighting Output',
    binaryLightingOutput: 'Binary Lighting Output',
    networkPort: 'Network Port',
    elevatorGroup: 'Elevator Group',
    escalator: 'Escalator',
    lift: 'Lift',
    staging: 'Staging',
    auditLog: 'Audit Log',
    auditReporter: 'Audit Reporter',
    color: 'Color',
    colorTemperature: 'Color Temperature',
  };

  /// All values defined by this library.
  static Iterable<BacnetObjectType> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Unknown ($value)';

  /// Human readable name of this value.
  String get label => getName(value);
}
