// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet property identifiers (BACnetPropertyIdentifier).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetPropertyId(value)`.
extension type const BacnetPropertyId(int value) implements int {
  /// Acked Transitions.
  static const ackedTransitions = BacnetPropertyId(0);

  /// Ack Required.
  static const ackRequired = BacnetPropertyId(1);

  /// Action.
  static const action = BacnetPropertyId(2);

  /// Action Text.
  static const actionText = BacnetPropertyId(3);

  /// Active Text.
  static const activeText = BacnetPropertyId(4);

  /// Active VT Sessions.
  static const activeVtSessions = BacnetPropertyId(5);

  /// Alarm Value.
  static const alarmValue = BacnetPropertyId(6);

  /// Alarm Values.
  static const alarmValues = BacnetPropertyId(7);

  /// All.
  static const all = BacnetPropertyId(8);

  /// All Writes Successful.
  static const allWritesSuccessful = BacnetPropertyId(9);

  /// APDU Segment Timeout.
  static const apduSegmentTimeout = BacnetPropertyId(10);

  /// APDU Timeout.
  static const apduTimeout = BacnetPropertyId(11);

  /// Application Software Version.
  static const applicationSoftwareVersion = BacnetPropertyId(12);

  /// Archive.
  static const archive = BacnetPropertyId(13);

  /// Bias.
  static const bias = BacnetPropertyId(14);

  /// Change Of State Count.
  static const changeOfStateCount = BacnetPropertyId(15);

  /// Change Of State Time.
  static const changeOfStateTime = BacnetPropertyId(16);

  /// Notification Class.
  static const notificationClass = BacnetPropertyId(17);

  /// Controlled Variable Reference.
  static const controlledVariableReference = BacnetPropertyId(19);

  /// Controlled Variable Units.
  static const controlledVariableUnits = BacnetPropertyId(20);

  /// Controlled Variable Value.
  static const controlledVariableValue = BacnetPropertyId(21);

  /// COV Increment.
  static const covIncrement = BacnetPropertyId(22);

  /// Date List.
  static const dateList = BacnetPropertyId(23);

  /// Daylight Savings Status.
  static const daylightSavingsStatus = BacnetPropertyId(24);

  /// Deadband.
  static const deadband = BacnetPropertyId(25);

  /// Derivative Constant.
  static const derivativeConstant = BacnetPropertyId(26);

  /// Derivative Constant Units.
  static const derivativeConstantUnits = BacnetPropertyId(27);

  /// Description.
  static const description = BacnetPropertyId(28);

  /// Description Of Halt.
  static const descriptionOfHalt = BacnetPropertyId(29);

  /// Device Address Binding.
  static const deviceAddressBinding = BacnetPropertyId(30);

  /// Device Type.
  static const deviceType = BacnetPropertyId(31);

  /// Effective Period.
  static const effectivePeriod = BacnetPropertyId(32);

  /// Elapsed Active Time.
  static const elapsedActiveTime = BacnetPropertyId(33);

  /// Error Limit.
  static const errorLimit = BacnetPropertyId(34);

  /// Event Enable.
  static const eventEnable = BacnetPropertyId(35);

  /// Event State.
  static const eventState = BacnetPropertyId(36);

  /// Event Type.
  static const eventType = BacnetPropertyId(37);

  /// Exception Schedule.
  static const exceptionSchedule = BacnetPropertyId(38);

  /// Fault Values.
  static const faultValues = BacnetPropertyId(39);

  /// Feedback Value.
  static const feedbackValue = BacnetPropertyId(40);

  /// File Access Method.
  static const fileAccessMethod = BacnetPropertyId(41);

  /// File Size.
  static const fileSize = BacnetPropertyId(42);

  /// File Type.
  static const fileType = BacnetPropertyId(43);

  /// Firmware Revision.
  static const firmwareRevision = BacnetPropertyId(44);

  /// High Limit.
  static const highLimit = BacnetPropertyId(45);

  /// Inactive Text.
  static const inactiveText = BacnetPropertyId(46);

  /// In Process.
  static const inProcess = BacnetPropertyId(47);

  /// Instance Of.
  static const instanceOf = BacnetPropertyId(48);

  /// Integral Constant.
  static const integralConstant = BacnetPropertyId(49);

  /// Integral Constant Units.
  static const integralConstantUnits = BacnetPropertyId(50);

  /// Issue Confirmed Notifications.
  static const issueConfirmedNotifications = BacnetPropertyId(51);

  /// Limit Enable.
  static const limitEnable = BacnetPropertyId(52);

  /// List Of Group Members.
  static const listOfGroupMembers = BacnetPropertyId(53);

  /// List Of Object Property References.
  static const listOfObjectPropertyReferences = BacnetPropertyId(54);

  /// List Of Session Keys.
  static const listOfSessionKeys = BacnetPropertyId(55);

  /// Local Date.
  static const localDate = BacnetPropertyId(56);

  /// Local Time.
  static const localTime = BacnetPropertyId(57);

  /// Location.
  static const location = BacnetPropertyId(58);

  /// Low Limit.
  static const lowLimit = BacnetPropertyId(59);

  /// Manipulated Variable Reference.
  static const manipulatedVariableReference = BacnetPropertyId(60);

  /// Maximum Output.
  static const maximumOutput = BacnetPropertyId(61);

  /// Max APDU Length Accepted.
  static const maxApduLengthAccepted = BacnetPropertyId(62);

  /// Max Info Frames.
  static const maxInfoFrames = BacnetPropertyId(63);

  /// Max Master.
  static const maxMaster = BacnetPropertyId(64);

  /// Max Pres Value.
  static const maxPresValue = BacnetPropertyId(65);

  /// Minimum Off Time.
  static const minimumOffTime = BacnetPropertyId(66);

  /// Minimum On Time.
  static const minimumOnTime = BacnetPropertyId(67);

  /// Minimum Output.
  static const minimumOutput = BacnetPropertyId(68);

  /// Min Pres Value.
  static const minPresValue = BacnetPropertyId(69);

  /// Model Name.
  static const modelName = BacnetPropertyId(70);

  /// Modification Date.
  static const modificationDate = BacnetPropertyId(71);

  /// Notify Type.
  static const notifyType = BacnetPropertyId(72);

  /// Number Of APDU Retries.
  static const numberOfApduRetries = BacnetPropertyId(73);

  /// Number Of States.
  static const numberOfStates = BacnetPropertyId(74);

  /// Object Identifier.
  static const objectIdentifier = BacnetPropertyId(75);

  /// Object List.
  static const objectList = BacnetPropertyId(76);

  /// Object Name.
  static const objectName = BacnetPropertyId(77);

  /// Object Property Reference.
  static const objectPropertyReference = BacnetPropertyId(78);

  /// Object Type.
  static const objectType = BacnetPropertyId(79);

  /// Optional.
  static const optional = BacnetPropertyId(80);

  /// Out Of Service.
  static const outOfService = BacnetPropertyId(81);

  /// Output Units.
  static const outputUnits = BacnetPropertyId(82);

  /// Event Parameters.
  static const eventParameters = BacnetPropertyId(83);

  /// Polarity.
  static const polarity = BacnetPropertyId(84);

  /// Present Value.
  static const presentValue = BacnetPropertyId(85);

  /// Priority.
  static const priority = BacnetPropertyId(86);

  /// Priority Array.
  static const priorityArray = BacnetPropertyId(87);

  /// Priority For Writing.
  static const priorityForWriting = BacnetPropertyId(88);

  /// Process Identifier.
  static const processIdentifier = BacnetPropertyId(89);

  /// Program Change.
  static const programChange = BacnetPropertyId(90);

  /// Program Location.
  static const programLocation = BacnetPropertyId(91);

  /// Program State.
  static const programState = BacnetPropertyId(92);

  /// Proportional Constant.
  static const proportionalConstant = BacnetPropertyId(93);

  /// Proportional Constant Units.
  static const proportionalConstantUnits = BacnetPropertyId(94);

  /// Protocol Conformance Class.
  static const protocolConformanceClass = BacnetPropertyId(95);

  /// Protocol Object Types Supported.
  static const protocolObjectTypesSupported = BacnetPropertyId(96);

  /// Protocol Services Supported.
  static const protocolServicesSupported = BacnetPropertyId(97);

  /// Protocol Version.
  static const protocolVersion = BacnetPropertyId(98);

  /// Read Only.
  static const readOnly = BacnetPropertyId(99);

  /// Reason For Halt.
  static const reasonForHalt = BacnetPropertyId(100);

  /// Recipient.
  static const recipient = BacnetPropertyId(101);

  /// Recipient List.
  static const recipientList = BacnetPropertyId(102);

  /// Reliability.
  static const reliability = BacnetPropertyId(103);

  /// Relinquish Default.
  static const relinquishDefault = BacnetPropertyId(104);

  /// Required.
  static const required = BacnetPropertyId(105);

  /// Resolution.
  static const resolution = BacnetPropertyId(106);

  /// Segmentation Supported.
  static const segmentationSupported = BacnetPropertyId(107);

  /// Setpoint.
  static const setpoint = BacnetPropertyId(108);

  /// Setpoint Reference.
  static const setpointReference = BacnetPropertyId(109);

  /// State Text.
  static const stateText = BacnetPropertyId(110);

  /// Status Flags.
  static const statusFlags = BacnetPropertyId(111);

  /// System Status.
  static const systemStatus = BacnetPropertyId(112);

  /// Time Delay.
  static const timeDelay = BacnetPropertyId(113);

  /// Time Of Active Time Reset.
  static const timeOfActiveTimeReset = BacnetPropertyId(114);

  /// Time Of State Count Reset.
  static const timeOfStateCountReset = BacnetPropertyId(115);

  /// Time Synchronization Recipients.
  static const timeSynchronizationRecipients = BacnetPropertyId(116);

  /// Units.
  static const units = BacnetPropertyId(117);

  /// Update Interval.
  static const updateInterval = BacnetPropertyId(118);

  /// UTC Offset.
  static const utcOffset = BacnetPropertyId(119);

  /// Vendor Identifier.
  static const vendorIdentifier = BacnetPropertyId(120);

  /// Vendor Name.
  static const vendorName = BacnetPropertyId(121);

  /// VT Classes Supported.
  static const vtClassesSupported = BacnetPropertyId(122);

  /// Weekly Schedule.
  static const weeklySchedule = BacnetPropertyId(123);

  /// Attempted Samples.
  static const attemptedSamples = BacnetPropertyId(124);

  /// Average Value.
  static const averageValue = BacnetPropertyId(125);

  /// Buffer Size.
  static const bufferSize = BacnetPropertyId(126);

  /// Client COV Increment.
  static const clientCovIncrement = BacnetPropertyId(127);

  /// COV Resubscription Interval.
  static const covResubscriptionInterval = BacnetPropertyId(128);

  /// Current Notify Time.
  static const currentNotifyTime = BacnetPropertyId(129);

  /// Event Time Stamps.
  static const eventTimeStamps = BacnetPropertyId(130);

  /// Log Buffer.
  static const logBuffer = BacnetPropertyId(131);

  /// Log Device Object Property.
  static const logDeviceObjectProperty = BacnetPropertyId(132);

  /// Enable.
  static const enable = BacnetPropertyId(133);

  /// Log Interval.
  static const logInterval = BacnetPropertyId(134);

  /// Maximum Value.
  static const maximumValue = BacnetPropertyId(135);

  /// Minimum Value.
  static const minimumValue = BacnetPropertyId(136);

  /// Notification Threshold.
  static const notificationThreshold = BacnetPropertyId(137);

  /// Previous Notify Time.
  static const previousNotifyTime = BacnetPropertyId(138);

  /// Protocol Revision.
  static const protocolRevision = BacnetPropertyId(139);

  /// Records Since Notification.
  static const recordsSinceNotification = BacnetPropertyId(140);

  /// Record Count.
  static const recordCount = BacnetPropertyId(141);

  /// Start Time.
  static const startTime = BacnetPropertyId(142);

  /// Stop Time.
  static const stopTime = BacnetPropertyId(143);

  /// Stop When Full.
  static const stopWhenFull = BacnetPropertyId(144);

  /// Total Record Count.
  static const totalRecordCount = BacnetPropertyId(145);

  /// Valid Samples.
  static const validSamples = BacnetPropertyId(146);

  /// Window Interval.
  static const windowInterval = BacnetPropertyId(147);

  /// Window Samples.
  static const windowSamples = BacnetPropertyId(148);

  /// Maximum Value Timestamp.
  static const maximumValueTimestamp = BacnetPropertyId(149);

  /// Minimum Value Timestamp.
  static const minimumValueTimestamp = BacnetPropertyId(150);

  /// Variance Value.
  static const varianceValue = BacnetPropertyId(151);

  /// Active COV Subscriptions.
  static const activeCovSubscriptions = BacnetPropertyId(152);

  /// Backup Failure Timeout.
  static const backupFailureTimeout = BacnetPropertyId(153);

  /// Configuration Files.
  static const configurationFiles = BacnetPropertyId(154);

  /// Database Revision.
  static const databaseRevision = BacnetPropertyId(155);

  /// Direct Reading.
  static const directReading = BacnetPropertyId(156);

  /// Last Restore Time.
  static const lastRestoreTime = BacnetPropertyId(157);

  /// Maintenance Required.
  static const maintenanceRequired = BacnetPropertyId(158);

  /// Member Of.
  static const memberOf = BacnetPropertyId(159);

  /// Mode.
  static const mode = BacnetPropertyId(160);

  /// Operation Expected.
  static const operationExpected = BacnetPropertyId(161);

  /// Setting.
  static const setting = BacnetPropertyId(162);

  /// Silenced.
  static const silenced = BacnetPropertyId(163);

  /// Tracking Value.
  static const trackingValue = BacnetPropertyId(164);

  /// Zone Members.
  static const zoneMembers = BacnetPropertyId(165);

  /// Life Safety Alarm Values.
  static const lifeSafetyAlarmValues = BacnetPropertyId(166);

  /// Max Segments Accepted.
  static const maxSegmentsAccepted = BacnetPropertyId(167);

  /// Profile Name.
  static const profileName = BacnetPropertyId(168);

  /// Auto Slave Discovery.
  static const autoSlaveDiscovery = BacnetPropertyId(169);

  /// Manual Slave Address Binding.
  static const manualSlaveAddressBinding = BacnetPropertyId(170);

  /// Slave Address Binding.
  static const slaveAddressBinding = BacnetPropertyId(171);

  /// Slave Proxy Enable.
  static const slaveProxyEnable = BacnetPropertyId(172);

  /// Last Notify Record.
  static const lastNotifyRecord = BacnetPropertyId(173);

  /// Schedule Default.
  static const scheduleDefault = BacnetPropertyId(174);

  /// Accepted Modes.
  static const acceptedModes = BacnetPropertyId(175);

  /// Adjust Value.
  static const adjustValue = BacnetPropertyId(176);

  /// Count.
  static const count = BacnetPropertyId(177);

  /// Count Before Change.
  static const countBeforeChange = BacnetPropertyId(178);

  /// Count Change Time.
  static const countChangeTime = BacnetPropertyId(179);

  /// COV Period.
  static const covPeriod = BacnetPropertyId(180);

  /// Input Reference.
  static const inputReference = BacnetPropertyId(181);

  /// Limit Monitoring Interval.
  static const limitMonitoringInterval = BacnetPropertyId(182);

  /// Logging Object.
  static const loggingObject = BacnetPropertyId(183);

  /// Logging Record.
  static const loggingRecord = BacnetPropertyId(184);

  /// Prescale.
  static const prescale = BacnetPropertyId(185);

  /// Pulse Rate.
  static const pulseRate = BacnetPropertyId(186);

  /// Scale.
  static const scale = BacnetPropertyId(187);

  /// Scale Factor.
  static const scaleFactor = BacnetPropertyId(188);

  /// Update Time.
  static const updateTime = BacnetPropertyId(189);

  /// Value Before Change.
  static const valueBeforeChange = BacnetPropertyId(190);

  /// Value Set.
  static const valueSet = BacnetPropertyId(191);

  /// Value Change Time.
  static const valueChangeTime = BacnetPropertyId(192);

  /// Align Intervals.
  static const alignIntervals = BacnetPropertyId(193);

  /// Interval Offset.
  static const intervalOffset = BacnetPropertyId(195);

  /// Last Restart Reason.
  static const lastRestartReason = BacnetPropertyId(196);

  /// Logging Type.
  static const loggingType = BacnetPropertyId(197);

  /// Restart Notification Recipients.
  static const restartNotificationRecipients = BacnetPropertyId(202);

  /// Time Of Device Restart.
  static const timeOfDeviceRestart = BacnetPropertyId(203);

  /// Time Synchronization Interval.
  static const timeSynchronizationInterval = BacnetPropertyId(204);

  /// Trigger.
  static const trigger = BacnetPropertyId(205);

  /// UTC Time Synchronization Recipients.
  static const utcTimeSynchronizationRecipients = BacnetPropertyId(206);

  /// Node Subtype.
  static const nodeSubtype = BacnetPropertyId(207);

  /// Node Type.
  static const nodeType = BacnetPropertyId(208);

  /// Structured Object List.
  static const structuredObjectList = BacnetPropertyId(209);

  /// Subordinate Annotations.
  static const subordinateAnnotations = BacnetPropertyId(210);

  /// Subordinate List.
  static const subordinateList = BacnetPropertyId(211);

  /// Actual Shed Level.
  static const actualShedLevel = BacnetPropertyId(212);

  /// Duty Window.
  static const dutyWindow = BacnetPropertyId(213);

  /// Expected Shed Level.
  static const expectedShedLevel = BacnetPropertyId(214);

  /// Full Duty Baseline.
  static const fullDutyBaseline = BacnetPropertyId(215);

  /// Requested Shed Level.
  static const requestedShedLevel = BacnetPropertyId(218);

  /// Shed Duration.
  static const shedDuration = BacnetPropertyId(219);

  /// Shed Level Descriptions.
  static const shedLevelDescriptions = BacnetPropertyId(220);

  /// Shed Levels.
  static const shedLevels = BacnetPropertyId(221);

  /// State Description.
  static const stateDescription = BacnetPropertyId(222);

  /// Door Alarm State.
  static const doorAlarmState = BacnetPropertyId(226);

  /// Door Extended Pulse Time.
  static const doorExtendedPulseTime = BacnetPropertyId(227);

  /// Door Members.
  static const doorMembers = BacnetPropertyId(228);

  /// Door Open Too Long Time.
  static const doorOpenTooLongTime = BacnetPropertyId(229);

  /// Door Pulse Time.
  static const doorPulseTime = BacnetPropertyId(230);

  /// Door Status.
  static const doorStatus = BacnetPropertyId(231);

  /// Door Unlock Delay Time.
  static const doorUnlockDelayTime = BacnetPropertyId(232);

  /// Lock Status.
  static const lockStatus = BacnetPropertyId(233);

  /// Masked Alarm Values.
  static const maskedAlarmValues = BacnetPropertyId(234);

  /// Secured Status.
  static const securedStatus = BacnetPropertyId(235);

  /// Absentee Limit.
  static const absenteeLimit = BacnetPropertyId(244);

  /// Access Alarm Events.
  static const accessAlarmEvents = BacnetPropertyId(245);

  /// Access Doors.
  static const accessDoors = BacnetPropertyId(246);

  /// Access Event.
  static const accessEvent = BacnetPropertyId(247);

  /// Access Event Authentication Factor.
  static const accessEventAuthenticationFactor = BacnetPropertyId(248);

  /// Access Event Credential.
  static const accessEventCredential = BacnetPropertyId(249);

  /// Access Event Time.
  static const accessEventTime = BacnetPropertyId(250);

  /// Access Transaction Events.
  static const accessTransactionEvents = BacnetPropertyId(251);

  /// Accompaniment.
  static const accompaniment = BacnetPropertyId(252);

  /// Accompaniment Time.
  static const accompanimentTime = BacnetPropertyId(253);

  /// Activation Time.
  static const activationTime = BacnetPropertyId(254);

  /// Active Authentication Policy.
  static const activeAuthenticationPolicy = BacnetPropertyId(255);

  /// Assigned Access Rights.
  static const assignedAccessRights = BacnetPropertyId(256);

  /// Authentication Factors.
  static const authenticationFactors = BacnetPropertyId(257);

  /// Authentication Policy List.
  static const authenticationPolicyList = BacnetPropertyId(258);

  /// Authentication Policy Names.
  static const authenticationPolicyNames = BacnetPropertyId(259);

  /// Authentication Status.
  static const authenticationStatus = BacnetPropertyId(260);

  /// Authorization Mode.
  static const authorizationMode = BacnetPropertyId(261);

  /// Belongs To.
  static const belongsTo = BacnetPropertyId(262);

  /// Credential Disable.
  static const credentialDisable = BacnetPropertyId(263);

  /// Credential Status.
  static const credentialStatus = BacnetPropertyId(264);

  /// Credentials.
  static const credentials = BacnetPropertyId(265);

  /// Credentials In Zone.
  static const credentialsInZone = BacnetPropertyId(266);

  /// Days Remaining.
  static const daysRemaining = BacnetPropertyId(267);

  /// Entry Points.
  static const entryPoints = BacnetPropertyId(268);

  /// Exit Points.
  static const exitPoints = BacnetPropertyId(269);

  /// Expiration Time.
  static const expirationTime = BacnetPropertyId(270);

  /// Extended Time Enable.
  static const extendedTimeEnable = BacnetPropertyId(271);

  /// Failed Attempt Events.
  static const failedAttemptEvents = BacnetPropertyId(272);

  /// Failed Attempts.
  static const failedAttempts = BacnetPropertyId(273);

  /// Failed Attempts Time.
  static const failedAttemptsTime = BacnetPropertyId(274);

  /// Last Access Event.
  static const lastAccessEvent = BacnetPropertyId(275);

  /// Last Access Point.
  static const lastAccessPoint = BacnetPropertyId(276);

  /// Last Credential Added.
  static const lastCredentialAdded = BacnetPropertyId(277);

  /// Last Credential Added Time.
  static const lastCredentialAddedTime = BacnetPropertyId(278);

  /// Last Credential Removed.
  static const lastCredentialRemoved = BacnetPropertyId(279);

  /// Last Credential Removed Time.
  static const lastCredentialRemovedTime = BacnetPropertyId(280);

  /// Last Use Time.
  static const lastUseTime = BacnetPropertyId(281);

  /// Lockout.
  static const lockout = BacnetPropertyId(282);

  /// Lockout Relinquish Time.
  static const lockoutRelinquishTime = BacnetPropertyId(283);

  /// Master Exemption.
  static const masterExemption = BacnetPropertyId(284);

  /// Max Failed Attempts.
  static const maxFailedAttempts = BacnetPropertyId(285);

  /// Members.
  static const members = BacnetPropertyId(286);

  /// Muster Point.
  static const musterPoint = BacnetPropertyId(287);

  /// Negative Access Rules.
  static const negativeAccessRules = BacnetPropertyId(288);

  /// Number Of Authentication Policies.
  static const numberOfAuthenticationPolicies = BacnetPropertyId(289);

  /// Occupancy Count.
  static const occupancyCount = BacnetPropertyId(290);

  /// Occupancy Count Adjust.
  static const occupancyCountAdjust = BacnetPropertyId(291);

  /// Occupancy Count Enable.
  static const occupancyCountEnable = BacnetPropertyId(292);

  /// Occupancy Exemption.
  static const occupancyExemption = BacnetPropertyId(293);

  /// Occupancy Lower Limit.
  static const occupancyLowerLimit = BacnetPropertyId(294);

  /// Occupancy Lower Limit Enforced.
  static const occupancyLowerLimitEnforced = BacnetPropertyId(295);

  /// Occupancy State.
  static const occupancyState = BacnetPropertyId(296);

  /// Occupancy Upper Limit.
  static const occupancyUpperLimit = BacnetPropertyId(297);

  /// Occupancy Upper Limit Enforced.
  static const occupancyUpperLimitEnforced = BacnetPropertyId(298);

  /// Passback Exemption.
  static const passbackExemption = BacnetPropertyId(299);

  /// Passback Mode.
  static const passbackMode = BacnetPropertyId(300);

  /// Passback Timeout.
  static const passbackTimeout = BacnetPropertyId(301);

  /// Positive Access Rules.
  static const positiveAccessRules = BacnetPropertyId(302);

  /// Reason For Disable.
  static const reasonForDisable = BacnetPropertyId(303);

  /// Supported Formats.
  static const supportedFormats = BacnetPropertyId(304);

  /// Supported Format Classes.
  static const supportedFormatClasses = BacnetPropertyId(305);

  /// Threat Authority.
  static const threatAuthority = BacnetPropertyId(306);

  /// Threat Level.
  static const threatLevel = BacnetPropertyId(307);

  /// Trace Flag.
  static const traceFlag = BacnetPropertyId(308);

  /// Transaction Notification Class.
  static const transactionNotificationClass = BacnetPropertyId(309);

  /// User External Identifier.
  static const userExternalIdentifier = BacnetPropertyId(310);

  /// User Information Reference.
  static const userInformationReference = BacnetPropertyId(311);

  /// User Name.
  static const userName = BacnetPropertyId(317);

  /// User Type.
  static const userType = BacnetPropertyId(318);

  /// Uses Remaining.
  static const usesRemaining = BacnetPropertyId(319);

  /// Zone From.
  static const zoneFrom = BacnetPropertyId(320);

  /// Zone To.
  static const zoneTo = BacnetPropertyId(321);

  /// Access Event Tag.
  static const accessEventTag = BacnetPropertyId(322);

  /// Global Identifier.
  static const globalIdentifier = BacnetPropertyId(323);

  /// Verification Time.
  static const verificationTime = BacnetPropertyId(326);

  /// Base Device Security Policy.
  static const baseDeviceSecurityPolicy = BacnetPropertyId(327);

  /// Distribution Key Revision.
  static const distributionKeyRevision = BacnetPropertyId(328);

  /// Do Not Hide.
  static const doNotHide = BacnetPropertyId(329);

  /// Key Sets.
  static const keySets = BacnetPropertyId(330);

  /// Last Key Server.
  static const lastKeyServer = BacnetPropertyId(331);

  /// Network Access Security Policies.
  static const networkAccessSecurityPolicies = BacnetPropertyId(332);

  /// Packet Reorder Time.
  static const packetReorderTime = BacnetPropertyId(333);

  /// Security Pdu Timeout.
  static const securityPduTimeout = BacnetPropertyId(334);

  /// Security Time Window.
  static const securityTimeWindow = BacnetPropertyId(335);

  /// Supported Security Algorithm.
  static const supportedSecurityAlgorithm = BacnetPropertyId(336);

  /// Update Key Set Timeout.
  static const updateKeySetTimeout = BacnetPropertyId(337);

  /// Backup And Restore State.
  static const backupAndRestoreState = BacnetPropertyId(338);

  /// Backup Preparation Time.
  static const backupPreparationTime = BacnetPropertyId(339);

  /// Restore Completion Time.
  static const restoreCompletionTime = BacnetPropertyId(340);

  /// Restore Preparation Time.
  static const restorePreparationTime = BacnetPropertyId(341);

  /// Bit Mask.
  static const bitMask = BacnetPropertyId(342);

  /// Bit Text.
  static const bitText = BacnetPropertyId(343);

  /// Is UTC.
  static const isUtc = BacnetPropertyId(344);

  /// Group Members.
  static const groupMembers = BacnetPropertyId(345);

  /// Group Member Names.
  static const groupMemberNames = BacnetPropertyId(346);

  /// Member Status Flags.
  static const memberStatusFlags = BacnetPropertyId(347);

  /// Requested Update Interval.
  static const requestedUpdateInterval = BacnetPropertyId(348);

  /// Covu Period.
  static const covuPeriod = BacnetPropertyId(349);

  /// Covu Recipients.
  static const covuRecipients = BacnetPropertyId(350);

  /// Event Message Texts.
  static const eventMessageTexts = BacnetPropertyId(351);

  /// Event Message Texts Config.
  static const eventMessageTextsConfig = BacnetPropertyId(352);

  /// Event Detection Enable.
  static const eventDetectionEnable = BacnetPropertyId(353);

  /// Event Algorithm Inhibit.
  static const eventAlgorithmInhibit = BacnetPropertyId(354);

  /// Event Algorithm Inhibit Ref.
  static const eventAlgorithmInhibitRef = BacnetPropertyId(355);

  /// Time Delay Normal.
  static const timeDelayNormal = BacnetPropertyId(356);

  /// Reliability Evaluation Inhibit.
  static const reliabilityEvaluationInhibit = BacnetPropertyId(357);

  /// Fault Parameters.
  static const faultParameters = BacnetPropertyId(358);

  /// Fault Type.
  static const faultType = BacnetPropertyId(359);

  /// Local Forwarding Only.
  static const localForwardingOnly = BacnetPropertyId(360);

  /// Process Identifier Filter.
  static const processIdentifierFilter = BacnetPropertyId(361);

  /// Subscribed Recipients.
  static const subscribedRecipients = BacnetPropertyId(362);

  /// Port Filter.
  static const portFilter = BacnetPropertyId(363);

  /// Authorization Exemptions.
  static const authorizationExemptions = BacnetPropertyId(364);

  /// Allow Group Delay Inhibit.
  static const allowGroupDelayInhibit = BacnetPropertyId(365);

  /// Channel Number.
  static const channelNumber = BacnetPropertyId(366);

  /// Control Groups.
  static const controlGroups = BacnetPropertyId(367);

  /// Execution Delay.
  static const executionDelay = BacnetPropertyId(368);

  /// Last Priority.
  static const lastPriority = BacnetPropertyId(369);

  /// Write Status.
  static const writeStatus = BacnetPropertyId(370);

  /// Property List.
  static const propertyList = BacnetPropertyId(371);

  /// Serial Number.
  static const serialNumber = BacnetPropertyId(372);

  /// Blink Warn Enable.
  static const blinkWarnEnable = BacnetPropertyId(373);

  /// Default Fade Time.
  static const defaultFadeTime = BacnetPropertyId(374);

  /// Default Ramp Rate.
  static const defaultRampRate = BacnetPropertyId(375);

  /// Default Step Increment.
  static const defaultStepIncrement = BacnetPropertyId(376);

  /// Egress Time.
  static const egressTime = BacnetPropertyId(377);

  /// In Progress.
  static const inProgress = BacnetPropertyId(378);

  /// Instantaneous Power.
  static const instantaneousPower = BacnetPropertyId(379);

  /// Lighting Command.
  static const lightingCommand = BacnetPropertyId(380);

  /// Lighting Command Default Priority.
  static const lightingCommandDefaultPriority = BacnetPropertyId(381);

  /// Max Actual Value.
  static const maxActualValue = BacnetPropertyId(382);

  /// Min Actual Value.
  static const minActualValue = BacnetPropertyId(383);

  /// Power.
  static const power = BacnetPropertyId(384);

  /// Transition.
  static const transition = BacnetPropertyId(385);

  /// Egress Active.
  static const egressActive = BacnetPropertyId(386);

  /// Interface Value.
  static const interfaceValue = BacnetPropertyId(387);

  /// Fault High Limit.
  static const faultHighLimit = BacnetPropertyId(388);

  /// Fault Low Limit.
  static const faultLowLimit = BacnetPropertyId(389);

  /// Low Diff Limit.
  static const lowDiffLimit = BacnetPropertyId(390);

  /// Strike Count.
  static const strikeCount = BacnetPropertyId(391);

  /// Time Of Strike Count Reset.
  static const timeOfStrikeCountReset = BacnetPropertyId(392);

  /// Default Timeout.
  static const defaultTimeout = BacnetPropertyId(393);

  /// Initial Timeout.
  static const initialTimeout = BacnetPropertyId(394);

  /// Last State Change.
  static const lastStateChange = BacnetPropertyId(395);

  /// State Change Values.
  static const stateChangeValues = BacnetPropertyId(396);

  /// Timer Running.
  static const timerRunning = BacnetPropertyId(397);

  /// Timer State.
  static const timerState = BacnetPropertyId(398);

  /// APDU Length.
  static const apduLength = BacnetPropertyId(399);

  /// IP Address.
  static const ipAddress = BacnetPropertyId(400);

  /// IP Default Gateway.
  static const ipDefaultGateway = BacnetPropertyId(401);

  /// IP DHCP Enable.
  static const ipDhcpEnable = BacnetPropertyId(402);

  /// IP DHCP Lease Time.
  static const ipDhcpLeaseTime = BacnetPropertyId(403);

  /// IP DHCP Lease Time Remaining.
  static const ipDhcpLeaseTimeRemaining = BacnetPropertyId(404);

  /// IP DHCP Server.
  static const ipDhcpServer = BacnetPropertyId(405);

  /// IP DNS Server.
  static const ipDnsServer = BacnetPropertyId(406);

  /// BACnet IP Global Address.
  static const bacnetIpGlobalAddress = BacnetPropertyId(407);

  /// BACnet IP Mode.
  static const bacnetIpMode = BacnetPropertyId(408);

  /// BACnet IP Multicast Address.
  static const bacnetIpMulticastAddress = BacnetPropertyId(409);

  /// BACnet IP Nat Traversal.
  static const bacnetIpNatTraversal = BacnetPropertyId(410);

  /// IP Subnet Mask.
  static const ipSubnetMask = BacnetPropertyId(411);

  /// BACnet IP UDP Port.
  static const bacnetIpUdpPort = BacnetPropertyId(412);

  /// BBMD Accept FD Registrations.
  static const bbmdAcceptFdRegistrations = BacnetPropertyId(413);

  /// BBMD Broadcast Distribution Table.
  static const bbmdBroadcastDistributionTable = BacnetPropertyId(414);

  /// BBMD Foreign Device Table.
  static const bbmdForeignDeviceTable = BacnetPropertyId(415);

  /// Changes Pending.
  static const changesPending = BacnetPropertyId(416);

  /// Command.
  static const command = BacnetPropertyId(417);

  /// FD BBMD Address.
  static const fdBbmdAddress = BacnetPropertyId(418);

  /// FD Subscription Lifetime.
  static const fdSubscriptionLifetime = BacnetPropertyId(419);

  /// Link Speed.
  static const linkSpeed = BacnetPropertyId(420);

  /// Link Speeds.
  static const linkSpeeds = BacnetPropertyId(421);

  /// Link Speed Autonegotiate.
  static const linkSpeedAutonegotiate = BacnetPropertyId(422);

  /// MAC Address.
  static const macAddress = BacnetPropertyId(423);

  /// Network Interface Name.
  static const networkInterfaceName = BacnetPropertyId(424);

  /// Network Number.
  static const networkNumber = BacnetPropertyId(425);

  /// Network Number Quality.
  static const networkNumberQuality = BacnetPropertyId(426);

  /// Network Type.
  static const networkType = BacnetPropertyId(427);

  /// Routing Table.
  static const routingTable = BacnetPropertyId(428);

  /// Virtual MAC Address Table.
  static const virtualMacAddressTable = BacnetPropertyId(429);

  /// Command Time Array.
  static const commandTimeArray = BacnetPropertyId(430);

  /// Current Command Priority.
  static const currentCommandPriority = BacnetPropertyId(431);

  /// Last Command Time.
  static const lastCommandTime = BacnetPropertyId(432);

  /// Value Source.
  static const valueSource = BacnetPropertyId(433);

  /// Value Source Array.
  static const valueSourceArray = BacnetPropertyId(434);

  /// BACnet IPv6 Mode.
  static const bacnetIpv6Mode = BacnetPropertyId(435);

  /// IPv6 Address.
  static const ipv6Address = BacnetPropertyId(436);

  /// IPv6 Prefix Length.
  static const ipv6PrefixLength = BacnetPropertyId(437);

  /// BACnet IPv6 UDP Port.
  static const bacnetIpv6UdpPort = BacnetPropertyId(438);

  /// IPv6 Default Gateway.
  static const ipv6DefaultGateway = BacnetPropertyId(439);

  /// BACnet IPv6 Multicast Address.
  static const bacnetIpv6MulticastAddress = BacnetPropertyId(440);

  /// IPv6 DNS Server.
  static const ipv6DnsServer = BacnetPropertyId(441);

  /// IPv6 Auto Addressing Enable.
  static const ipv6AutoAddressingEnable = BacnetPropertyId(442);

  /// IPv6 DHCP Lease Time.
  static const ipv6DhcpLeaseTime = BacnetPropertyId(443);

  /// IPv6 DHCP Lease Time Remaining.
  static const ipv6DhcpLeaseTimeRemaining = BacnetPropertyId(444);

  /// IPv6 DHCP Server.
  static const ipv6DhcpServer = BacnetPropertyId(445);

  /// IPv6 Zone Index.
  static const ipv6ZoneIndex = BacnetPropertyId(446);

  /// Assigned Landing Calls.
  static const assignedLandingCalls = BacnetPropertyId(447);

  /// Car Assigned Direction.
  static const carAssignedDirection = BacnetPropertyId(448);

  /// Car Door Command.
  static const carDoorCommand = BacnetPropertyId(449);

  /// Car Door Status.
  static const carDoorStatus = BacnetPropertyId(450);

  /// Car Door Text.
  static const carDoorText = BacnetPropertyId(451);

  /// Car Door Zone.
  static const carDoorZone = BacnetPropertyId(452);

  /// Car Drive Status.
  static const carDriveStatus = BacnetPropertyId(453);

  /// Car Load.
  static const carLoad = BacnetPropertyId(454);

  /// Car Load Units.
  static const carLoadUnits = BacnetPropertyId(455);

  /// Car Mode.
  static const carMode = BacnetPropertyId(456);

  /// Car Moving Direction.
  static const carMovingDirection = BacnetPropertyId(457);

  /// Car Position.
  static const carPosition = BacnetPropertyId(458);

  /// Elevator Group.
  static const elevatorGroup = BacnetPropertyId(459);

  /// Energy Meter.
  static const energyMeter = BacnetPropertyId(460);

  /// Energy Meter Ref.
  static const energyMeterRef = BacnetPropertyId(461);

  /// Escalator Mode.
  static const escalatorMode = BacnetPropertyId(462);

  /// Fault Signals.
  static const faultSignals = BacnetPropertyId(463);

  /// Floor Text.
  static const floorText = BacnetPropertyId(464);

  /// Group ID.
  static const groupId = BacnetPropertyId(465);

  /// Group Mode.
  static const groupMode = BacnetPropertyId(467);

  /// Higher Deck.
  static const higherDeck = BacnetPropertyId(468);

  /// Installation ID.
  static const installationId = BacnetPropertyId(469);

  /// Landing Calls.
  static const landingCalls = BacnetPropertyId(470);

  /// Landing Call Control.
  static const landingCallControl = BacnetPropertyId(471);

  /// Landing Door Status.
  static const landingDoorStatus = BacnetPropertyId(472);

  /// Lower Deck.
  static const lowerDeck = BacnetPropertyId(473);

  /// Machine Room ID.
  static const machineRoomId = BacnetPropertyId(474);

  /// Making Car Call.
  static const makingCarCall = BacnetPropertyId(475);

  /// Next Stopping Floor.
  static const nextStoppingFloor = BacnetPropertyId(476);

  /// Operation Direction.
  static const operationDirection = BacnetPropertyId(477);

  /// Passenger Alarm.
  static const passengerAlarm = BacnetPropertyId(478);

  /// Power Mode.
  static const powerMode = BacnetPropertyId(479);

  /// Registered Car Call.
  static const registeredCarCall = BacnetPropertyId(480);

  /// Active COV Multiple Subscriptions.
  static const activeCovMultipleSubscriptions = BacnetPropertyId(481);

  /// Protocol Level.
  static const protocolLevel = BacnetPropertyId(482);

  /// Reference Port.
  static const referencePort = BacnetPropertyId(483);

  /// Deployed Profile Location.
  static const deployedProfileLocation = BacnetPropertyId(484);

  /// Profile Location.
  static const profileLocation = BacnetPropertyId(485);

  /// Tags.
  static const tags = BacnetPropertyId(486);

  /// Subordinate Node Types.
  static const subordinateNodeTypes = BacnetPropertyId(487);

  /// Subordinate Tags.
  static const subordinateTags = BacnetPropertyId(488);

  /// Subordinate Relationships.
  static const subordinateRelationships = BacnetPropertyId(489);

  /// Default Subordinate Relationship.
  static const defaultSubordinateRelationship = BacnetPropertyId(490);

  /// Represents.
  static const represents = BacnetPropertyId(491);

  /// Default Present Value.
  static const defaultPresentValue = BacnetPropertyId(492);

  /// Present Stage.
  static const presentStage = BacnetPropertyId(493);

  /// Stages.
  static const stages = BacnetPropertyId(494);

  /// Stage Names.
  static const stageNames = BacnetPropertyId(495);

  /// Target References.
  static const targetReferences = BacnetPropertyId(496);

  /// Audit Source Level.
  static const auditSourceLevel = BacnetPropertyId(497);

  /// Audit Level.
  static const auditLevel = BacnetPropertyId(498);

  /// Audit Notification Recipient.
  static const auditNotificationRecipient = BacnetPropertyId(499);

  /// Audit Priority Filter.
  static const auditPriorityFilter = BacnetPropertyId(500);

  /// Auditable Operations.
  static const auditableOperations = BacnetPropertyId(501);

  /// Delete On Forward.
  static const deleteOnForward = BacnetPropertyId(502);

  /// Maximum Send Delay.
  static const maximumSendDelay = BacnetPropertyId(503);

  /// Monitored Objects.
  static const monitoredObjects = BacnetPropertyId(504);

  /// Send Now.
  static const sendNow = BacnetPropertyId(505);

  /// Floor Number.
  static const floorNumber = BacnetPropertyId(506);

  /// Device UUID.
  static const deviceUuid = BacnetPropertyId(507);

  /// Additional Reference Ports.
  static const additionalReferencePorts = BacnetPropertyId(508);

  /// Certificate Signing Request File.
  static const certificateSigningRequestFile = BacnetPropertyId(509);

  /// Command Validation Result.
  static const commandValidationResult = BacnetPropertyId(510);

  /// Issuer Certificate Files.
  static const issuerCertificateFiles = BacnetPropertyId(511);

  /// Max Bvlc Length Accepted.
  static const maxBvlcLengthAccepted = BacnetPropertyId(4194304);

  /// Max NPDU Length Accepted.
  static const maxNpduLengthAccepted = BacnetPropertyId(4194305);

  /// Operational Certificate File.
  static const operationalCertificateFile = BacnetPropertyId(4194306);

  /// Current Health.
  static const currentHealth = BacnetPropertyId(4194307);

  /// SC Connect Wait Timeout.
  static const scConnectWaitTimeout = BacnetPropertyId(4194308);

  /// SC Direct Connect Accept Enable.
  static const scDirectConnectAcceptEnable = BacnetPropertyId(4194309);

  /// SC Direct Connect Accept Uris.
  static const scDirectConnectAcceptUris = BacnetPropertyId(4194310);

  /// SC Direct Connect Binding.
  static const scDirectConnectBinding = BacnetPropertyId(4194311);

  /// SC Direct Connect Connection Status.
  static const scDirectConnectConnectionStatus = BacnetPropertyId(4194312);

  /// SC Direct Connect Initiate Enable.
  static const scDirectConnectInitiateEnable = BacnetPropertyId(4194313);

  /// SC Disconnect Wait Timeout.
  static const scDisconnectWaitTimeout = BacnetPropertyId(4194314);

  /// SC Failed Connection Requests.
  static const scFailedConnectionRequests = BacnetPropertyId(4194315);

  /// SC Failover Hub Connection Status.
  static const scFailoverHubConnectionStatus = BacnetPropertyId(4194316);

  /// SC Failover Hub Uri.
  static const scFailoverHubUri = BacnetPropertyId(4194317);

  /// SC Hub Connector State.
  static const scHubConnectorState = BacnetPropertyId(4194318);

  /// SC Hub Function Accept Uris.
  static const scHubFunctionAcceptUris = BacnetPropertyId(4194319);

  /// SC Hub Function Binding.
  static const scHubFunctionBinding = BacnetPropertyId(4194320);

  /// SC Hub Function Connection Status.
  static const scHubFunctionConnectionStatus = BacnetPropertyId(4194321);

  /// SC Hub Function Enable.
  static const scHubFunctionEnable = BacnetPropertyId(4194322);

  /// SC Heartbeat Timeout.
  static const scHeartbeatTimeout = BacnetPropertyId(4194323);

  /// SC Primary Hub Connection Status.
  static const scPrimaryHubConnectionStatus = BacnetPropertyId(4194324);

  /// SC Primary Hub Uri.
  static const scPrimaryHubUri = BacnetPropertyId(4194325);

  /// SC Maximum Reconnect Time.
  static const scMaximumReconnectTime = BacnetPropertyId(4194326);

  /// SC Minimum Reconnect Time.
  static const scMinimumReconnectTime = BacnetPropertyId(4194327);

  /// Color Override.
  static const colorOverride = BacnetPropertyId(4194328);

  /// Color Reference.
  static const colorReference = BacnetPropertyId(4194329);

  /// Default Color.
  static const defaultColor = BacnetPropertyId(4194330);

  /// Default Color Temperature.
  static const defaultColorTemperature = BacnetPropertyId(4194331);

  /// Override Color Reference.
  static const overrideColorReference = BacnetPropertyId(4194332);

  /// Write Every Scheduled Action.
  static const writeEveryScheduledAction = BacnetPropertyId(4194333);

  /// Color Command.
  static const colorCommand = BacnetPropertyId(4194334);

  /// High End Trim.
  static const highEndTrim = BacnetPropertyId(4194335);

  /// Low End Trim.
  static const lowEndTrim = BacnetPropertyId(4194336);

  /// Trim Fade Time.
  static const trimFadeTime = BacnetPropertyId(4194337);

  /// Device Address Proxy Enable.
  static const deviceAddressProxyEnable = BacnetPropertyId(4194338);

  /// Device Address Proxy Table.
  static const deviceAddressProxyTable = BacnetPropertyId(4194339);

  /// Device Address Proxy Timeout.
  static const deviceAddressProxyTimeout = BacnetPropertyId(4194340);

  /// Default On Value.
  static const defaultOnValue = BacnetPropertyId(4194341);

  /// Last On Value.
  static const lastOnValue = BacnetPropertyId(4194342);

  /// Authorization Cache.
  static const authorizationCache = BacnetPropertyId(4194343);

  /// Authorization Groups.
  static const authorizationGroups = BacnetPropertyId(4194344);

  /// Authorization Policy.
  static const authorizationPolicy = BacnetPropertyId(4194345);

  /// Authorization Scope.
  static const authorizationScope = BacnetPropertyId(4194346);

  /// Authorization Server.
  static const authorizationServer = BacnetPropertyId(4194347);

  /// Authorization Status.
  static const authorizationStatus = BacnetPropertyId(4194348);

  /// Max Proxied I Ams Per Second.
  static const maxProxiedIAmsPerSecond = BacnetPropertyId(4194349);

  static const Map<BacnetPropertyId, String> _labels = {
    ackedTransitions: 'Acked Transitions',
    ackRequired: 'Ack Required',
    action: 'Action',
    actionText: 'Action Text',
    activeText: 'Active Text',
    activeVtSessions: 'Active VT Sessions',
    alarmValue: 'Alarm Value',
    alarmValues: 'Alarm Values',
    all: 'All',
    allWritesSuccessful: 'All Writes Successful',
    apduSegmentTimeout: 'APDU Segment Timeout',
    apduTimeout: 'APDU Timeout',
    applicationSoftwareVersion: 'Application Software Version',
    archive: 'Archive',
    bias: 'Bias',
    changeOfStateCount: 'Change Of State Count',
    changeOfStateTime: 'Change Of State Time',
    notificationClass: 'Notification Class',
    controlledVariableReference: 'Controlled Variable Reference',
    controlledVariableUnits: 'Controlled Variable Units',
    controlledVariableValue: 'Controlled Variable Value',
    covIncrement: 'COV Increment',
    dateList: 'Date List',
    daylightSavingsStatus: 'Daylight Savings Status',
    deadband: 'Deadband',
    derivativeConstant: 'Derivative Constant',
    derivativeConstantUnits: 'Derivative Constant Units',
    description: 'Description',
    descriptionOfHalt: 'Description Of Halt',
    deviceAddressBinding: 'Device Address Binding',
    deviceType: 'Device Type',
    effectivePeriod: 'Effective Period',
    elapsedActiveTime: 'Elapsed Active Time',
    errorLimit: 'Error Limit',
    eventEnable: 'Event Enable',
    eventState: 'Event State',
    eventType: 'Event Type',
    exceptionSchedule: 'Exception Schedule',
    faultValues: 'Fault Values',
    feedbackValue: 'Feedback Value',
    fileAccessMethod: 'File Access Method',
    fileSize: 'File Size',
    fileType: 'File Type',
    firmwareRevision: 'Firmware Revision',
    highLimit: 'High Limit',
    inactiveText: 'Inactive Text',
    inProcess: 'In Process',
    instanceOf: 'Instance Of',
    integralConstant: 'Integral Constant',
    integralConstantUnits: 'Integral Constant Units',
    issueConfirmedNotifications: 'Issue Confirmed Notifications',
    limitEnable: 'Limit Enable',
    listOfGroupMembers: 'List Of Group Members',
    listOfObjectPropertyReferences: 'List Of Object Property References',
    listOfSessionKeys: 'List Of Session Keys',
    localDate: 'Local Date',
    localTime: 'Local Time',
    location: 'Location',
    lowLimit: 'Low Limit',
    manipulatedVariableReference: 'Manipulated Variable Reference',
    maximumOutput: 'Maximum Output',
    maxApduLengthAccepted: 'Max APDU Length Accepted',
    maxInfoFrames: 'Max Info Frames',
    maxMaster: 'Max Master',
    maxPresValue: 'Max Pres Value',
    minimumOffTime: 'Minimum Off Time',
    minimumOnTime: 'Minimum On Time',
    minimumOutput: 'Minimum Output',
    minPresValue: 'Min Pres Value',
    modelName: 'Model Name',
    modificationDate: 'Modification Date',
    notifyType: 'Notify Type',
    numberOfApduRetries: 'Number Of APDU Retries',
    numberOfStates: 'Number Of States',
    objectIdentifier: 'Object Identifier',
    objectList: 'Object List',
    objectName: 'Object Name',
    objectPropertyReference: 'Object Property Reference',
    objectType: 'Object Type',
    optional: 'Optional',
    outOfService: 'Out Of Service',
    outputUnits: 'Output Units',
    eventParameters: 'Event Parameters',
    polarity: 'Polarity',
    presentValue: 'Present Value',
    priority: 'Priority',
    priorityArray: 'Priority Array',
    priorityForWriting: 'Priority For Writing',
    processIdentifier: 'Process Identifier',
    programChange: 'Program Change',
    programLocation: 'Program Location',
    programState: 'Program State',
    proportionalConstant: 'Proportional Constant',
    proportionalConstantUnits: 'Proportional Constant Units',
    protocolConformanceClass: 'Protocol Conformance Class',
    protocolObjectTypesSupported: 'Protocol Object Types Supported',
    protocolServicesSupported: 'Protocol Services Supported',
    protocolVersion: 'Protocol Version',
    readOnly: 'Read Only',
    reasonForHalt: 'Reason For Halt',
    recipient: 'Recipient',
    recipientList: 'Recipient List',
    reliability: 'Reliability',
    relinquishDefault: 'Relinquish Default',
    required: 'Required',
    resolution: 'Resolution',
    segmentationSupported: 'Segmentation Supported',
    setpoint: 'Setpoint',
    setpointReference: 'Setpoint Reference',
    stateText: 'State Text',
    statusFlags: 'Status Flags',
    systemStatus: 'System Status',
    timeDelay: 'Time Delay',
    timeOfActiveTimeReset: 'Time Of Active Time Reset',
    timeOfStateCountReset: 'Time Of State Count Reset',
    timeSynchronizationRecipients: 'Time Synchronization Recipients',
    units: 'Units',
    updateInterval: 'Update Interval',
    utcOffset: 'UTC Offset',
    vendorIdentifier: 'Vendor Identifier',
    vendorName: 'Vendor Name',
    vtClassesSupported: 'VT Classes Supported',
    weeklySchedule: 'Weekly Schedule',
    attemptedSamples: 'Attempted Samples',
    averageValue: 'Average Value',
    bufferSize: 'Buffer Size',
    clientCovIncrement: 'Client COV Increment',
    covResubscriptionInterval: 'COV Resubscription Interval',
    currentNotifyTime: 'Current Notify Time',
    eventTimeStamps: 'Event Time Stamps',
    logBuffer: 'Log Buffer',
    logDeviceObjectProperty: 'Log Device Object Property',
    enable: 'Enable',
    logInterval: 'Log Interval',
    maximumValue: 'Maximum Value',
    minimumValue: 'Minimum Value',
    notificationThreshold: 'Notification Threshold',
    previousNotifyTime: 'Previous Notify Time',
    protocolRevision: 'Protocol Revision',
    recordsSinceNotification: 'Records Since Notification',
    recordCount: 'Record Count',
    startTime: 'Start Time',
    stopTime: 'Stop Time',
    stopWhenFull: 'Stop When Full',
    totalRecordCount: 'Total Record Count',
    validSamples: 'Valid Samples',
    windowInterval: 'Window Interval',
    windowSamples: 'Window Samples',
    maximumValueTimestamp: 'Maximum Value Timestamp',
    minimumValueTimestamp: 'Minimum Value Timestamp',
    varianceValue: 'Variance Value',
    activeCovSubscriptions: 'Active COV Subscriptions',
    backupFailureTimeout: 'Backup Failure Timeout',
    configurationFiles: 'Configuration Files',
    databaseRevision: 'Database Revision',
    directReading: 'Direct Reading',
    lastRestoreTime: 'Last Restore Time',
    maintenanceRequired: 'Maintenance Required',
    memberOf: 'Member Of',
    mode: 'Mode',
    operationExpected: 'Operation Expected',
    setting: 'Setting',
    silenced: 'Silenced',
    trackingValue: 'Tracking Value',
    zoneMembers: 'Zone Members',
    lifeSafetyAlarmValues: 'Life Safety Alarm Values',
    maxSegmentsAccepted: 'Max Segments Accepted',
    profileName: 'Profile Name',
    autoSlaveDiscovery: 'Auto Slave Discovery',
    manualSlaveAddressBinding: 'Manual Slave Address Binding',
    slaveAddressBinding: 'Slave Address Binding',
    slaveProxyEnable: 'Slave Proxy Enable',
    lastNotifyRecord: 'Last Notify Record',
    scheduleDefault: 'Schedule Default',
    acceptedModes: 'Accepted Modes',
    adjustValue: 'Adjust Value',
    count: 'Count',
    countBeforeChange: 'Count Before Change',
    countChangeTime: 'Count Change Time',
    covPeriod: 'COV Period',
    inputReference: 'Input Reference',
    limitMonitoringInterval: 'Limit Monitoring Interval',
    loggingObject: 'Logging Object',
    loggingRecord: 'Logging Record',
    prescale: 'Prescale',
    pulseRate: 'Pulse Rate',
    scale: 'Scale',
    scaleFactor: 'Scale Factor',
    updateTime: 'Update Time',
    valueBeforeChange: 'Value Before Change',
    valueSet: 'Value Set',
    valueChangeTime: 'Value Change Time',
    alignIntervals: 'Align Intervals',
    intervalOffset: 'Interval Offset',
    lastRestartReason: 'Last Restart Reason',
    loggingType: 'Logging Type',
    restartNotificationRecipients: 'Restart Notification Recipients',
    timeOfDeviceRestart: 'Time Of Device Restart',
    timeSynchronizationInterval: 'Time Synchronization Interval',
    trigger: 'Trigger',
    utcTimeSynchronizationRecipients: 'UTC Time Synchronization Recipients',
    nodeSubtype: 'Node Subtype',
    nodeType: 'Node Type',
    structuredObjectList: 'Structured Object List',
    subordinateAnnotations: 'Subordinate Annotations',
    subordinateList: 'Subordinate List',
    actualShedLevel: 'Actual Shed Level',
    dutyWindow: 'Duty Window',
    expectedShedLevel: 'Expected Shed Level',
    fullDutyBaseline: 'Full Duty Baseline',
    requestedShedLevel: 'Requested Shed Level',
    shedDuration: 'Shed Duration',
    shedLevelDescriptions: 'Shed Level Descriptions',
    shedLevels: 'Shed Levels',
    stateDescription: 'State Description',
    doorAlarmState: 'Door Alarm State',
    doorExtendedPulseTime: 'Door Extended Pulse Time',
    doorMembers: 'Door Members',
    doorOpenTooLongTime: 'Door Open Too Long Time',
    doorPulseTime: 'Door Pulse Time',
    doorStatus: 'Door Status',
    doorUnlockDelayTime: 'Door Unlock Delay Time',
    lockStatus: 'Lock Status',
    maskedAlarmValues: 'Masked Alarm Values',
    securedStatus: 'Secured Status',
    absenteeLimit: 'Absentee Limit',
    accessAlarmEvents: 'Access Alarm Events',
    accessDoors: 'Access Doors',
    accessEvent: 'Access Event',
    accessEventAuthenticationFactor: 'Access Event Authentication Factor',
    accessEventCredential: 'Access Event Credential',
    accessEventTime: 'Access Event Time',
    accessTransactionEvents: 'Access Transaction Events',
    accompaniment: 'Accompaniment',
    accompanimentTime: 'Accompaniment Time',
    activationTime: 'Activation Time',
    activeAuthenticationPolicy: 'Active Authentication Policy',
    assignedAccessRights: 'Assigned Access Rights',
    authenticationFactors: 'Authentication Factors',
    authenticationPolicyList: 'Authentication Policy List',
    authenticationPolicyNames: 'Authentication Policy Names',
    authenticationStatus: 'Authentication Status',
    authorizationMode: 'Authorization Mode',
    belongsTo: 'Belongs To',
    credentialDisable: 'Credential Disable',
    credentialStatus: 'Credential Status',
    credentials: 'Credentials',
    credentialsInZone: 'Credentials In Zone',
    daysRemaining: 'Days Remaining',
    entryPoints: 'Entry Points',
    exitPoints: 'Exit Points',
    expirationTime: 'Expiration Time',
    extendedTimeEnable: 'Extended Time Enable',
    failedAttemptEvents: 'Failed Attempt Events',
    failedAttempts: 'Failed Attempts',
    failedAttemptsTime: 'Failed Attempts Time',
    lastAccessEvent: 'Last Access Event',
    lastAccessPoint: 'Last Access Point',
    lastCredentialAdded: 'Last Credential Added',
    lastCredentialAddedTime: 'Last Credential Added Time',
    lastCredentialRemoved: 'Last Credential Removed',
    lastCredentialRemovedTime: 'Last Credential Removed Time',
    lastUseTime: 'Last Use Time',
    lockout: 'Lockout',
    lockoutRelinquishTime: 'Lockout Relinquish Time',
    masterExemption: 'Master Exemption',
    maxFailedAttempts: 'Max Failed Attempts',
    members: 'Members',
    musterPoint: 'Muster Point',
    negativeAccessRules: 'Negative Access Rules',
    numberOfAuthenticationPolicies: 'Number Of Authentication Policies',
    occupancyCount: 'Occupancy Count',
    occupancyCountAdjust: 'Occupancy Count Adjust',
    occupancyCountEnable: 'Occupancy Count Enable',
    occupancyExemption: 'Occupancy Exemption',
    occupancyLowerLimit: 'Occupancy Lower Limit',
    occupancyLowerLimitEnforced: 'Occupancy Lower Limit Enforced',
    occupancyState: 'Occupancy State',
    occupancyUpperLimit: 'Occupancy Upper Limit',
    occupancyUpperLimitEnforced: 'Occupancy Upper Limit Enforced',
    passbackExemption: 'Passback Exemption',
    passbackMode: 'Passback Mode',
    passbackTimeout: 'Passback Timeout',
    positiveAccessRules: 'Positive Access Rules',
    reasonForDisable: 'Reason For Disable',
    supportedFormats: 'Supported Formats',
    supportedFormatClasses: 'Supported Format Classes',
    threatAuthority: 'Threat Authority',
    threatLevel: 'Threat Level',
    traceFlag: 'Trace Flag',
    transactionNotificationClass: 'Transaction Notification Class',
    userExternalIdentifier: 'User External Identifier',
    userInformationReference: 'User Information Reference',
    userName: 'User Name',
    userType: 'User Type',
    usesRemaining: 'Uses Remaining',
    zoneFrom: 'Zone From',
    zoneTo: 'Zone To',
    accessEventTag: 'Access Event Tag',
    globalIdentifier: 'Global Identifier',
    verificationTime: 'Verification Time',
    baseDeviceSecurityPolicy: 'Base Device Security Policy',
    distributionKeyRevision: 'Distribution Key Revision',
    doNotHide: 'Do Not Hide',
    keySets: 'Key Sets',
    lastKeyServer: 'Last Key Server',
    networkAccessSecurityPolicies: 'Network Access Security Policies',
    packetReorderTime: 'Packet Reorder Time',
    securityPduTimeout: 'Security Pdu Timeout',
    securityTimeWindow: 'Security Time Window',
    supportedSecurityAlgorithm: 'Supported Security Algorithm',
    updateKeySetTimeout: 'Update Key Set Timeout',
    backupAndRestoreState: 'Backup And Restore State',
    backupPreparationTime: 'Backup Preparation Time',
    restoreCompletionTime: 'Restore Completion Time',
    restorePreparationTime: 'Restore Preparation Time',
    bitMask: 'Bit Mask',
    bitText: 'Bit Text',
    isUtc: 'Is UTC',
    groupMembers: 'Group Members',
    groupMemberNames: 'Group Member Names',
    memberStatusFlags: 'Member Status Flags',
    requestedUpdateInterval: 'Requested Update Interval',
    covuPeriod: 'Covu Period',
    covuRecipients: 'Covu Recipients',
    eventMessageTexts: 'Event Message Texts',
    eventMessageTextsConfig: 'Event Message Texts Config',
    eventDetectionEnable: 'Event Detection Enable',
    eventAlgorithmInhibit: 'Event Algorithm Inhibit',
    eventAlgorithmInhibitRef: 'Event Algorithm Inhibit Ref',
    timeDelayNormal: 'Time Delay Normal',
    reliabilityEvaluationInhibit: 'Reliability Evaluation Inhibit',
    faultParameters: 'Fault Parameters',
    faultType: 'Fault Type',
    localForwardingOnly: 'Local Forwarding Only',
    processIdentifierFilter: 'Process Identifier Filter',
    subscribedRecipients: 'Subscribed Recipients',
    portFilter: 'Port Filter',
    authorizationExemptions: 'Authorization Exemptions',
    allowGroupDelayInhibit: 'Allow Group Delay Inhibit',
    channelNumber: 'Channel Number',
    controlGroups: 'Control Groups',
    executionDelay: 'Execution Delay',
    lastPriority: 'Last Priority',
    writeStatus: 'Write Status',
    propertyList: 'Property List',
    serialNumber: 'Serial Number',
    blinkWarnEnable: 'Blink Warn Enable',
    defaultFadeTime: 'Default Fade Time',
    defaultRampRate: 'Default Ramp Rate',
    defaultStepIncrement: 'Default Step Increment',
    egressTime: 'Egress Time',
    inProgress: 'In Progress',
    instantaneousPower: 'Instantaneous Power',
    lightingCommand: 'Lighting Command',
    lightingCommandDefaultPriority: 'Lighting Command Default Priority',
    maxActualValue: 'Max Actual Value',
    minActualValue: 'Min Actual Value',
    power: 'Power',
    transition: 'Transition',
    egressActive: 'Egress Active',
    interfaceValue: 'Interface Value',
    faultHighLimit: 'Fault High Limit',
    faultLowLimit: 'Fault Low Limit',
    lowDiffLimit: 'Low Diff Limit',
    strikeCount: 'Strike Count',
    timeOfStrikeCountReset: 'Time Of Strike Count Reset',
    defaultTimeout: 'Default Timeout',
    initialTimeout: 'Initial Timeout',
    lastStateChange: 'Last State Change',
    stateChangeValues: 'State Change Values',
    timerRunning: 'Timer Running',
    timerState: 'Timer State',
    apduLength: 'APDU Length',
    ipAddress: 'IP Address',
    ipDefaultGateway: 'IP Default Gateway',
    ipDhcpEnable: 'IP DHCP Enable',
    ipDhcpLeaseTime: 'IP DHCP Lease Time',
    ipDhcpLeaseTimeRemaining: 'IP DHCP Lease Time Remaining',
    ipDhcpServer: 'IP DHCP Server',
    ipDnsServer: 'IP DNS Server',
    bacnetIpGlobalAddress: 'BACnet IP Global Address',
    bacnetIpMode: 'BACnet IP Mode',
    bacnetIpMulticastAddress: 'BACnet IP Multicast Address',
    bacnetIpNatTraversal: 'BACnet IP Nat Traversal',
    ipSubnetMask: 'IP Subnet Mask',
    bacnetIpUdpPort: 'BACnet IP UDP Port',
    bbmdAcceptFdRegistrations: 'BBMD Accept FD Registrations',
    bbmdBroadcastDistributionTable: 'BBMD Broadcast Distribution Table',
    bbmdForeignDeviceTable: 'BBMD Foreign Device Table',
    changesPending: 'Changes Pending',
    command: 'Command',
    fdBbmdAddress: 'FD BBMD Address',
    fdSubscriptionLifetime: 'FD Subscription Lifetime',
    linkSpeed: 'Link Speed',
    linkSpeeds: 'Link Speeds',
    linkSpeedAutonegotiate: 'Link Speed Autonegotiate',
    macAddress: 'MAC Address',
    networkInterfaceName: 'Network Interface Name',
    networkNumber: 'Network Number',
    networkNumberQuality: 'Network Number Quality',
    networkType: 'Network Type',
    routingTable: 'Routing Table',
    virtualMacAddressTable: 'Virtual MAC Address Table',
    commandTimeArray: 'Command Time Array',
    currentCommandPriority: 'Current Command Priority',
    lastCommandTime: 'Last Command Time',
    valueSource: 'Value Source',
    valueSourceArray: 'Value Source Array',
    bacnetIpv6Mode: 'BACnet IPv6 Mode',
    ipv6Address: 'IPv6 Address',
    ipv6PrefixLength: 'IPv6 Prefix Length',
    bacnetIpv6UdpPort: 'BACnet IPv6 UDP Port',
    ipv6DefaultGateway: 'IPv6 Default Gateway',
    bacnetIpv6MulticastAddress: 'BACnet IPv6 Multicast Address',
    ipv6DnsServer: 'IPv6 DNS Server',
    ipv6AutoAddressingEnable: 'IPv6 Auto Addressing Enable',
    ipv6DhcpLeaseTime: 'IPv6 DHCP Lease Time',
    ipv6DhcpLeaseTimeRemaining: 'IPv6 DHCP Lease Time Remaining',
    ipv6DhcpServer: 'IPv6 DHCP Server',
    ipv6ZoneIndex: 'IPv6 Zone Index',
    assignedLandingCalls: 'Assigned Landing Calls',
    carAssignedDirection: 'Car Assigned Direction',
    carDoorCommand: 'Car Door Command',
    carDoorStatus: 'Car Door Status',
    carDoorText: 'Car Door Text',
    carDoorZone: 'Car Door Zone',
    carDriveStatus: 'Car Drive Status',
    carLoad: 'Car Load',
    carLoadUnits: 'Car Load Units',
    carMode: 'Car Mode',
    carMovingDirection: 'Car Moving Direction',
    carPosition: 'Car Position',
    elevatorGroup: 'Elevator Group',
    energyMeter: 'Energy Meter',
    energyMeterRef: 'Energy Meter Ref',
    escalatorMode: 'Escalator Mode',
    faultSignals: 'Fault Signals',
    floorText: 'Floor Text',
    groupId: 'Group ID',
    groupMode: 'Group Mode',
    higherDeck: 'Higher Deck',
    installationId: 'Installation ID',
    landingCalls: 'Landing Calls',
    landingCallControl: 'Landing Call Control',
    landingDoorStatus: 'Landing Door Status',
    lowerDeck: 'Lower Deck',
    machineRoomId: 'Machine Room ID',
    makingCarCall: 'Making Car Call',
    nextStoppingFloor: 'Next Stopping Floor',
    operationDirection: 'Operation Direction',
    passengerAlarm: 'Passenger Alarm',
    powerMode: 'Power Mode',
    registeredCarCall: 'Registered Car Call',
    activeCovMultipleSubscriptions: 'Active COV Multiple Subscriptions',
    protocolLevel: 'Protocol Level',
    referencePort: 'Reference Port',
    deployedProfileLocation: 'Deployed Profile Location',
    profileLocation: 'Profile Location',
    tags: 'Tags',
    subordinateNodeTypes: 'Subordinate Node Types',
    subordinateTags: 'Subordinate Tags',
    subordinateRelationships: 'Subordinate Relationships',
    defaultSubordinateRelationship: 'Default Subordinate Relationship',
    represents: 'Represents',
    defaultPresentValue: 'Default Present Value',
    presentStage: 'Present Stage',
    stages: 'Stages',
    stageNames: 'Stage Names',
    targetReferences: 'Target References',
    auditSourceLevel: 'Audit Source Level',
    auditLevel: 'Audit Level',
    auditNotificationRecipient: 'Audit Notification Recipient',
    auditPriorityFilter: 'Audit Priority Filter',
    auditableOperations: 'Auditable Operations',
    deleteOnForward: 'Delete On Forward',
    maximumSendDelay: 'Maximum Send Delay',
    monitoredObjects: 'Monitored Objects',
    sendNow: 'Send Now',
    floorNumber: 'Floor Number',
    deviceUuid: 'Device UUID',
    additionalReferencePorts: 'Additional Reference Ports',
    certificateSigningRequestFile: 'Certificate Signing Request File',
    commandValidationResult: 'Command Validation Result',
    issuerCertificateFiles: 'Issuer Certificate Files',
    maxBvlcLengthAccepted: 'Max Bvlc Length Accepted',
    maxNpduLengthAccepted: 'Max NPDU Length Accepted',
    operationalCertificateFile: 'Operational Certificate File',
    currentHealth: 'Current Health',
    scConnectWaitTimeout: 'SC Connect Wait Timeout',
    scDirectConnectAcceptEnable: 'SC Direct Connect Accept Enable',
    scDirectConnectAcceptUris: 'SC Direct Connect Accept Uris',
    scDirectConnectBinding: 'SC Direct Connect Binding',
    scDirectConnectConnectionStatus: 'SC Direct Connect Connection Status',
    scDirectConnectInitiateEnable: 'SC Direct Connect Initiate Enable',
    scDisconnectWaitTimeout: 'SC Disconnect Wait Timeout',
    scFailedConnectionRequests: 'SC Failed Connection Requests',
    scFailoverHubConnectionStatus: 'SC Failover Hub Connection Status',
    scFailoverHubUri: 'SC Failover Hub Uri',
    scHubConnectorState: 'SC Hub Connector State',
    scHubFunctionAcceptUris: 'SC Hub Function Accept Uris',
    scHubFunctionBinding: 'SC Hub Function Binding',
    scHubFunctionConnectionStatus: 'SC Hub Function Connection Status',
    scHubFunctionEnable: 'SC Hub Function Enable',
    scHeartbeatTimeout: 'SC Heartbeat Timeout',
    scPrimaryHubConnectionStatus: 'SC Primary Hub Connection Status',
    scPrimaryHubUri: 'SC Primary Hub Uri',
    scMaximumReconnectTime: 'SC Maximum Reconnect Time',
    scMinimumReconnectTime: 'SC Minimum Reconnect Time',
    colorOverride: 'Color Override',
    colorReference: 'Color Reference',
    defaultColor: 'Default Color',
    defaultColorTemperature: 'Default Color Temperature',
    overrideColorReference: 'Override Color Reference',
    writeEveryScheduledAction: 'Write Every Scheduled Action',
    colorCommand: 'Color Command',
    highEndTrim: 'High End Trim',
    lowEndTrim: 'Low End Trim',
    trimFadeTime: 'Trim Fade Time',
    deviceAddressProxyEnable: 'Device Address Proxy Enable',
    deviceAddressProxyTable: 'Device Address Proxy Table',
    deviceAddressProxyTimeout: 'Device Address Proxy Timeout',
    defaultOnValue: 'Default On Value',
    lastOnValue: 'Last On Value',
    authorizationCache: 'Authorization Cache',
    authorizationGroups: 'Authorization Groups',
    authorizationPolicy: 'Authorization Policy',
    authorizationScope: 'Authorization Scope',
    authorizationServer: 'Authorization Server',
    authorizationStatus: 'Authorization Status',
    maxProxiedIAmsPerSecond: 'Max Proxied I Ams Per Second',
  };

  /// All values defined by this library.
  static Iterable<BacnetPropertyId> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Property $value';

  /// Human readable name of this value.
  String get label => getName(value);
}
