// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet property identifiers (BACnetPropertyIdentifier).
abstract final class BacnetPropertyId {
  /// Acked Transitions.
  static const int ackedTransitions = 0;

  /// Ack Required.
  static const int ackRequired = 1;

  /// Action.
  static const int action = 2;

  /// Action Text.
  static const int actionText = 3;

  /// Active Text.
  static const int activeText = 4;

  /// Active VT Sessions.
  static const int activeVtSessions = 5;

  /// Alarm Value.
  static const int alarmValue = 6;

  /// Alarm Values.
  static const int alarmValues = 7;

  /// All.
  static const int all = 8;

  /// All Writes Successful.
  static const int allWritesSuccessful = 9;

  /// APDU Segment Timeout.
  static const int apduSegmentTimeout = 10;

  /// APDU Timeout.
  static const int apduTimeout = 11;

  /// Application Software Version.
  static const int applicationSoftwareVersion = 12;

  /// Archive.
  static const int archive = 13;

  /// Bias.
  static const int bias = 14;

  /// Change Of State Count.
  static const int changeOfStateCount = 15;

  /// Change Of State Time.
  static const int changeOfStateTime = 16;

  /// Notification Class.
  static const int notificationClass = 17;

  /// Controlled Variable Reference.
  static const int controlledVariableReference = 19;

  /// Controlled Variable Units.
  static const int controlledVariableUnits = 20;

  /// Controlled Variable Value.
  static const int controlledVariableValue = 21;

  /// COV Increment.
  static const int covIncrement = 22;

  /// Date List.
  static const int dateList = 23;

  /// Daylight Savings Status.
  static const int daylightSavingsStatus = 24;

  /// Deadband.
  static const int deadband = 25;

  /// Derivative Constant.
  static const int derivativeConstant = 26;

  /// Derivative Constant Units.
  static const int derivativeConstantUnits = 27;

  /// Description.
  static const int description = 28;

  /// Description Of Halt.
  static const int descriptionOfHalt = 29;

  /// Device Address Binding.
  static const int deviceAddressBinding = 30;

  /// Device Type.
  static const int deviceType = 31;

  /// Effective Period.
  static const int effectivePeriod = 32;

  /// Elapsed Active Time.
  static const int elapsedActiveTime = 33;

  /// Error Limit.
  static const int errorLimit = 34;

  /// Event Enable.
  static const int eventEnable = 35;

  /// Event State.
  static const int eventState = 36;

  /// Event Type.
  static const int eventType = 37;

  /// Exception Schedule.
  static const int exceptionSchedule = 38;

  /// Fault Values.
  static const int faultValues = 39;

  /// Feedback Value.
  static const int feedbackValue = 40;

  /// File Access Method.
  static const int fileAccessMethod = 41;

  /// File Size.
  static const int fileSize = 42;

  /// File Type.
  static const int fileType = 43;

  /// Firmware Revision.
  static const int firmwareRevision = 44;

  /// High Limit.
  static const int highLimit = 45;

  /// Inactive Text.
  static const int inactiveText = 46;

  /// In Process.
  static const int inProcess = 47;

  /// Instance Of.
  static const int instanceOf = 48;

  /// Integral Constant.
  static const int integralConstant = 49;

  /// Integral Constant Units.
  static const int integralConstantUnits = 50;

  /// Issue Confirmed Notifications.
  static const int issueConfirmedNotifications = 51;

  /// Limit Enable.
  static const int limitEnable = 52;

  /// List Of Group Members.
  static const int listOfGroupMembers = 53;

  /// List Of Object Property References.
  static const int listOfObjectPropertyReferences = 54;

  /// List Of Session Keys.
  static const int listOfSessionKeys = 55;

  /// Local Date.
  static const int localDate = 56;

  /// Local Time.
  static const int localTime = 57;

  /// Location.
  static const int location = 58;

  /// Low Limit.
  static const int lowLimit = 59;

  /// Manipulated Variable Reference.
  static const int manipulatedVariableReference = 60;

  /// Maximum Output.
  static const int maximumOutput = 61;

  /// Max APDU Length Accepted.
  static const int maxApduLengthAccepted = 62;

  /// Max Info Frames.
  static const int maxInfoFrames = 63;

  /// Max Master.
  static const int maxMaster = 64;

  /// Max Pres Value.
  static const int maxPresValue = 65;

  /// Minimum Off Time.
  static const int minimumOffTime = 66;

  /// Minimum On Time.
  static const int minimumOnTime = 67;

  /// Minimum Output.
  static const int minimumOutput = 68;

  /// Min Pres Value.
  static const int minPresValue = 69;

  /// Model Name.
  static const int modelName = 70;

  /// Modification Date.
  static const int modificationDate = 71;

  /// Notify Type.
  static const int notifyType = 72;

  /// Number Of APDU Retries.
  static const int numberOfApduRetries = 73;

  /// Number Of States.
  static const int numberOfStates = 74;

  /// Object Identifier.
  static const int objectIdentifier = 75;

  /// Object List.
  static const int objectList = 76;

  /// Object Name.
  static const int objectName = 77;

  /// Object Property Reference.
  static const int objectPropertyReference = 78;

  /// Object Type.
  static const int objectType = 79;

  /// Optional.
  static const int optional = 80;

  /// Out Of Service.
  static const int outOfService = 81;

  /// Output Units.
  static const int outputUnits = 82;

  /// Event Parameters.
  static const int eventParameters = 83;

  /// Polarity.
  static const int polarity = 84;

  /// Present Value.
  static const int presentValue = 85;

  /// Priority.
  static const int priority = 86;

  /// Priority Array.
  static const int priorityArray = 87;

  /// Priority For Writing.
  static const int priorityForWriting = 88;

  /// Process Identifier.
  static const int processIdentifier = 89;

  /// Program Change.
  static const int programChange = 90;

  /// Program Location.
  static const int programLocation = 91;

  /// Program State.
  static const int programState = 92;

  /// Proportional Constant.
  static const int proportionalConstant = 93;

  /// Proportional Constant Units.
  static const int proportionalConstantUnits = 94;

  /// Protocol Conformance Class.
  static const int protocolConformanceClass = 95;

  /// Protocol Object Types Supported.
  static const int protocolObjectTypesSupported = 96;

  /// Protocol Services Supported.
  static const int protocolServicesSupported = 97;

  /// Protocol Version.
  static const int protocolVersion = 98;

  /// Read Only.
  static const int readOnly = 99;

  /// Reason For Halt.
  static const int reasonForHalt = 100;

  /// Recipient.
  static const int recipient = 101;

  /// Recipient List.
  static const int recipientList = 102;

  /// Reliability.
  static const int reliability = 103;

  /// Relinquish Default.
  static const int relinquishDefault = 104;

  /// Required.
  static const int required = 105;

  /// Resolution.
  static const int resolution = 106;

  /// Segmentation Supported.
  static const int segmentationSupported = 107;

  /// Setpoint.
  static const int setpoint = 108;

  /// Setpoint Reference.
  static const int setpointReference = 109;

  /// State Text.
  static const int stateText = 110;

  /// Status Flags.
  static const int statusFlags = 111;

  /// System Status.
  static const int systemStatus = 112;

  /// Time Delay.
  static const int timeDelay = 113;

  /// Time Of Active Time Reset.
  static const int timeOfActiveTimeReset = 114;

  /// Time Of State Count Reset.
  static const int timeOfStateCountReset = 115;

  /// Time Synchronization Recipients.
  static const int timeSynchronizationRecipients = 116;

  /// Units.
  static const int units = 117;

  /// Update Interval.
  static const int updateInterval = 118;

  /// UTC Offset.
  static const int utcOffset = 119;

  /// Vendor Identifier.
  static const int vendorIdentifier = 120;

  /// Vendor Name.
  static const int vendorName = 121;

  /// VT Classes Supported.
  static const int vtClassesSupported = 122;

  /// Weekly Schedule.
  static const int weeklySchedule = 123;

  /// Attempted Samples.
  static const int attemptedSamples = 124;

  /// Average Value.
  static const int averageValue = 125;

  /// Buffer Size.
  static const int bufferSize = 126;

  /// Client COV Increment.
  static const int clientCovIncrement = 127;

  /// COV Resubscription Interval.
  static const int covResubscriptionInterval = 128;

  /// Current Notify Time.
  static const int currentNotifyTime = 129;

  /// Event Time Stamps.
  static const int eventTimeStamps = 130;

  /// Log Buffer.
  static const int logBuffer = 131;

  /// Log Device Object Property.
  static const int logDeviceObjectProperty = 132;

  /// Enable.
  static const int enable = 133;

  /// Log Interval.
  static const int logInterval = 134;

  /// Maximum Value.
  static const int maximumValue = 135;

  /// Minimum Value.
  static const int minimumValue = 136;

  /// Notification Threshold.
  static const int notificationThreshold = 137;

  /// Previous Notify Time.
  static const int previousNotifyTime = 138;

  /// Protocol Revision.
  static const int protocolRevision = 139;

  /// Records Since Notification.
  static const int recordsSinceNotification = 140;

  /// Record Count.
  static const int recordCount = 141;

  /// Start Time.
  static const int startTime = 142;

  /// Stop Time.
  static const int stopTime = 143;

  /// Stop When Full.
  static const int stopWhenFull = 144;

  /// Total Record Count.
  static const int totalRecordCount = 145;

  /// Valid Samples.
  static const int validSamples = 146;

  /// Window Interval.
  static const int windowInterval = 147;

  /// Window Samples.
  static const int windowSamples = 148;

  /// Maximum Value Timestamp.
  static const int maximumValueTimestamp = 149;

  /// Minimum Value Timestamp.
  static const int minimumValueTimestamp = 150;

  /// Variance Value.
  static const int varianceValue = 151;

  /// Active COV Subscriptions.
  static const int activeCovSubscriptions = 152;

  /// Backup Failure Timeout.
  static const int backupFailureTimeout = 153;

  /// Configuration Files.
  static const int configurationFiles = 154;

  /// Database Revision.
  static const int databaseRevision = 155;

  /// Direct Reading.
  static const int directReading = 156;

  /// Last Restore Time.
  static const int lastRestoreTime = 157;

  /// Maintenance Required.
  static const int maintenanceRequired = 158;

  /// Member Of.
  static const int memberOf = 159;

  /// Mode.
  static const int mode = 160;

  /// Operation Expected.
  static const int operationExpected = 161;

  /// Setting.
  static const int setting = 162;

  /// Silenced.
  static const int silenced = 163;

  /// Tracking Value.
  static const int trackingValue = 164;

  /// Zone Members.
  static const int zoneMembers = 165;

  /// Life Safety Alarm Values.
  static const int lifeSafetyAlarmValues = 166;

  /// Max Segments Accepted.
  static const int maxSegmentsAccepted = 167;

  /// Profile Name.
  static const int profileName = 168;

  /// Auto Slave Discovery.
  static const int autoSlaveDiscovery = 169;

  /// Manual Slave Address Binding.
  static const int manualSlaveAddressBinding = 170;

  /// Slave Address Binding.
  static const int slaveAddressBinding = 171;

  /// Slave Proxy Enable.
  static const int slaveProxyEnable = 172;

  /// Last Notify Record.
  static const int lastNotifyRecord = 173;

  /// Schedule Default.
  static const int scheduleDefault = 174;

  /// Accepted Modes.
  static const int acceptedModes = 175;

  /// Adjust Value.
  static const int adjustValue = 176;

  /// Count.
  static const int count = 177;

  /// Count Before Change.
  static const int countBeforeChange = 178;

  /// Count Change Time.
  static const int countChangeTime = 179;

  /// COV Period.
  static const int covPeriod = 180;

  /// Input Reference.
  static const int inputReference = 181;

  /// Limit Monitoring Interval.
  static const int limitMonitoringInterval = 182;

  /// Logging Object.
  static const int loggingObject = 183;

  /// Logging Record.
  static const int loggingRecord = 184;

  /// Prescale.
  static const int prescale = 185;

  /// Pulse Rate.
  static const int pulseRate = 186;

  /// Scale.
  static const int scale = 187;

  /// Scale Factor.
  static const int scaleFactor = 188;

  /// Update Time.
  static const int updateTime = 189;

  /// Value Before Change.
  static const int valueBeforeChange = 190;

  /// Value Set.
  static const int valueSet = 191;

  /// Value Change Time.
  static const int valueChangeTime = 192;

  /// Align Intervals.
  static const int alignIntervals = 193;

  /// Interval Offset.
  static const int intervalOffset = 195;

  /// Last Restart Reason.
  static const int lastRestartReason = 196;

  /// Logging Type.
  static const int loggingType = 197;

  /// Restart Notification Recipients.
  static const int restartNotificationRecipients = 202;

  /// Time Of Device Restart.
  static const int timeOfDeviceRestart = 203;

  /// Time Synchronization Interval.
  static const int timeSynchronizationInterval = 204;

  /// Trigger.
  static const int trigger = 205;

  /// UTC Time Synchronization Recipients.
  static const int utcTimeSynchronizationRecipients = 206;

  /// Node Subtype.
  static const int nodeSubtype = 207;

  /// Node Type.
  static const int nodeType = 208;

  /// Structured Object List.
  static const int structuredObjectList = 209;

  /// Subordinate Annotations.
  static const int subordinateAnnotations = 210;

  /// Subordinate List.
  static const int subordinateList = 211;

  /// Actual Shed Level.
  static const int actualShedLevel = 212;

  /// Duty Window.
  static const int dutyWindow = 213;

  /// Expected Shed Level.
  static const int expectedShedLevel = 214;

  /// Full Duty Baseline.
  static const int fullDutyBaseline = 215;

  /// Requested Shed Level.
  static const int requestedShedLevel = 218;

  /// Shed Duration.
  static const int shedDuration = 219;

  /// Shed Level Descriptions.
  static const int shedLevelDescriptions = 220;

  /// Shed Levels.
  static const int shedLevels = 221;

  /// State Description.
  static const int stateDescription = 222;

  /// Door Alarm State.
  static const int doorAlarmState = 226;

  /// Door Extended Pulse Time.
  static const int doorExtendedPulseTime = 227;

  /// Door Members.
  static const int doorMembers = 228;

  /// Door Open Too Long Time.
  static const int doorOpenTooLongTime = 229;

  /// Door Pulse Time.
  static const int doorPulseTime = 230;

  /// Door Status.
  static const int doorStatus = 231;

  /// Door Unlock Delay Time.
  static const int doorUnlockDelayTime = 232;

  /// Lock Status.
  static const int lockStatus = 233;

  /// Masked Alarm Values.
  static const int maskedAlarmValues = 234;

  /// Secured Status.
  static const int securedStatus = 235;

  /// Absentee Limit.
  static const int absenteeLimit = 244;

  /// Access Alarm Events.
  static const int accessAlarmEvents = 245;

  /// Access Doors.
  static const int accessDoors = 246;

  /// Access Event.
  static const int accessEvent = 247;

  /// Access Event Authentication Factor.
  static const int accessEventAuthenticationFactor = 248;

  /// Access Event Credential.
  static const int accessEventCredential = 249;

  /// Access Event Time.
  static const int accessEventTime = 250;

  /// Access Transaction Events.
  static const int accessTransactionEvents = 251;

  /// Accompaniment.
  static const int accompaniment = 252;

  /// Accompaniment Time.
  static const int accompanimentTime = 253;

  /// Activation Time.
  static const int activationTime = 254;

  /// Active Authentication Policy.
  static const int activeAuthenticationPolicy = 255;

  /// Assigned Access Rights.
  static const int assignedAccessRights = 256;

  /// Authentication Factors.
  static const int authenticationFactors = 257;

  /// Authentication Policy List.
  static const int authenticationPolicyList = 258;

  /// Authentication Policy Names.
  static const int authenticationPolicyNames = 259;

  /// Authentication Status.
  static const int authenticationStatus = 260;

  /// Authorization Mode.
  static const int authorizationMode = 261;

  /// Belongs To.
  static const int belongsTo = 262;

  /// Credential Disable.
  static const int credentialDisable = 263;

  /// Credential Status.
  static const int credentialStatus = 264;

  /// Credentials.
  static const int credentials = 265;

  /// Credentials In Zone.
  static const int credentialsInZone = 266;

  /// Days Remaining.
  static const int daysRemaining = 267;

  /// Entry Points.
  static const int entryPoints = 268;

  /// Exit Points.
  static const int exitPoints = 269;

  /// Expiration Time.
  static const int expirationTime = 270;

  /// Extended Time Enable.
  static const int extendedTimeEnable = 271;

  /// Failed Attempt Events.
  static const int failedAttemptEvents = 272;

  /// Failed Attempts.
  static const int failedAttempts = 273;

  /// Failed Attempts Time.
  static const int failedAttemptsTime = 274;

  /// Last Access Event.
  static const int lastAccessEvent = 275;

  /// Last Access Point.
  static const int lastAccessPoint = 276;

  /// Last Credential Added.
  static const int lastCredentialAdded = 277;

  /// Last Credential Added Time.
  static const int lastCredentialAddedTime = 278;

  /// Last Credential Removed.
  static const int lastCredentialRemoved = 279;

  /// Last Credential Removed Time.
  static const int lastCredentialRemovedTime = 280;

  /// Last Use Time.
  static const int lastUseTime = 281;

  /// Lockout.
  static const int lockout = 282;

  /// Lockout Relinquish Time.
  static const int lockoutRelinquishTime = 283;

  /// Master Exemption.
  static const int masterExemption = 284;

  /// Max Failed Attempts.
  static const int maxFailedAttempts = 285;

  /// Members.
  static const int members = 286;

  /// Muster Point.
  static const int musterPoint = 287;

  /// Negative Access Rules.
  static const int negativeAccessRules = 288;

  /// Number Of Authentication Policies.
  static const int numberOfAuthenticationPolicies = 289;

  /// Occupancy Count.
  static const int occupancyCount = 290;

  /// Occupancy Count Adjust.
  static const int occupancyCountAdjust = 291;

  /// Occupancy Count Enable.
  static const int occupancyCountEnable = 292;

  /// Occupancy Exemption.
  static const int occupancyExemption = 293;

  /// Occupancy Lower Limit.
  static const int occupancyLowerLimit = 294;

  /// Occupancy Lower Limit Enforced.
  static const int occupancyLowerLimitEnforced = 295;

  /// Occupancy State.
  static const int occupancyState = 296;

  /// Occupancy Upper Limit.
  static const int occupancyUpperLimit = 297;

  /// Occupancy Upper Limit Enforced.
  static const int occupancyUpperLimitEnforced = 298;

  /// Passback Exemption.
  static const int passbackExemption = 299;

  /// Passback Mode.
  static const int passbackMode = 300;

  /// Passback Timeout.
  static const int passbackTimeout = 301;

  /// Positive Access Rules.
  static const int positiveAccessRules = 302;

  /// Reason For Disable.
  static const int reasonForDisable = 303;

  /// Supported Formats.
  static const int supportedFormats = 304;

  /// Supported Format Classes.
  static const int supportedFormatClasses = 305;

  /// Threat Authority.
  static const int threatAuthority = 306;

  /// Threat Level.
  static const int threatLevel = 307;

  /// Trace Flag.
  static const int traceFlag = 308;

  /// Transaction Notification Class.
  static const int transactionNotificationClass = 309;

  /// User External Identifier.
  static const int userExternalIdentifier = 310;

  /// User Information Reference.
  static const int userInformationReference = 311;

  /// User Name.
  static const int userName = 317;

  /// User Type.
  static const int userType = 318;

  /// Uses Remaining.
  static const int usesRemaining = 319;

  /// Zone From.
  static const int zoneFrom = 320;

  /// Zone To.
  static const int zoneTo = 321;

  /// Access Event Tag.
  static const int accessEventTag = 322;

  /// Global Identifier.
  static const int globalIdentifier = 323;

  /// Verification Time.
  static const int verificationTime = 326;

  /// Base Device Security Policy.
  static const int baseDeviceSecurityPolicy = 327;

  /// Distribution Key Revision.
  static const int distributionKeyRevision = 328;

  /// Do Not Hide.
  static const int doNotHide = 329;

  /// Key Sets.
  static const int keySets = 330;

  /// Last Key Server.
  static const int lastKeyServer = 331;

  /// Network Access Security Policies.
  static const int networkAccessSecurityPolicies = 332;

  /// Packet Reorder Time.
  static const int packetReorderTime = 333;

  /// Security Pdu Timeout.
  static const int securityPduTimeout = 334;

  /// Security Time Window.
  static const int securityTimeWindow = 335;

  /// Supported Security Algorithm.
  static const int supportedSecurityAlgorithm = 336;

  /// Update Key Set Timeout.
  static const int updateKeySetTimeout = 337;

  /// Backup And Restore State.
  static const int backupAndRestoreState = 338;

  /// Backup Preparation Time.
  static const int backupPreparationTime = 339;

  /// Restore Completion Time.
  static const int restoreCompletionTime = 340;

  /// Restore Preparation Time.
  static const int restorePreparationTime = 341;

  /// Bit Mask.
  static const int bitMask = 342;

  /// Bit Text.
  static const int bitText = 343;

  /// Is UTC.
  static const int isUtc = 344;

  /// Group Members.
  static const int groupMembers = 345;

  /// Group Member Names.
  static const int groupMemberNames = 346;

  /// Member Status Flags.
  static const int memberStatusFlags = 347;

  /// Requested Update Interval.
  static const int requestedUpdateInterval = 348;

  /// Covu Period.
  static const int covuPeriod = 349;

  /// Covu Recipients.
  static const int covuRecipients = 350;

  /// Event Message Texts.
  static const int eventMessageTexts = 351;

  /// Event Message Texts Config.
  static const int eventMessageTextsConfig = 352;

  /// Event Detection Enable.
  static const int eventDetectionEnable = 353;

  /// Event Algorithm Inhibit.
  static const int eventAlgorithmInhibit = 354;

  /// Event Algorithm Inhibit Ref.
  static const int eventAlgorithmInhibitRef = 355;

  /// Time Delay Normal.
  static const int timeDelayNormal = 356;

  /// Reliability Evaluation Inhibit.
  static const int reliabilityEvaluationInhibit = 357;

  /// Fault Parameters.
  static const int faultParameters = 358;

  /// Fault Type.
  static const int faultType = 359;

  /// Local Forwarding Only.
  static const int localForwardingOnly = 360;

  /// Process Identifier Filter.
  static const int processIdentifierFilter = 361;

  /// Subscribed Recipients.
  static const int subscribedRecipients = 362;

  /// Port Filter.
  static const int portFilter = 363;

  /// Authorization Exemptions.
  static const int authorizationExemptions = 364;

  /// Allow Group Delay Inhibit.
  static const int allowGroupDelayInhibit = 365;

  /// Channel Number.
  static const int channelNumber = 366;

  /// Control Groups.
  static const int controlGroups = 367;

  /// Execution Delay.
  static const int executionDelay = 368;

  /// Last Priority.
  static const int lastPriority = 369;

  /// Write Status.
  static const int writeStatus = 370;

  /// Property List.
  static const int propertyList = 371;

  /// Serial Number.
  static const int serialNumber = 372;

  /// Blink Warn Enable.
  static const int blinkWarnEnable = 373;

  /// Default Fade Time.
  static const int defaultFadeTime = 374;

  /// Default Ramp Rate.
  static const int defaultRampRate = 375;

  /// Default Step Increment.
  static const int defaultStepIncrement = 376;

  /// Egress Time.
  static const int egressTime = 377;

  /// In Progress.
  static const int inProgress = 378;

  /// Instantaneous Power.
  static const int instantaneousPower = 379;

  /// Lighting Command.
  static const int lightingCommand = 380;

  /// Lighting Command Default Priority.
  static const int lightingCommandDefaultPriority = 381;

  /// Max Actual Value.
  static const int maxActualValue = 382;

  /// Min Actual Value.
  static const int minActualValue = 383;

  /// Power.
  static const int power = 384;

  /// Transition.
  static const int transition = 385;

  /// Egress Active.
  static const int egressActive = 386;

  /// Interface Value.
  static const int interfaceValue = 387;

  /// Fault High Limit.
  static const int faultHighLimit = 388;

  /// Fault Low Limit.
  static const int faultLowLimit = 389;

  /// Low Diff Limit.
  static const int lowDiffLimit = 390;

  /// Strike Count.
  static const int strikeCount = 391;

  /// Time Of Strike Count Reset.
  static const int timeOfStrikeCountReset = 392;

  /// Default Timeout.
  static const int defaultTimeout = 393;

  /// Initial Timeout.
  static const int initialTimeout = 394;

  /// Last State Change.
  static const int lastStateChange = 395;

  /// State Change Values.
  static const int stateChangeValues = 396;

  /// Timer Running.
  static const int timerRunning = 397;

  /// Timer State.
  static const int timerState = 398;

  /// APDU Length.
  static const int apduLength = 399;

  /// IP Address.
  static const int ipAddress = 400;

  /// IP Default Gateway.
  static const int ipDefaultGateway = 401;

  /// IP DHCP Enable.
  static const int ipDhcpEnable = 402;

  /// IP DHCP Lease Time.
  static const int ipDhcpLeaseTime = 403;

  /// IP DHCP Lease Time Remaining.
  static const int ipDhcpLeaseTimeRemaining = 404;

  /// IP DHCP Server.
  static const int ipDhcpServer = 405;

  /// IP DNS Server.
  static const int ipDnsServer = 406;

  /// BACnet IP Global Address.
  static const int bacnetIpGlobalAddress = 407;

  /// BACnet IP Mode.
  static const int bacnetIpMode = 408;

  /// BACnet IP Multicast Address.
  static const int bacnetIpMulticastAddress = 409;

  /// BACnet IP Nat Traversal.
  static const int bacnetIpNatTraversal = 410;

  /// IP Subnet Mask.
  static const int ipSubnetMask = 411;

  /// BACnet IP UDP Port.
  static const int bacnetIpUdpPort = 412;

  /// BBMD Accept FD Registrations.
  static const int bbmdAcceptFdRegistrations = 413;

  /// BBMD Broadcast Distribution Table.
  static const int bbmdBroadcastDistributionTable = 414;

  /// BBMD Foreign Device Table.
  static const int bbmdForeignDeviceTable = 415;

  /// Changes Pending.
  static const int changesPending = 416;

  /// Command.
  static const int command = 417;

  /// FD BBMD Address.
  static const int fdBbmdAddress = 418;

  /// FD Subscription Lifetime.
  static const int fdSubscriptionLifetime = 419;

  /// Link Speed.
  static const int linkSpeed = 420;

  /// Link Speeds.
  static const int linkSpeeds = 421;

  /// Link Speed Autonegotiate.
  static const int linkSpeedAutonegotiate = 422;

  /// MAC Address.
  static const int macAddress = 423;

  /// Network Interface Name.
  static const int networkInterfaceName = 424;

  /// Network Number.
  static const int networkNumber = 425;

  /// Network Number Quality.
  static const int networkNumberQuality = 426;

  /// Network Type.
  static const int networkType = 427;

  /// Routing Table.
  static const int routingTable = 428;

  /// Virtual MAC Address Table.
  static const int virtualMacAddressTable = 429;

  /// Command Time Array.
  static const int commandTimeArray = 430;

  /// Current Command Priority.
  static const int currentCommandPriority = 431;

  /// Last Command Time.
  static const int lastCommandTime = 432;

  /// Value Source.
  static const int valueSource = 433;

  /// Value Source Array.
  static const int valueSourceArray = 434;

  /// BACnet IPv6 Mode.
  static const int bacnetIpv6Mode = 435;

  /// IPv6 Address.
  static const int ipv6Address = 436;

  /// IPv6 Prefix Length.
  static const int ipv6PrefixLength = 437;

  /// BACnet IPv6 UDP Port.
  static const int bacnetIpv6UdpPort = 438;

  /// IPv6 Default Gateway.
  static const int ipv6DefaultGateway = 439;

  /// BACnet IPv6 Multicast Address.
  static const int bacnetIpv6MulticastAddress = 440;

  /// IPv6 DNS Server.
  static const int ipv6DnsServer = 441;

  /// IPv6 Auto Addressing Enable.
  static const int ipv6AutoAddressingEnable = 442;

  /// IPv6 DHCP Lease Time.
  static const int ipv6DhcpLeaseTime = 443;

  /// IPv6 DHCP Lease Time Remaining.
  static const int ipv6DhcpLeaseTimeRemaining = 444;

  /// IPv6 DHCP Server.
  static const int ipv6DhcpServer = 445;

  /// IPv6 Zone Index.
  static const int ipv6ZoneIndex = 446;

  /// Assigned Landing Calls.
  static const int assignedLandingCalls = 447;

  /// Car Assigned Direction.
  static const int carAssignedDirection = 448;

  /// Car Door Command.
  static const int carDoorCommand = 449;

  /// Car Door Status.
  static const int carDoorStatus = 450;

  /// Car Door Text.
  static const int carDoorText = 451;

  /// Car Door Zone.
  static const int carDoorZone = 452;

  /// Car Drive Status.
  static const int carDriveStatus = 453;

  /// Car Load.
  static const int carLoad = 454;

  /// Car Load Units.
  static const int carLoadUnits = 455;

  /// Car Mode.
  static const int carMode = 456;

  /// Car Moving Direction.
  static const int carMovingDirection = 457;

  /// Car Position.
  static const int carPosition = 458;

  /// Elevator Group.
  static const int elevatorGroup = 459;

  /// Energy Meter.
  static const int energyMeter = 460;

  /// Energy Meter Ref.
  static const int energyMeterRef = 461;

  /// Escalator Mode.
  static const int escalatorMode = 462;

  /// Fault Signals.
  static const int faultSignals = 463;

  /// Floor Text.
  static const int floorText = 464;

  /// Group ID.
  static const int groupId = 465;

  /// Group Mode.
  static const int groupMode = 467;

  /// Higher Deck.
  static const int higherDeck = 468;

  /// Installation ID.
  static const int installationId = 469;

  /// Landing Calls.
  static const int landingCalls = 470;

  /// Landing Call Control.
  static const int landingCallControl = 471;

  /// Landing Door Status.
  static const int landingDoorStatus = 472;

  /// Lower Deck.
  static const int lowerDeck = 473;

  /// Machine Room ID.
  static const int machineRoomId = 474;

  /// Making Car Call.
  static const int makingCarCall = 475;

  /// Next Stopping Floor.
  static const int nextStoppingFloor = 476;

  /// Operation Direction.
  static const int operationDirection = 477;

  /// Passenger Alarm.
  static const int passengerAlarm = 478;

  /// Power Mode.
  static const int powerMode = 479;

  /// Registered Car Call.
  static const int registeredCarCall = 480;

  /// Active COV Multiple Subscriptions.
  static const int activeCovMultipleSubscriptions = 481;

  /// Protocol Level.
  static const int protocolLevel = 482;

  /// Reference Port.
  static const int referencePort = 483;

  /// Deployed Profile Location.
  static const int deployedProfileLocation = 484;

  /// Profile Location.
  static const int profileLocation = 485;

  /// Tags.
  static const int tags = 486;

  /// Subordinate Node Types.
  static const int subordinateNodeTypes = 487;

  /// Subordinate Tags.
  static const int subordinateTags = 488;

  /// Subordinate Relationships.
  static const int subordinateRelationships = 489;

  /// Default Subordinate Relationship.
  static const int defaultSubordinateRelationship = 490;

  /// Represents.
  static const int represents = 491;

  /// Default Present Value.
  static const int defaultPresentValue = 492;

  /// Present Stage.
  static const int presentStage = 493;

  /// Stages.
  static const int stages = 494;

  /// Stage Names.
  static const int stageNames = 495;

  /// Target References.
  static const int targetReferences = 496;

  /// Audit Source Level.
  static const int auditSourceLevel = 497;

  /// Audit Level.
  static const int auditLevel = 498;

  /// Audit Notification Recipient.
  static const int auditNotificationRecipient = 499;

  /// Audit Priority Filter.
  static const int auditPriorityFilter = 500;

  /// Auditable Operations.
  static const int auditableOperations = 501;

  /// Delete On Forward.
  static const int deleteOnForward = 502;

  /// Maximum Send Delay.
  static const int maximumSendDelay = 503;

  /// Monitored Objects.
  static const int monitoredObjects = 504;

  /// Send Now.
  static const int sendNow = 505;

  /// Floor Number.
  static const int floorNumber = 506;

  /// Device UUID.
  static const int deviceUuid = 507;

  /// Additional Reference Ports.
  static const int additionalReferencePorts = 508;

  /// Certificate Signing Request File.
  static const int certificateSigningRequestFile = 509;

  /// Command Validation Result.
  static const int commandValidationResult = 510;

  /// Issuer Certificate Files.
  static const int issuerCertificateFiles = 511;

  /// Max Bvlc Length Accepted.
  static const int maxBvlcLengthAccepted = 4194304;

  /// Max NPDU Length Accepted.
  static const int maxNpduLengthAccepted = 4194305;

  /// Operational Certificate File.
  static const int operationalCertificateFile = 4194306;

  /// Current Health.
  static const int currentHealth = 4194307;

  /// SC Connect Wait Timeout.
  static const int scConnectWaitTimeout = 4194308;

  /// SC Direct Connect Accept Enable.
  static const int scDirectConnectAcceptEnable = 4194309;

  /// SC Direct Connect Accept Uris.
  static const int scDirectConnectAcceptUris = 4194310;

  /// SC Direct Connect Binding.
  static const int scDirectConnectBinding = 4194311;

  /// SC Direct Connect Connection Status.
  static const int scDirectConnectConnectionStatus = 4194312;

  /// SC Direct Connect Initiate Enable.
  static const int scDirectConnectInitiateEnable = 4194313;

  /// SC Disconnect Wait Timeout.
  static const int scDisconnectWaitTimeout = 4194314;

  /// SC Failed Connection Requests.
  static const int scFailedConnectionRequests = 4194315;

  /// SC Failover Hub Connection Status.
  static const int scFailoverHubConnectionStatus = 4194316;

  /// SC Failover Hub Uri.
  static const int scFailoverHubUri = 4194317;

  /// SC Hub Connector State.
  static const int scHubConnectorState = 4194318;

  /// SC Hub Function Accept Uris.
  static const int scHubFunctionAcceptUris = 4194319;

  /// SC Hub Function Binding.
  static const int scHubFunctionBinding = 4194320;

  /// SC Hub Function Connection Status.
  static const int scHubFunctionConnectionStatus = 4194321;

  /// SC Hub Function Enable.
  static const int scHubFunctionEnable = 4194322;

  /// SC Heartbeat Timeout.
  static const int scHeartbeatTimeout = 4194323;

  /// SC Primary Hub Connection Status.
  static const int scPrimaryHubConnectionStatus = 4194324;

  /// SC Primary Hub Uri.
  static const int scPrimaryHubUri = 4194325;

  /// SC Maximum Reconnect Time.
  static const int scMaximumReconnectTime = 4194326;

  /// SC Minimum Reconnect Time.
  static const int scMinimumReconnectTime = 4194327;

  /// Color Override.
  static const int colorOverride = 4194328;

  /// Color Reference.
  static const int colorReference = 4194329;

  /// Default Color.
  static const int defaultColor = 4194330;

  /// Default Color Temperature.
  static const int defaultColorTemperature = 4194331;

  /// Override Color Reference.
  static const int overrideColorReference = 4194332;

  /// Write Every Scheduled Action.
  static const int writeEveryScheduledAction = 4194333;

  /// Color Command.
  static const int colorCommand = 4194334;

  /// High End Trim.
  static const int highEndTrim = 4194335;

  /// Low End Trim.
  static const int lowEndTrim = 4194336;

  /// Trim Fade Time.
  static const int trimFadeTime = 4194337;

  /// Device Address Proxy Enable.
  static const int deviceAddressProxyEnable = 4194338;

  /// Device Address Proxy Table.
  static const int deviceAddressProxyTable = 4194339;

  /// Device Address Proxy Timeout.
  static const int deviceAddressProxyTimeout = 4194340;

  /// Default On Value.
  static const int defaultOnValue = 4194341;

  /// Last On Value.
  static const int lastOnValue = 4194342;

  /// Authorization Cache.
  static const int authorizationCache = 4194343;

  /// Authorization Groups.
  static const int authorizationGroups = 4194344;

  /// Authorization Policy.
  static const int authorizationPolicy = 4194345;

  /// Authorization Scope.
  static const int authorizationScope = 4194346;

  /// Authorization Server.
  static const int authorizationServer = 4194347;

  /// Authorization Status.
  static const int authorizationStatus = 4194348;

  /// Max Proxied I Ams Per Second.
  static const int maxProxiedIAmsPerSecond = 4194349;

  static const Map<int, String> _labels = {
    ackedTransitions: 'Acked Transitions',
    ackRequired: 'Ack Required',
    action: 'Action',
    actionText: 'Action Text',
    activeText: 'Active Text',
    activeVtSessions: 'Active VT Sessions',
    alarmValue: 'Alarm Value',
    alarmValues: 'Alarm Values',
    all: 'All',
    allWritesSuccessful: 'All Writes Successful',
    apduSegmentTimeout: 'APDU Segment Timeout',
    apduTimeout: 'APDU Timeout',
    applicationSoftwareVersion: 'Application Software Version',
    archive: 'Archive',
    bias: 'Bias',
    changeOfStateCount: 'Change Of State Count',
    changeOfStateTime: 'Change Of State Time',
    notificationClass: 'Notification Class',
    controlledVariableReference: 'Controlled Variable Reference',
    controlledVariableUnits: 'Controlled Variable Units',
    controlledVariableValue: 'Controlled Variable Value',
    covIncrement: 'COV Increment',
    dateList: 'Date List',
    daylightSavingsStatus: 'Daylight Savings Status',
    deadband: 'Deadband',
    derivativeConstant: 'Derivative Constant',
    derivativeConstantUnits: 'Derivative Constant Units',
    description: 'Description',
    descriptionOfHalt: 'Description Of Halt',
    deviceAddressBinding: 'Device Address Binding',
    deviceType: 'Device Type',
    effectivePeriod: 'Effective Period',
    elapsedActiveTime: 'Elapsed Active Time',
    errorLimit: 'Error Limit',
    eventEnable: 'Event Enable',
    eventState: 'Event State',
    eventType: 'Event Type',
    exceptionSchedule: 'Exception Schedule',
    faultValues: 'Fault Values',
    feedbackValue: 'Feedback Value',
    fileAccessMethod: 'File Access Method',
    fileSize: 'File Size',
    fileType: 'File Type',
    firmwareRevision: 'Firmware Revision',
    highLimit: 'High Limit',
    inactiveText: 'Inactive Text',
    inProcess: 'In Process',
    instanceOf: 'Instance Of',
    integralConstant: 'Integral Constant',
    integralConstantUnits: 'Integral Constant Units',
    issueConfirmedNotifications: 'Issue Confirmed Notifications',
    limitEnable: 'Limit Enable',
    listOfGroupMembers: 'List Of Group Members',
    listOfObjectPropertyReferences: 'List Of Object Property References',
    listOfSessionKeys: 'List Of Session Keys',
    localDate: 'Local Date',
    localTime: 'Local Time',
    location: 'Location',
    lowLimit: 'Low Limit',
    manipulatedVariableReference: 'Manipulated Variable Reference',
    maximumOutput: 'Maximum Output',
    maxApduLengthAccepted: 'Max APDU Length Accepted',
    maxInfoFrames: 'Max Info Frames',
    maxMaster: 'Max Master',
    maxPresValue: 'Max Pres Value',
    minimumOffTime: 'Minimum Off Time',
    minimumOnTime: 'Minimum On Time',
    minimumOutput: 'Minimum Output',
    minPresValue: 'Min Pres Value',
    modelName: 'Model Name',
    modificationDate: 'Modification Date',
    notifyType: 'Notify Type',
    numberOfApduRetries: 'Number Of APDU Retries',
    numberOfStates: 'Number Of States',
    objectIdentifier: 'Object Identifier',
    objectList: 'Object List',
    objectName: 'Object Name',
    objectPropertyReference: 'Object Property Reference',
    objectType: 'Object Type',
    optional: 'Optional',
    outOfService: 'Out Of Service',
    outputUnits: 'Output Units',
    eventParameters: 'Event Parameters',
    polarity: 'Polarity',
    presentValue: 'Present Value',
    priority: 'Priority',
    priorityArray: 'Priority Array',
    priorityForWriting: 'Priority For Writing',
    processIdentifier: 'Process Identifier',
    programChange: 'Program Change',
    programLocation: 'Program Location',
    programState: 'Program State',
    proportionalConstant: 'Proportional Constant',
    proportionalConstantUnits: 'Proportional Constant Units',
    protocolConformanceClass: 'Protocol Conformance Class',
    protocolObjectTypesSupported: 'Protocol Object Types Supported',
    protocolServicesSupported: 'Protocol Services Supported',
    protocolVersion: 'Protocol Version',
    readOnly: 'Read Only',
    reasonForHalt: 'Reason For Halt',
    recipient: 'Recipient',
    recipientList: 'Recipient List',
    reliability: 'Reliability',
    relinquishDefault: 'Relinquish Default',
    required: 'Required',
    resolution: 'Resolution',
    segmentationSupported: 'Segmentation Supported',
    setpoint: 'Setpoint',
    setpointReference: 'Setpoint Reference',
    stateText: 'State Text',
    statusFlags: 'Status Flags',
    systemStatus: 'System Status',
    timeDelay: 'Time Delay',
    timeOfActiveTimeReset: 'Time Of Active Time Reset',
    timeOfStateCountReset: 'Time Of State Count Reset',
    timeSynchronizationRecipients: 'Time Synchronization Recipients',
    units: 'Units',
    updateInterval: 'Update Interval',
    utcOffset: 'UTC Offset',
    vendorIdentifier: 'Vendor Identifier',
    vendorName: 'Vendor Name',
    vtClassesSupported: 'VT Classes Supported',
    weeklySchedule: 'Weekly Schedule',
    attemptedSamples: 'Attempted Samples',
    averageValue: 'Average Value',
    bufferSize: 'Buffer Size',
    clientCovIncrement: 'Client COV Increment',
    covResubscriptionInterval: 'COV Resubscription Interval',
    currentNotifyTime: 'Current Notify Time',
    eventTimeStamps: 'Event Time Stamps',
    logBuffer: 'Log Buffer',
    logDeviceObjectProperty: 'Log Device Object Property',
    enable: 'Enable',
    logInterval: 'Log Interval',
    maximumValue: 'Maximum Value',
    minimumValue: 'Minimum Value',
    notificationThreshold: 'Notification Threshold',
    previousNotifyTime: 'Previous Notify Time',
    protocolRevision: 'Protocol Revision',
    recordsSinceNotification: 'Records Since Notification',
    recordCount: 'Record Count',
    startTime: 'Start Time',
    stopTime: 'Stop Time',
    stopWhenFull: 'Stop When Full',
    totalRecordCount: 'Total Record Count',
    validSamples: 'Valid Samples',
    windowInterval: 'Window Interval',
    windowSamples: 'Window Samples',
    maximumValueTimestamp: 'Maximum Value Timestamp',
    minimumValueTimestamp: 'Minimum Value Timestamp',
    varianceValue: 'Variance Value',
    activeCovSubscriptions: 'Active COV Subscriptions',
    backupFailureTimeout: 'Backup Failure Timeout',
    configurationFiles: 'Configuration Files',
    databaseRevision: 'Database Revision',
    directReading: 'Direct Reading',
    lastRestoreTime: 'Last Restore Time',
    maintenanceRequired: 'Maintenance Required',
    memberOf: 'Member Of',
    mode: 'Mode',
    operationExpected: 'Operation Expected',
    setting: 'Setting',
    silenced: 'Silenced',
    trackingValue: 'Tracking Value',
    zoneMembers: 'Zone Members',
    lifeSafetyAlarmValues: 'Life Safety Alarm Values',
    maxSegmentsAccepted: 'Max Segments Accepted',
    profileName: 'Profile Name',
    autoSlaveDiscovery: 'Auto Slave Discovery',
    manualSlaveAddressBinding: 'Manual Slave Address Binding',
    slaveAddressBinding: 'Slave Address Binding',
    slaveProxyEnable: 'Slave Proxy Enable',
    lastNotifyRecord: 'Last Notify Record',
    scheduleDefault: 'Schedule Default',
    acceptedModes: 'Accepted Modes',
    adjustValue: 'Adjust Value',
    count: 'Count',
    countBeforeChange: 'Count Before Change',
    countChangeTime: 'Count Change Time',
    covPeriod: 'COV Period',
    inputReference: 'Input Reference',
    limitMonitoringInterval: 'Limit Monitoring Interval',
    loggingObject: 'Logging Object',
    loggingRecord: 'Logging Record',
    prescale: 'Prescale',
    pulseRate: 'Pulse Rate',
    scale: 'Scale',
    scaleFactor: 'Scale Factor',
    updateTime: 'Update Time',
    valueBeforeChange: 'Value Before Change',
    valueSet: 'Value Set',
    valueChangeTime: 'Value Change Time',
    alignIntervals: 'Align Intervals',
    intervalOffset: 'Interval Offset',
    lastRestartReason: 'Last Restart Reason',
    loggingType: 'Logging Type',
    restartNotificationRecipients: 'Restart Notification Recipients',
    timeOfDeviceRestart: 'Time Of Device Restart',
    timeSynchronizationInterval: 'Time Synchronization Interval',
    trigger: 'Trigger',
    utcTimeSynchronizationRecipients: 'UTC Time Synchronization Recipients',
    nodeSubtype: 'Node Subtype',
    nodeType: 'Node Type',
    structuredObjectList: 'Structured Object List',
    subordinateAnnotations: 'Subordinate Annotations',
    subordinateList: 'Subordinate List',
    actualShedLevel: 'Actual Shed Level',
    dutyWindow: 'Duty Window',
    expectedShedLevel: 'Expected Shed Level',
    fullDutyBaseline: 'Full Duty Baseline',
    requestedShedLevel: 'Requested Shed Level',
    shedDuration: 'Shed Duration',
    shedLevelDescriptions: 'Shed Level Descriptions',
    shedLevels: 'Shed Levels',
    stateDescription: 'State Description',
    doorAlarmState: 'Door Alarm State',
    doorExtendedPulseTime: 'Door Extended Pulse Time',
    doorMembers: 'Door Members',
    doorOpenTooLongTime: 'Door Open Too Long Time',
    doorPulseTime: 'Door Pulse Time',
    doorStatus: 'Door Status',
    doorUnlockDelayTime: 'Door Unlock Delay Time',
    lockStatus: 'Lock Status',
    maskedAlarmValues: 'Masked Alarm Values',
    securedStatus: 'Secured Status',
    absenteeLimit: 'Absentee Limit',
    accessAlarmEvents: 'Access Alarm Events',
    accessDoors: 'Access Doors',
    accessEvent: 'Access Event',
    accessEventAuthenticationFactor: 'Access Event Authentication Factor',
    accessEventCredential: 'Access Event Credential',
    accessEventTime: 'Access Event Time',
    accessTransactionEvents: 'Access Transaction Events',
    accompaniment: 'Accompaniment',
    accompanimentTime: 'Accompaniment Time',
    activationTime: 'Activation Time',
    activeAuthenticationPolicy: 'Active Authentication Policy',
    assignedAccessRights: 'Assigned Access Rights',
    authenticationFactors: 'Authentication Factors',
    authenticationPolicyList: 'Authentication Policy List',
    authenticationPolicyNames: 'Authentication Policy Names',
    authenticationStatus: 'Authentication Status',
    authorizationMode: 'Authorization Mode',
    belongsTo: 'Belongs To',
    credentialDisable: 'Credential Disable',
    credentialStatus: 'Credential Status',
    credentials: 'Credentials',
    credentialsInZone: 'Credentials In Zone',
    daysRemaining: 'Days Remaining',
    entryPoints: 'Entry Points',
    exitPoints: 'Exit Points',
    expirationTime: 'Expiration Time',
    extendedTimeEnable: 'Extended Time Enable',
    failedAttemptEvents: 'Failed Attempt Events',
    failedAttempts: 'Failed Attempts',
    failedAttemptsTime: 'Failed Attempts Time',
    lastAccessEvent: 'Last Access Event',
    lastAccessPoint: 'Last Access Point',
    lastCredentialAdded: 'Last Credential Added',
    lastCredentialAddedTime: 'Last Credential Added Time',
    lastCredentialRemoved: 'Last Credential Removed',
    lastCredentialRemovedTime: 'Last Credential Removed Time',
    lastUseTime: 'Last Use Time',
    lockout: 'Lockout',
    lockoutRelinquishTime: 'Lockout Relinquish Time',
    masterExemption: 'Master Exemption',
    maxFailedAttempts: 'Max Failed Attempts',
    members: 'Members',
    musterPoint: 'Muster Point',
    negativeAccessRules: 'Negative Access Rules',
    numberOfAuthenticationPolicies: 'Number Of Authentication Policies',
    occupancyCount: 'Occupancy Count',
    occupancyCountAdjust: 'Occupancy Count Adjust',
    occupancyCountEnable: 'Occupancy Count Enable',
    occupancyExemption: 'Occupancy Exemption',
    occupancyLowerLimit: 'Occupancy Lower Limit',
    occupancyLowerLimitEnforced: 'Occupancy Lower Limit Enforced',
    occupancyState: 'Occupancy State',
    occupancyUpperLimit: 'Occupancy Upper Limit',
    occupancyUpperLimitEnforced: 'Occupancy Upper Limit Enforced',
    passbackExemption: 'Passback Exemption',
    passbackMode: 'Passback Mode',
    passbackTimeout: 'Passback Timeout',
    positiveAccessRules: 'Positive Access Rules',
    reasonForDisable: 'Reason For Disable',
    supportedFormats: 'Supported Formats',
    supportedFormatClasses: 'Supported Format Classes',
    threatAuthority: 'Threat Authority',
    threatLevel: 'Threat Level',
    traceFlag: 'Trace Flag',
    transactionNotificationClass: 'Transaction Notification Class',
    userExternalIdentifier: 'User External Identifier',
    userInformationReference: 'User Information Reference',
    userName: 'User Name',
    userType: 'User Type',
    usesRemaining: 'Uses Remaining',
    zoneFrom: 'Zone From',
    zoneTo: 'Zone To',
    accessEventTag: 'Access Event Tag',
    globalIdentifier: 'Global Identifier',
    verificationTime: 'Verification Time',
    baseDeviceSecurityPolicy: 'Base Device Security Policy',
    distributionKeyRevision: 'Distribution Key Revision',
    doNotHide: 'Do Not Hide',
    keySets: 'Key Sets',
    lastKeyServer: 'Last Key Server',
    networkAccessSecurityPolicies: 'Network Access Security Policies',
    packetReorderTime: 'Packet Reorder Time',
    securityPduTimeout: 'Security Pdu Timeout',
    securityTimeWindow: 'Security Time Window',
    supportedSecurityAlgorithm: 'Supported Security Algorithm',
    updateKeySetTimeout: 'Update Key Set Timeout',
    backupAndRestoreState: 'Backup And Restore State',
    backupPreparationTime: 'Backup Preparation Time',
    restoreCompletionTime: 'Restore Completion Time',
    restorePreparationTime: 'Restore Preparation Time',
    bitMask: 'Bit Mask',
    bitText: 'Bit Text',
    isUtc: 'Is UTC',
    groupMembers: 'Group Members',
    groupMemberNames: 'Group Member Names',
    memberStatusFlags: 'Member Status Flags',
    requestedUpdateInterval: 'Requested Update Interval',
    covuPeriod: 'Covu Period',
    covuRecipients: 'Covu Recipients',
    eventMessageTexts: 'Event Message Texts',
    eventMessageTextsConfig: 'Event Message Texts Config',
    eventDetectionEnable: 'Event Detection Enable',
    eventAlgorithmInhibit: 'Event Algorithm Inhibit',
    eventAlgorithmInhibitRef: 'Event Algorithm Inhibit Ref',
    timeDelayNormal: 'Time Delay Normal',
    reliabilityEvaluationInhibit: 'Reliability Evaluation Inhibit',
    faultParameters: 'Fault Parameters',
    faultType: 'Fault Type',
    localForwardingOnly: 'Local Forwarding Only',
    processIdentifierFilter: 'Process Identifier Filter',
    subscribedRecipients: 'Subscribed Recipients',
    portFilter: 'Port Filter',
    authorizationExemptions: 'Authorization Exemptions',
    allowGroupDelayInhibit: 'Allow Group Delay Inhibit',
    channelNumber: 'Channel Number',
    controlGroups: 'Control Groups',
    executionDelay: 'Execution Delay',
    lastPriority: 'Last Priority',
    writeStatus: 'Write Status',
    propertyList: 'Property List',
    serialNumber: 'Serial Number',
    blinkWarnEnable: 'Blink Warn Enable',
    defaultFadeTime: 'Default Fade Time',
    defaultRampRate: 'Default Ramp Rate',
    defaultStepIncrement: 'Default Step Increment',
    egressTime: 'Egress Time',
    inProgress: 'In Progress',
    instantaneousPower: 'Instantaneous Power',
    lightingCommand: 'Lighting Command',
    lightingCommandDefaultPriority: 'Lighting Command Default Priority',
    maxActualValue: 'Max Actual Value',
    minActualValue: 'Min Actual Value',
    power: 'Power',
    transition: 'Transition',
    egressActive: 'Egress Active',
    interfaceValue: 'Interface Value',
    faultHighLimit: 'Fault High Limit',
    faultLowLimit: 'Fault Low Limit',
    lowDiffLimit: 'Low Diff Limit',
    strikeCount: 'Strike Count',
    timeOfStrikeCountReset: 'Time Of Strike Count Reset',
    defaultTimeout: 'Default Timeout',
    initialTimeout: 'Initial Timeout',
    lastStateChange: 'Last State Change',
    stateChangeValues: 'State Change Values',
    timerRunning: 'Timer Running',
    timerState: 'Timer State',
    apduLength: 'APDU Length',
    ipAddress: 'IP Address',
    ipDefaultGateway: 'IP Default Gateway',
    ipDhcpEnable: 'IP DHCP Enable',
    ipDhcpLeaseTime: 'IP DHCP Lease Time',
    ipDhcpLeaseTimeRemaining: 'IP DHCP Lease Time Remaining',
    ipDhcpServer: 'IP DHCP Server',
    ipDnsServer: 'IP DNS Server',
    bacnetIpGlobalAddress: 'BACnet IP Global Address',
    bacnetIpMode: 'BACnet IP Mode',
    bacnetIpMulticastAddress: 'BACnet IP Multicast Address',
    bacnetIpNatTraversal: 'BACnet IP Nat Traversal',
    ipSubnetMask: 'IP Subnet Mask',
    bacnetIpUdpPort: 'BACnet IP UDP Port',
    bbmdAcceptFdRegistrations: 'BBMD Accept FD Registrations',
    bbmdBroadcastDistributionTable: 'BBMD Broadcast Distribution Table',
    bbmdForeignDeviceTable: 'BBMD Foreign Device Table',
    changesPending: 'Changes Pending',
    command: 'Command',
    fdBbmdAddress: 'FD BBMD Address',
    fdSubscriptionLifetime: 'FD Subscription Lifetime',
    linkSpeed: 'Link Speed',
    linkSpeeds: 'Link Speeds',
    linkSpeedAutonegotiate: 'Link Speed Autonegotiate',
    macAddress: 'MAC Address',
    networkInterfaceName: 'Network Interface Name',
    networkNumber: 'Network Number',
    networkNumberQuality: 'Network Number Quality',
    networkType: 'Network Type',
    routingTable: 'Routing Table',
    virtualMacAddressTable: 'Virtual MAC Address Table',
    commandTimeArray: 'Command Time Array',
    currentCommandPriority: 'Current Command Priority',
    lastCommandTime: 'Last Command Time',
    valueSource: 'Value Source',
    valueSourceArray: 'Value Source Array',
    bacnetIpv6Mode: 'BACnet IPv6 Mode',
    ipv6Address: 'IPv6 Address',
    ipv6PrefixLength: 'IPv6 Prefix Length',
    bacnetIpv6UdpPort: 'BACnet IPv6 UDP Port',
    ipv6DefaultGateway: 'IPv6 Default Gateway',
    bacnetIpv6MulticastAddress: 'BACnet IPv6 Multicast Address',
    ipv6DnsServer: 'IPv6 DNS Server',
    ipv6AutoAddressingEnable: 'IPv6 Auto Addressing Enable',
    ipv6DhcpLeaseTime: 'IPv6 DHCP Lease Time',
    ipv6DhcpLeaseTimeRemaining: 'IPv6 DHCP Lease Time Remaining',
    ipv6DhcpServer: 'IPv6 DHCP Server',
    ipv6ZoneIndex: 'IPv6 Zone Index',
    assignedLandingCalls: 'Assigned Landing Calls',
    carAssignedDirection: 'Car Assigned Direction',
    carDoorCommand: 'Car Door Command',
    carDoorStatus: 'Car Door Status',
    carDoorText: 'Car Door Text',
    carDoorZone: 'Car Door Zone',
    carDriveStatus: 'Car Drive Status',
    carLoad: 'Car Load',
    carLoadUnits: 'Car Load Units',
    carMode: 'Car Mode',
    carMovingDirection: 'Car Moving Direction',
    carPosition: 'Car Position',
    elevatorGroup: 'Elevator Group',
    energyMeter: 'Energy Meter',
    energyMeterRef: 'Energy Meter Ref',
    escalatorMode: 'Escalator Mode',
    faultSignals: 'Fault Signals',
    floorText: 'Floor Text',
    groupId: 'Group ID',
    groupMode: 'Group Mode',
    higherDeck: 'Higher Deck',
    installationId: 'Installation ID',
    landingCalls: 'Landing Calls',
    landingCallControl: 'Landing Call Control',
    landingDoorStatus: 'Landing Door Status',
    lowerDeck: 'Lower Deck',
    machineRoomId: 'Machine Room ID',
    makingCarCall: 'Making Car Call',
    nextStoppingFloor: 'Next Stopping Floor',
    operationDirection: 'Operation Direction',
    passengerAlarm: 'Passenger Alarm',
    powerMode: 'Power Mode',
    registeredCarCall: 'Registered Car Call',
    activeCovMultipleSubscriptions: 'Active COV Multiple Subscriptions',
    protocolLevel: 'Protocol Level',
    referencePort: 'Reference Port',
    deployedProfileLocation: 'Deployed Profile Location',
    profileLocation: 'Profile Location',
    tags: 'Tags',
    subordinateNodeTypes: 'Subordinate Node Types',
    subordinateTags: 'Subordinate Tags',
    subordinateRelationships: 'Subordinate Relationships',
    defaultSubordinateRelationship: 'Default Subordinate Relationship',
    represents: 'Represents',
    defaultPresentValue: 'Default Present Value',
    presentStage: 'Present Stage',
    stages: 'Stages',
    stageNames: 'Stage Names',
    targetReferences: 'Target References',
    auditSourceLevel: 'Audit Source Level',
    auditLevel: 'Audit Level',
    auditNotificationRecipient: 'Audit Notification Recipient',
    auditPriorityFilter: 'Audit Priority Filter',
    auditableOperations: 'Auditable Operations',
    deleteOnForward: 'Delete On Forward',
    maximumSendDelay: 'Maximum Send Delay',
    monitoredObjects: 'Monitored Objects',
    sendNow: 'Send Now',
    floorNumber: 'Floor Number',
    deviceUuid: 'Device UUID',
    additionalReferencePorts: 'Additional Reference Ports',
    certificateSigningRequestFile: 'Certificate Signing Request File',
    commandValidationResult: 'Command Validation Result',
    issuerCertificateFiles: 'Issuer Certificate Files',
    maxBvlcLengthAccepted: 'Max Bvlc Length Accepted',
    maxNpduLengthAccepted: 'Max NPDU Length Accepted',
    operationalCertificateFile: 'Operational Certificate File',
    currentHealth: 'Current Health',
    scConnectWaitTimeout: 'SC Connect Wait Timeout',
    scDirectConnectAcceptEnable: 'SC Direct Connect Accept Enable',
    scDirectConnectAcceptUris: 'SC Direct Connect Accept Uris',
    scDirectConnectBinding: 'SC Direct Connect Binding',
    scDirectConnectConnectionStatus: 'SC Direct Connect Connection Status',
    scDirectConnectInitiateEnable: 'SC Direct Connect Initiate Enable',
    scDisconnectWaitTimeout: 'SC Disconnect Wait Timeout',
    scFailedConnectionRequests: 'SC Failed Connection Requests',
    scFailoverHubConnectionStatus: 'SC Failover Hub Connection Status',
    scFailoverHubUri: 'SC Failover Hub Uri',
    scHubConnectorState: 'SC Hub Connector State',
    scHubFunctionAcceptUris: 'SC Hub Function Accept Uris',
    scHubFunctionBinding: 'SC Hub Function Binding',
    scHubFunctionConnectionStatus: 'SC Hub Function Connection Status',
    scHubFunctionEnable: 'SC Hub Function Enable',
    scHeartbeatTimeout: 'SC Heartbeat Timeout',
    scPrimaryHubConnectionStatus: 'SC Primary Hub Connection Status',
    scPrimaryHubUri: 'SC Primary Hub Uri',
    scMaximumReconnectTime: 'SC Maximum Reconnect Time',
    scMinimumReconnectTime: 'SC Minimum Reconnect Time',
    colorOverride: 'Color Override',
    colorReference: 'Color Reference',
    defaultColor: 'Default Color',
    defaultColorTemperature: 'Default Color Temperature',
    overrideColorReference: 'Override Color Reference',
    writeEveryScheduledAction: 'Write Every Scheduled Action',
    colorCommand: 'Color Command',
    highEndTrim: 'High End Trim',
    lowEndTrim: 'Low End Trim',
    trimFadeTime: 'Trim Fade Time',
    deviceAddressProxyEnable: 'Device Address Proxy Enable',
    deviceAddressProxyTable: 'Device Address Proxy Table',
    deviceAddressProxyTimeout: 'Device Address Proxy Timeout',
    defaultOnValue: 'Default On Value',
    lastOnValue: 'Last On Value',
    authorizationCache: 'Authorization Cache',
    authorizationGroups: 'Authorization Groups',
    authorizationPolicy: 'Authorization Policy',
    authorizationScope: 'Authorization Scope',
    authorizationServer: 'Authorization Server',
    authorizationStatus: 'Authorization Status',
    maxProxiedIAmsPerSecond: 'Max Proxied I Ams Per Second',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) => _labels[value] ?? 'Property $value';
}
