// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet confirmed service choices (BACnetConfirmedServiceChoice).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetConfirmedService(value)`.
extension type const BacnetConfirmedService(int value) implements int {
  /// Acknowledge Alarm.
  static const acknowledgeAlarm = BacnetConfirmedService(0);

  /// COV Notification.
  static const covNotification = BacnetConfirmedService(1);

  /// Event Notification.
  static const eventNotification = BacnetConfirmedService(2);

  /// Get Alarm Summary.
  static const getAlarmSummary = BacnetConfirmedService(3);

  /// Get Enrollment Summary.
  static const getEnrollmentSummary = BacnetConfirmedService(4);

  /// Subscribe COV.
  static const subscribeCov = BacnetConfirmedService(5);

  /// Atomic Read File.
  static const atomicReadFile = BacnetConfirmedService(6);

  /// Atomic Write File.
  static const atomicWriteFile = BacnetConfirmedService(7);

  /// Add List Element.
  static const addListElement = BacnetConfirmedService(8);

  /// Remove List Element.
  static const removeListElement = BacnetConfirmedService(9);

  /// Create Object.
  static const createObject = BacnetConfirmedService(10);

  /// Delete Object.
  static const deleteObject = BacnetConfirmedService(11);

  /// Read Property.
  static const readProperty = BacnetConfirmedService(12);

  /// Read Prop Conditional.
  static const readPropertyConditional = BacnetConfirmedService(13);

  /// Read Prop Multiple.
  static const readPropertyMultiple = BacnetConfirmedService(14);

  /// Write Property.
  static const writeProperty = BacnetConfirmedService(15);

  /// Write Prop Multiple.
  static const writePropertyMultiple = BacnetConfirmedService(16);

  /// Device Communication Control.
  static const deviceCommunicationControl = BacnetConfirmedService(17);

  /// Private Transfer.
  static const privateTransfer = BacnetConfirmedService(18);

  /// Text Message.
  static const textMessage = BacnetConfirmedService(19);

  /// Reinitialize Device.
  static const reinitializeDevice = BacnetConfirmedService(20);

  /// VT Open.
  static const vtOpen = BacnetConfirmedService(21);

  /// VT Close.
  static const vtClose = BacnetConfirmedService(22);

  /// VT Data.
  static const vtData = BacnetConfirmedService(23);

  /// Authenticate.
  static const authenticate = BacnetConfirmedService(24);

  /// Request Key.
  static const requestKey = BacnetConfirmedService(25);

  /// Read Range.
  static const readRange = BacnetConfirmedService(26);

  /// Life Safety Operation.
  static const lifeSafetyOperation = BacnetConfirmedService(27);

  /// Subscribe COV Property.
  static const subscribeCovProperty = BacnetConfirmedService(28);

  /// Get Event Information.
  static const getEventInformation = BacnetConfirmedService(29);

  /// Subscribe COV Property Multiple.
  static const subscribeCovPropertyMultiple = BacnetConfirmedService(30);

  /// COV Notification Multiple.
  static const covNotificationMultiple = BacnetConfirmedService(31);

  /// Audit Notification.
  static const auditNotification = BacnetConfirmedService(32);

  /// Audit Log Query.
  static const auditLogQuery = BacnetConfirmedService(33);

  /// Auth Request.
  static const authorizationRequest = BacnetConfirmedService(34);

  static const Map<BacnetConfirmedService, String> _labels = {
    acknowledgeAlarm: 'Acknowledge Alarm',
    covNotification: 'COV Notification',
    eventNotification: 'Event Notification',
    getAlarmSummary: 'Get Alarm Summary',
    getEnrollmentSummary: 'Get Enrollment Summary',
    subscribeCov: 'Subscribe COV',
    atomicReadFile: 'Atomic Read File',
    atomicWriteFile: 'Atomic Write File',
    addListElement: 'Add List Element',
    removeListElement: 'Remove List Element',
    createObject: 'Create Object',
    deleteObject: 'Delete Object',
    readProperty: 'Read Property',
    readPropertyConditional: 'Read Prop Conditional',
    readPropertyMultiple: 'Read Prop Multiple',
    writeProperty: 'Write Property',
    writePropertyMultiple: 'Write Prop Multiple',
    deviceCommunicationControl: 'Device Communication Control',
    privateTransfer: 'Private Transfer',
    textMessage: 'Text Message',
    reinitializeDevice: 'Reinitialize Device',
    vtOpen: 'VT Open',
    vtClose: 'VT Close',
    vtData: 'VT Data',
    authenticate: 'Authenticate',
    requestKey: 'Request Key',
    readRange: 'Read Range',
    lifeSafetyOperation: 'Life Safety Operation',
    subscribeCovProperty: 'Subscribe COV Property',
    getEventInformation: 'Get Event Information',
    subscribeCovPropertyMultiple: 'Subscribe COV Property Multiple',
    covNotificationMultiple: 'COV Notification Multiple',
    auditNotification: 'Audit Notification',
    auditLogQuery: 'Audit Log Query',
    authorizationRequest: 'Auth Request',
  };

  /// All values defined by this library.
  static Iterable<BacnetConfirmedService> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) =>
      _labels[value] ?? 'Confirmed Service $value';

  /// Human readable name of this value.
  String get label => getName(value);
}

/// BACnet unconfirmed service choices (BACnetUnconfirmedServiceChoice).
///
/// An extension type over the encoded value: it is an [int] at
/// runtime and can be used wherever an int is expected. Values
/// this library does not define (proprietary or newer ones) are
/// created with `BacnetUnconfirmedService(value)`.
extension type const BacnetUnconfirmedService(int value) implements int {
  /// I Am.
  static const iAm = BacnetUnconfirmedService(0);

  /// I Have.
  static const iHave = BacnetUnconfirmedService(1);

  /// COV Notification.
  static const covNotification = BacnetUnconfirmedService(2);

  /// Event Notification.
  static const eventNotification = BacnetUnconfirmedService(3);

  /// Private Transfer.
  static const privateTransfer = BacnetUnconfirmedService(4);

  /// Text Message.
  static const textMessage = BacnetUnconfirmedService(5);

  /// Time Synchronization.
  static const timeSynchronization = BacnetUnconfirmedService(6);

  /// Who Has.
  static const whoHas = BacnetUnconfirmedService(7);

  /// Who Is.
  static const whoIs = BacnetUnconfirmedService(8);

  /// UTC Time Synchronization.
  static const utcTimeSynchronization = BacnetUnconfirmedService(9);

  /// Write Group.
  static const writeGroup = BacnetUnconfirmedService(10);

  /// COV Notification Multiple.
  static const covNotificationMultiple = BacnetUnconfirmedService(11);

  /// Audit Notification.
  static const auditNotification = BacnetUnconfirmedService(12);

  /// Who Am I.
  static const whoAmI = BacnetUnconfirmedService(13);

  /// You Are.
  static const youAre = BacnetUnconfirmedService(14);

  static const Map<BacnetUnconfirmedService, String> _labels = {
    iAm: 'I Am',
    iHave: 'I Have',
    covNotification: 'COV Notification',
    eventNotification: 'Event Notification',
    privateTransfer: 'Private Transfer',
    textMessage: 'Text Message',
    timeSynchronization: 'Time Synchronization',
    whoHas: 'Who Has',
    whoIs: 'Who Is',
    utcTimeSynchronization: 'UTC Time Synchronization',
    writeGroup: 'Write Group',
    covNotificationMultiple: 'COV Notification Multiple',
    auditNotification: 'Audit Notification',
    whoAmI: 'Who Am I',
    youAre: 'You Are',
  };

  /// All values defined by this library.
  static Iterable<BacnetUnconfirmedService> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) =>
      _labels[value] ?? 'Unconfirmed Service $value';

  /// Human readable name of this value.
  String get label => getName(value);
}
