// GENERATED by tool/generate_constants.dart from
// bacnet-stack bacenum.h. Do not edit.

/// BACnet confirmed service choices (BACnetConfirmedServiceChoice).
abstract final class BacnetConfirmedService {
  /// Acknowledge Alarm.
  static const int acknowledgeAlarm = 0;

  /// COV Notification.
  static const int covNotification = 1;

  /// Event Notification.
  static const int eventNotification = 2;

  /// Get Alarm Summary.
  static const int getAlarmSummary = 3;

  /// Get Enrollment Summary.
  static const int getEnrollmentSummary = 4;

  /// Subscribe COV.
  static const int subscribeCov = 5;

  /// Atomic Read File.
  static const int atomicReadFile = 6;

  /// Atomic Write File.
  static const int atomicWriteFile = 7;

  /// Add List Element.
  static const int addListElement = 8;

  /// Remove List Element.
  static const int removeListElement = 9;

  /// Create Object.
  static const int createObject = 10;

  /// Delete Object.
  static const int deleteObject = 11;

  /// Read Property.
  static const int readProperty = 12;

  /// Read Prop Conditional.
  static const int readPropertyConditional = 13;

  /// Read Prop Multiple.
  static const int readPropertyMultiple = 14;

  /// Write Property.
  static const int writeProperty = 15;

  /// Write Prop Multiple.
  static const int writePropertyMultiple = 16;

  /// Device Communication Control.
  static const int deviceCommunicationControl = 17;

  /// Private Transfer.
  static const int privateTransfer = 18;

  /// Text Message.
  static const int textMessage = 19;

  /// Reinitialize Device.
  static const int reinitializeDevice = 20;

  /// VT Open.
  static const int vtOpen = 21;

  /// VT Close.
  static const int vtClose = 22;

  /// VT Data.
  static const int vtData = 23;

  /// Authenticate.
  static const int authenticate = 24;

  /// Request Key.
  static const int requestKey = 25;

  /// Read Range.
  static const int readRange = 26;

  /// Life Safety Operation.
  static const int lifeSafetyOperation = 27;

  /// Subscribe COV Property.
  static const int subscribeCovProperty = 28;

  /// Get Event Information.
  static const int getEventInformation = 29;

  /// Subscribe COV Property Multiple.
  static const int subscribeCovPropertyMultiple = 30;

  /// COV Notification Multiple.
  static const int covNotificationMultiple = 31;

  /// Audit Notification.
  static const int auditNotification = 32;

  /// Audit Log Query.
  static const int auditLogQuery = 33;

  /// Auth Request.
  static const int authorizationRequest = 34;

  static const Map<int, String> _labels = {
    acknowledgeAlarm: 'Acknowledge Alarm',
    covNotification: 'COV Notification',
    eventNotification: 'Event Notification',
    getAlarmSummary: 'Get Alarm Summary',
    getEnrollmentSummary: 'Get Enrollment Summary',
    subscribeCov: 'Subscribe COV',
    atomicReadFile: 'Atomic Read File',
    atomicWriteFile: 'Atomic Write File',
    addListElement: 'Add List Element',
    removeListElement: 'Remove List Element',
    createObject: 'Create Object',
    deleteObject: 'Delete Object',
    readProperty: 'Read Property',
    readPropertyConditional: 'Read Prop Conditional',
    readPropertyMultiple: 'Read Prop Multiple',
    writeProperty: 'Write Property',
    writePropertyMultiple: 'Write Prop Multiple',
    deviceCommunicationControl: 'Device Communication Control',
    privateTransfer: 'Private Transfer',
    textMessage: 'Text Message',
    reinitializeDevice: 'Reinitialize Device',
    vtOpen: 'VT Open',
    vtClose: 'VT Close',
    vtData: 'VT Data',
    authenticate: 'Authenticate',
    requestKey: 'Request Key',
    readRange: 'Read Range',
    lifeSafetyOperation: 'Life Safety Operation',
    subscribeCovProperty: 'Subscribe COV Property',
    getEventInformation: 'Get Event Information',
    subscribeCovPropertyMultiple: 'Subscribe COV Property Multiple',
    covNotificationMultiple: 'COV Notification Multiple',
    auditNotification: 'Audit Notification',
    auditLogQuery: 'Audit Log Query',
    authorizationRequest: 'Auth Request',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) =>
      _labels[value] ?? 'Confirmed Service $value';
}

/// BACnet unconfirmed service choices (BACnetUnconfirmedServiceChoice).
abstract final class BacnetUnconfirmedService {
  /// I Am.
  static const int iAm = 0;

  /// I Have.
  static const int iHave = 1;

  /// COV Notification.
  static const int covNotification = 2;

  /// Event Notification.
  static const int eventNotification = 3;

  /// Private Transfer.
  static const int privateTransfer = 4;

  /// Text Message.
  static const int textMessage = 5;

  /// Time Synchronization.
  static const int timeSynchronization = 6;

  /// Who Has.
  static const int whoHas = 7;

  /// Who Is.
  static const int whoIs = 8;

  /// UTC Time Synchronization.
  static const int utcTimeSynchronization = 9;

  /// Write Group.
  static const int writeGroup = 10;

  /// COV Notification Multiple.
  static const int covNotificationMultiple = 11;

  /// Audit Notification.
  static const int auditNotification = 12;

  /// Who Am I.
  static const int whoAmI = 13;

  /// You Are.
  static const int youAre = 14;

  static const Map<int, String> _labels = {
    iAm: 'I Am',
    iHave: 'I Have',
    covNotification: 'COV Notification',
    eventNotification: 'Event Notification',
    privateTransfer: 'Private Transfer',
    textMessage: 'Text Message',
    timeSynchronization: 'Time Synchronization',
    whoHas: 'Who Has',
    whoIs: 'Who Is',
    utcTimeSynchronization: 'UTC Time Synchronization',
    writeGroup: 'Write Group',
    covNotificationMultiple: 'COV Notification Multiple',
    auditNotification: 'Audit Notification',
    whoAmI: 'Who Am I',
    youAre: 'You Are',
  };

  /// All values defined by this library.
  static Iterable<int> get values => _labels.keys;

  /// Human readable name of [value].
  static String getName(int value) =>
      _labels[value] ?? 'Unconfirmed Service $value';
}
