#!/usr/bin/env python3
"""Generates native/src/bp_object_table.h from bacnet-stack's device.c.

The default object table of bacnet-stack contains object types whose Init()
creates fixed demo instances (Command, Trend Log, Schedule, Access Control).
The plugin server must only expose objects created by the application, so it
uses a copy of the table without those types.

Run after updating the bacnet-stack submodule:
    python3 tool/gen_object_table.py
"""
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
DEVICE_C = ROOT / "native/bacnet-stack/src/bacnet/basic/object/device.c"
OUTPUT = ROOT / "native/src/bp_object_table.h"

# object types with statically allocated demo instances
EXCLUDED = {
    "OBJECT_COMMAND",
    "OBJECT_TRENDLOG",
    "OBJECT_SCHEDULE",
    "OBJECT_ACCESS_CREDENTIAL",
    "OBJECT_ACCESS_DOOR",
    "OBJECT_ACCESS_POINT",
    "OBJECT_ACCESS_RIGHTS",
    "OBJECT_ACCESS_USER",
    "OBJECT_ACCESS_ZONE",
    "OBJECT_CREDENTIAL_DATA_INPUT",
}


def main() -> None:
    source = DEVICE_C.read_text()
    includes = re.findall(r'^#include "bacnet/basic/object/[^"]+"$', source, re.M)
    start = source.index("static object_functions_t Default_Object_Table[] = {")
    end = source.index("\n};", start)
    body = source[start:end].split("\n")[1:]

    out_lines = []
    entry = []
    depth = 0
    for line in body:
        stripped = line.strip()
        if depth == 0 and stripped.startswith("#"):
            out_lines.append(line)
            continue
        if depth == 0 and not stripped:
            continue
        entry.append(line)
        depth += line.count("{") - line.count("}")
        if depth == 0:
            text = "\n".join(entry)
            match = re.search(r"\{\s*(\w+)", text)
            if match is None or match.group(1) not in EXCLUDED:
                out_lines.append(text)
            entry = []

    header = [
        "/* Generated by tool/gen_object_table.py from bacnet-stack device.c."
        " Do not edit. */",
        "#ifndef BP_OBJECT_TABLE_H",
        "#define BP_OBJECT_TABLE_H",
        "",
        *includes,
        "",
        "static object_functions_t BP_Object_Table[] = {",
        *out_lines,
        "};",
        "",
        "#endif",
        "",
    ]
    OUTPUT.write_text("\n".join(header))
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
